### ISSUE TITLE
Throw exceptions when accessing some HTTPS images

### ISSUE THREAD

**Issue by wangwanxiong** [Baseflow/flutter_cached_network_image#109]
`I/flutter (18846): HandshakeException: Handshake error in client (OS Error:`
`I/flutter (18846):      CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:363))`
`I/flutter (18846):`
` ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE 
SERVICE╞════════════════════════════════════════════════════`
`I/flutter (18846): The following message was thrown resolving an image codec:`
`I/flutter (18846): Couldn't download or retreive file.`

**Comment by lifetin** [comment]
我也遇到了这样的问题.
![44](https://user-images.githubusercontent.com/10474968/56844286-6c45fd80-68e0-11e9-9c6f-ffedb6039699.png)

**Comment by lifetin** [comment]
执行下Flutter clean
就好了

**Comment by Jason-zzzz** [comment]
solution:https://stackoverflow.com/questions/49638183/flutter-image-network-throws-handshakeexception/60019856#60019856?newreg=1b19c150c8b140788ac71d380b771a2b
