### ISSUE TITLE
Performance issue on long list

### ISSUE THREAD

**Issue by eikebartels** [Baseflow/flutter_cached_network_image#118]
Hey, 

first of all thanks for the nice and useful library. 

I have a list with about 100 items with each 2 images. If I scroll down quick the frame rate drops almost to 0. Any idea how to solve this issue?

**Comment by renefloor** [comment]
@eikebartels could you try version 0.6.0-beta. We made quite a lot of improvements on the performance.

**Comment by eikebartels** [comment]
@renefloor  where do I find 0.6.0-beta? I only see 0.2.0+1 in the pub and v0.5.1 in on GitHub.

**Comment by renefloor** [comment]
@eikebartels the beta should be on pub: https://pub.dartlang.org/packages/cached_network_image/versions/0.6.0-beta+1

**Comment by Hanggi** [comment]
I'm using 0.6.2, still has bad performance with fast scrolling.

**Comment by renefloor** [comment]
It should largely be improved in 2.3.0-beta
