### ISSUE TITLE
Problems with FadeTransition

### ISSUE THREAD

**Issue by AleSpero** [Baseflow/flutter_cached_network_image#141]
Hello,

I'm using your library to render an image which will be the size of the screen.
I made a custom placeholder widget which has a blue background color, but when the image is loaded the screen flashes white because of the fadetransition applied to the image. This is particularly frustrating for the user. 

Is there any thing i can do to transition from the color of the placeholder directly to the image avoiding the flashing white of the fadetransition? 

I also noticed that changing the ThemeData brightness to dark the image doesn't flash white but does flash a grey color, so i suppose the fadetransition is using a theme data attribute. I tried searching the library source code but i didn't find anything. 

Thank you for the good work anyways. :D

**Comment by AleSpero** [comment]
Ok so i think i found a workaround that's working, at least for me:

it seems that the animation takes the color from the attribute `scaffoldBackgroundColor` of the ThemeData. So after changing this color i was able to transition from the color of my choosing, to the image.

**Comment by tangtaoit** [comment]
![cache_image_demo](https://user-images.githubusercontent.com/3895878/54595906-90572900-4a6e-11e9-9eca-3dc350dc4415.gif)

**Comment by dshukertjr** [comment]
It would be nice to get this issue fixed

**Comment by lifetin** [comment]
期待

**Comment by renefloor** [comment]
I guess this is improved in 1.1.0, but not sure. 
Can you supply me with an example code?

**Comment by dshukertjr** [comment]
Using any placeholder results in this white blink shown by @tangtaoit .

**Comment by sosite** [comment]
The problem is with image transitions because on the moment we have a black background between transions :/

**Comment by renefloor** [comment]
In 2.3.0-beta it shouldn't fade when the image is already loaded. Love to hear your feedback on that version.

**Comment by royston-c** [comment]
@renefloor I haven't fully tested 2.3.0-beta but this it appears to have fixed this issue for me. Cached images no longer fade in. I can also confirm it works with a Hero animation. looks great, nice work! 👍
