### ISSUE TITLE
The images inside a list is not pre-loaded

### ISSUE THREAD

**Issue by michealchow2324** [Baseflow/flutter_cached_network_image#151]
I am displaying a list of images with CachedNetworkImage. But it seems like the images were not saved to the cache file, since every time when I scroll the list, the images out of the device were not pre-loaded. Is there any additional setup to make?
my code:
```
             new CachedNetworkImage(
                fit: BoxFit.fitWidth,
                height: 100.0,
                imageUrl: imageUrl,
                placeholder: (context, url) {
                    new CircularProgressIndicator();
                } ,
                errorWidget: (context, url, error) => new Icon(Icons.error),
              ),
            ),
```

**Comment by renefloor** [comment]
Have many images do you have on your list. The defaultcachemanager has a limit of 200 items. You can change this by supplying your own BaseCacheManager.
Do the images load from the cache when not in a list?
