### ISSUE TITLE
Performance issue with CachedNetworkImageProvider and FadeInImage on long list

### ISSUE THREAD

**Issue by EDnny12** [Baseflow/flutter_cached_network_image#178]
Scroll on long list is slow with CachedNetworkImageProvider and FadeInImage

can you update for better perfomance?

**Comment by renefloor** [comment]
Did it improve in 1.1.0?

**Comment by MohammedYAmmar** [comment]
No it's still makes the list slow 

I think that the problem  is related  to that
All the image is loading at the same time
So it take a lot of devices resources

**Comment by renefloor** [comment]
If it's still an issue with FadeInImage you can just try with CachedNetworkImage version 2.3.0-beta, it should have a better performance.
