### ISSUE TITLE
Blink

### ISSUE THREAD

**Issue by fengyuxx** [Baseflow/flutter_cached_network_image#195]
When I use cached_network_image as children of "reorderables",
cached_network_image blink when I start drag it.

reorderables
https://pub.dev/packages/reorderables

**Comment by sosite** [comment]
It can be similar problem to https://github.com/renefloor/flutter_cached_network_image/issues/141.

**Comment by renefloor** [comment]
Should be fixed in 2.3.0-beta, it would be nice if you can verify
