### ISSUE TITLE
Error calling sqlite3_step (1: cannot rollback - no transaction is active) SQLITE_ERROR

### ISSUE THREAD

**Issue by chavesgu** [Baseflow/flutter_cached_network_image#205]
when i use this plugin,this text will be shown in the console.

**Comment by renefloor** [comment]
Can you reproduce it? I'm not getting this error.

**Comment by edwardchow33** [comment]
i got the same error when performing hot restart. 

> Performing hot restart...                                               
> Restarted application in 1,055ms.
> Error calling sqlite3_step (1: cannot rollback - no transaction is active) SQLITE_ERROR
> DB Query: ROLLBACK
> Unknown error finalizing or resetting statement (1: cannot rollback - no transaction is active)
> DB Query: ROLLBACK
>
