### ISSUE TITLE
CachedNetworkImageProvider overrides maxRadius of CircleAvatar

### ISSUE THREAD

**Issue by khainke** [Baseflow/flutter_cached_network_image#213]
When doing:
```dart
CircleAvatar(
      maxRadius: x,
      backgroundImage:  CachedNetworkImageProvider(url),
    )
```
the CircleAvatar somehow ignores the maxRadius and scales itself to aspect ratios different from 1:1, (the image itself is not distorted, but the circle is now an ellipse instead of a circle), this does not happen with other image providers.

**Comment by renefloor** [comment]
I changed a lot in 2.2.0, would be weird if there is still a difference with other image providers
