### ISSUE TITLE
我遇到了一个问题，我不确定是不是您的框架导致的

### ISSUE THREAD

**Issue by 2697a** [Baseflow/flutter_cached_network_image#214]
当一个页面的ListView图片加载完成后，在开启一个新的页面，停留一段时间返回，原来页面的图片会重新加载

**Comment by zhancheng** [comment]
这个是flutter框架本身的机制

**Comment by zhangweiwei0326** [comment]
也有这个问题

**Comment by iTiaNex** [comment]
乡亲们，问题解决了么，怎么清除那个缓存图片，
默认这个插件不是在软件目录cache下面？
在系统临时 目录么

**Comment by 972091604** [comment]
是加载图片尺寸过大的问题，不加载大尺寸图片就没问题了

**Comment by renefloor** [comment]
Sorry, we only can support English. If there is still an issue make a new ticket in English please.
