### ISSUE TITLE
Colored background on error

### ISSUE THREAD

**Issue by deakjahn** [Baseflow/flutter_cached_network_image#218]
`errorWidget` nicely shows alternative images or icons but a mere `Container(color: ...)` doesn't seem to work, seemingly because of sizing issues (Flutter probably renders it with zero size).

**Comment by renefloor** [comment]
@deakjahn what if you wrap the container in a `SizedBox.expand`?

**Comment by deakjahn** [comment]
Oh, that was so long ago, I wasn't even aware of it. Anyway, now that I moved on to Octo, it probably wasn't important, anyway. :-)

**Comment by renefloor** [comment]
No problem, I'm just cleaning up the backlog
