### ISSUE TITLE
All the goodies minus the cache?

### ISSUE THREAD

**Issue by brianegan** [Baseflow/flutter_cached_network_image#22]
Hey hey :)

I really love this library! I've found a situation where I want the goodies, such as a placeholder Widget and error fallback without the cache.

Ideas:

  1. Create a base package (I've called mine fancy_network_image to prototype) that provides the Goodies, without the cache.  CachedNetworkImage would extend from the base classes this lib provides. Prototype here: https://github.com/brianegan/fancy_network_image & https://github.com/brianegan/flutter_cached_network_image/tree/fancy-network-image
  2. Create a `cache` boolean. If false, the image won't be cached (then the name CachedNetworkImage sounds a bit weird, but wouldn't require 2 different libs).

What are your thoughts!? If you like one of those ideas, happy to push up PRs.

**Comment by renefloor** [comment]
Hi @brianegan 
Thanks for the suggestions. I indeed think that the image with the placeholder and error widget could be a standalone package. I had to hack the errorListener in the imageprovider as the ImageStream only gives a `OnFinished` kind of listener and not and `OnError` kind. I want to have a better look at the flutter source and maybe do a pull request on that to add errorListeners on the ImageStream. That way I can change this to accept any ImageProvider which would be a better solution than keep adding functions to the CachedImageProvider. Your case should be able to use a generic NetworkImage.

**Comment by brianegan** [comment]
@renefloor Hah, that's exactly what I found too! I ended up just ripping the `NetworkImage` out of the framework and putting that into my prototype library so I had complete control.

Would be very cool to see an error callback solution.

**Comment by matejthetree** [comment]
Can you not do @brianegan FadeInImage to achieve that?

**Comment by brianegan** [comment]
@matejthetree Not a bad idea! Unfortunately, `FadeInImage` only supports placeholder images, but not fallback images in case the image fails to load. That was the use-case I needed to solve at the time, so I ended up forking this lib and rolling my own ImageProvider that gave me the ability to do just that.

**Comment by renefloor** [comment]
@brianegan This issue can finally be closed 😄. (See [OctoImage](https://pub.dev/packages/octo_image)). Although the errorListeners in Flutter were still shaky.
