### ISSUE TITLE
terrible problem！all cache image did not render sometime.

### ISSUE THREAD

**Issue by zhancheng** [Baseflow/flutter_cached_network_image#220]
java.lang.Throwable: DatabaseException(no such table: cacheObject (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM cacheObject WHERE url = ?) sql 'SELECT * FROM cacheObject WHERE url = ?' args [https://dl.weshineapp.com/app_pcp/20190813/2e8cbfa46b14895609e5a0516a3ffed4.png!150]}

**Comment by renefloor** [comment]
Is this still an issue?

**Comment by zhancheng** [comment]
@renefloor im not sure, i notice that the flutter_cache_network_image use database conflict with my app database at the same time when app start.

**Comment by renefloor** [comment]
I guess it is a duplicate of #299 then. I think we need to move away from using sqflite to fix that.

**Comment by imran-samed** [comment]
@renefloor Why u closing issue without any solution
