### ISSUE TITLE
Cached Image getting weird blink every a swipe happens in my app?

### ISSUE THREAD

**Issue by mikeyyg96** [Baseflow/flutter_cached_network_image#221]
![CachedNetworkBlinkIssue](https://user-images.githubusercontent.com/33616962/63125363-7c5f1700-bf7b-11e9-9b8a-b62d7b49ba00.gif)

[https://gist.github.com/mikeyyg96/a33bed217ae80b69b98667af54d110fd](url)

**Comment by Jer0** [comment]
I have the same problem

**Comment by mikeyyg96** [comment]
I fixed the problem. For me, it was because the image size was too large. I pulled these images from Google not knowing the sizes. I stick with smaller images now.

**Comment by Jer0** [comment]
That solution may help me, right now I am loading high resolution images, I will try less, thanks!

**Comment by maxmoros** [comment]
I have same issue. When app launches, home screen fades in two CachedNetworkImage's then blinks both areas white. After the white blink both images show immediately without fade in. This is gross for the user experience. 

I suspect it has something to do with another area of the widget setting state pulling server data.

I had a similar issue with Image.asset and was able to resolve by setting 'gaplessPlayback: true'

**Comment by renefloor** [comment]
This should be fixed in 2.3.0-beta, it would be nice if any of you can verify this.
