### ISSUE TITLE
i cant install the package flutter cached network image 

### ISSUE THREAD

**Issue by mahdicha** [Baseflow/flutter_cached_network_image#228]
![Capture01](https://user-images.githubusercontent.com/48725749/63634619-dda87980-c650-11e9-8a3d-7b0ecbea6a0c.PNG)
![Capture02](https://user-images.githubusercontent.com/48725749/63634620-dda87980-c650-11e9-9728-596e906e9a65.PNG)

**Comment by renefloor** [comment]
Could you try packages upgrade?
