### ISSUE TITLE
adding gaplessPlayback: true to internal Image

### ISSUE THREAD

**Issue by jaleelmeemo** [Baseflow/flutter_cached_network_image#231]
can we add gaplessplayback parameter here https://github.com/renefloor/flutter_cached_network_image/blob/master/lib/src/cached_image_widget.dart

or make it an option in the constructor, else some cases where rebuilds are triggered will briefly show a blank area before loading the asset

**Comment by basnetjiten** [comment]
Is there any workaround for this issues ? What could be the alternative to gaplessPlayBack ?

**Comment by renefloor** [comment]
This should already work with useOldImageOnUrlChange, if not you can reopen the issue
