### ISSUE TITLE
how can I get loading progress to update my ProgressIndicator?

### ISSUE THREAD

**Issue by VadimOsovsky** [Baseflow/flutter_cached_network_image#233]

**Comment by GrahamDi** [comment]
@renefloor 
Hi, Is this being worked on eg. togther with issue #365? Thanks.

**Comment by renefloor** [comment]
@GrahamDi yes, the widget already supports it. The development of the ImageProvider is already finished, will be released soon.

**Comment by GrahamDi** [comment]
@renefloor  Great stuff! Thanks for your rapid response.

**Comment by renefloor** [comment]
ImageProvider is released in 2.2.0

**Comment by GrahamDi** [comment]
Works great, thank you.
