### ISSUE TITLE
 BaseCacheManager.getFile(package:flutter_cache_manager/src/cache_manager.dart:120)

### ISSUE THREAD

**Issue by qq3144225600** [Baseflow/flutter_cached_network_image#234]
Dart.0 BaseCacheManager.getFile(package:flutter_cache_manager/src/cache_manager.dart:120)
--
2 Dart.1 CachedNetworkImageState._animatedWidget(package:cached_network_image/src/cached_image_widget.dart:270)
3 Dart.2 CachedNetworkImageState.build(package:cached_network_image/src/cached_image_widget.dart:196)
4 Dart.3 StatefulElement.build(package:flutter/src/widgets/framework.dart:4012)
5 Dart.4 ComponentElement.performRebuild(package:flutter/src/widgets/framework.dart:3924)
6 Dart.5 Element.rebuild(package:flutter/src/widgets/framework.dart:3721)
7 Dart.6 ComponentElement._firstBuild(package:flutter/src/widgets/framework.dart:3907)
8 Dart.7 StatefulElement._firstBuild(package:flutter/src/widgets/framework.dart:4053)
9 Dart.8 ComponentElement.mount(package:flutter/src/widgets/framework.dart:3902)
10 Dart.9 Element.inflateWidget(package:flutter/src/widgets/framework.dart:3084)
11 Dart.10 Element.updateChild(package:flutter/src/widgets/framework.dart:2887)
12 Dart.11 SingleChildRenderObjectElement.mount(package:flutter/src/widgets/framework.dart:5092)
13 Dart.12 Element.inflateWidget(package:flutter/src/widgets/framework.dart:3084)
14 Dart.13 Element.updateChild(package:flutter/src/widgets/framework.dart:2887)
15 Dart.14 SingleChildRenderObjectElement.mount(package:flutter/src/widgets/framework.dart:5092)

**Comment by JonathanJude** [comment]
I'm having this issue too.

**Comment by kaciula** [comment]
Is there any plan to fix this? I get plenty crash reports because of this. I was assuming this package is production-ready seeing that it is recommended on the official Flutter site.

**Comment by yrom** [comment]
Duplicated #216

**Comment by renefloor** [comment]
possible duplicate of #273
