### ISSUE TITLE
[Feature Request] Add option to clear a specific image from cache

### ISSUE THREAD

**Issue by RollyPeres** [Baseflow/flutter_cached_network_image#237]
Users should be able to clear certain cached image and force a re-download and re-cache at the same time, even if maxAge hasn't expired yet.

**Comment by renefloor** [comment]
CacheManager support [removeFile](https://pub.dev/documentation/flutter_cache_manager/latest/flutter_cache_manager/BaseCacheManager/removeFile.html) and [downloadFile](https://pub.dev/documentation/flutter_cache_manager/latest/flutter_cache_manager/BaseCacheManager/downloadFile.html).
