### ISSUE TITLE
this package and facebook login package seems to crash the app

### ISSUE THREAD

**Issue by Mikkelet** [Baseflow/flutter_cached_network_image#243]
narrowed the crash down to these dependencies:
  flutter_facebook_login: ^2.0.1
  cached_network_image: ^1.1.1

multidex enabled,
gradle.properties
android.useAndroidX=true
android.enableJetifier=true

**Comment by renefloor** [comment]
I really need more info to investigate this. How does it crash and with what kind of error? If you are still having problems please reopen with more info.
