### ISSUE TITLE
App crash if image url is not valid and returns 404 on browser

### ISSUE THREAD

**Issue by achalkias** [Baseflow/flutter_cached_network_image#245]
WebHelper._downloadRemoteFile.<anonymous closure> (/Users/apostoloschalkias/.pub-cache/hosted/pub.dartlang.org/flutter_cache_manager-1.1.1/lib/src/web_helper.dart:70)
<asynchronous gap> (Unknown Source:0)
new Future.sync (dart:async/future.dart:224)
WebHelper._downloadRemoteFile (/Users/apostoloschalkias/.pub-cache/hosted/pub.dartlang.org/flutter_cache_manager-1.1.1/lib/src/web_helper.dart:49)
<asynchronous gap> (Unknown Source:0)
WebHelper.downloadFile (/Users/apostoloschalkias/.pub-cache/hosted/pub.dartlang.org/flutter_cache_manager-1.1.1/lib/src/web_helper.dart:33)
<asynchronous gap> (Unknown Source:0)
BaseCacheManager.getFile (/Users/apostoloschalkias/.pub-cache/hosted/pub.dartlang.org/flutter_cache_manager-1.1.1/lib/src/cache_manager.dart:114)
<asynchronous gap> (Unknown Source:0)
BaseCacheManager.getFile (/Users/apostoloschalkias/.pub-cache/hosted/pub.dartlang.org/flutter_cache_manager-1.1.1/lib/src/cache_manager.dart:0)
CachedNetworkImageState._animatedWidget (/Users/apostoloschalkias/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.1/lib/src/cached_image_widget.dart:270)
CachedNetworkImageState.build (/Users/apostoloschalkias/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.1/lib/src/cached_image_widget.dart:196)
StatefulElement.build (/Users/apostoloschalkias/development/flutter/packages/flutter/lib/src/widgets/framework.dart:4047)
ComponentElement.performRebuild (/Users/apostoloschalkias/development/flutter/packages/flutter/lib/src/widgets/framework.dart:3941)
Element.rebuild (/Users/apostoloschalkias/development/flutter/packages/flutter/lib/src/widgets/framework.dart:3738)
ComponentElement._firstBuild (/Users/apostoloschalkias/development/flutter/packages/flutter/lib/src/widgets/framework.dart:3924)
StatefulElement._firstBuild (/Users/apostoloschalkias/development/flutter/packages/flutter/lib/src/widgets/framework.dart:4088)
ComponentElement.mount (/Users/apostoloschalkias/development/flutter/packages/flutter/lib/src/widgets/framework.dart:3919)
Element.inflateWidget (/Users/apostoloschalkias/development/flutter/packages/flutter/lib/src/widgets/framework.dart:3101)
MultiChildRenderObjectElement.mount (/Users/apostoloschalkias/development/flutter/packages/flutter/lib/src/widgets/framework.dart:5233)

**Comment by YAPPDEF** [comment]
Facing the same issue with statusCode 404

**Comment by renefloor** [comment]
grouping this in #273
