### ISSUE TITLE
Running out of memory exception in a staggered list view of images

### ISSUE THREAD

**Issue by Udaychinthala** [Baseflow/flutter_cached_network_image#254]
After scrolling to some point , Getting running out of memory exception in staggered list of images
and also PlaceHolder is just disappearing suddenly just before loading of image

**Comment by beydeng** [comment]
I have the same Issues...

**Comment by kennenfromchina** [comment]
I have the same problem, swipe the ListView quickly on the iOS platform, the app will crash when it receives the memory warning, I tested the memory up to 1.3GB.

**Comment by DyaryRaoof** [comment]
Having the same issue. Any updates guys  ? the issue was present in flutter Image.Network also which is solved (I THINK) by adding the CacheWidth and CacheHeight parameters to the Image.Network on the master channel. I have't yet found these parameters in the Cached_Network_Image.

**Comment by asjqkkkk** [comment]
I have the same problem..

**Comment by ozyl** [comment]
I also have this question, why is the memory usage getting bigger and causing crashes on Android devices.

**Comment by renefloor** [comment]
Let's move this discussion to #260
