### ISSUE TITLE
Fail to load this image

### ISSUE THREAD

**Issue by JCKodel** [Baseflow/flutter_cached_network_image#259]
![image](https://user-images.githubusercontent.com/379339/66246825-b9c76180-e6ed-11e9-9310-b113af95f789.png)

when trying to load this file: https://mcc-ticket.code.art.br/api/system/download?file=t842335_115f56_llx4yetr.png

**Comment by dzliergaard** [comment]
Similar issue. I think at some point the query parameters are being trimmed off the url, but I'm not sure where or why.

**Comment by MichaelMarner** [comment]
I take it this image nolonger exists? I get the following when trying to access:

```json
{"status":"fail","message":"Trying to get property of non-object","data":null}
```

**Comment by JCKodel** [comment]
> I take it this image nolonger exists? I get the following when trying to access:
> 
> ```json
> {"status":"fail","message":"Trying to get property of non-object","data":null}
> ```

No. It doesn't exist anymore. Try this one: `https://mcc-ticket.code.art.br/api/system/download?file=t109626_b4e0c1_qgagnnv3.png`

I guess the problem is the lack of filename (please tell me you're not determining the type of image by its extension >.<)

**Comment by MichaelMarner** [comment]
Same error with that image

**Comment by renefloor** [comment]
I guess it is a duplicate of #320. If not please reopen with an url that gives this problem.
