### ISSUE TITLE
Image blinks while scrolling.

### ISSUE THREAD

**Issue by pouloghost** [Baseflow/flutter_cached_network_image#274]
When using io.flutter.embedding.engine.FlutterEngine and changing widget height with gesture, image blinks( quickly changing between shown and hidden status). all becomes normal when changing back to Image widget.
flutter 1.7.8 hotfix4

**Comment by cbenhagen** [comment]
Possibly a duplicate of #258 ?

**Comment by renefloor** [comment]
probably fixed with #289, that is merged into develop (not yet master or release). If it is not fixed please reopen the issue.
