### ISSUE TITLE
No error callback when Could not instantiate image codec.

### ISSUE THREAD

**Issue by KingWu** [Baseflow/flutter_cached_network_image#281]
I pass a non image url into CachedNetworkImageProvider. The errorListener is not triggered.

----------
The following _Exception was thrown resolving an image codec:
Exception: Could not instantiate image codec.

When the exception was thrown, this was the stack: 
#0      _futurize (dart:ui/painting.dart:4134:5)
#1      instantiateImageCodec (dart:ui/painting.dart:1669:10)
#2      CachedNetworkImageProvider._loadAsyncFromFile (package:cached_network_image/src/cached_network_image_provider.dart:89:18)
<asynchronous suspension>
#3      CachedNetworkImageProvider._loadAsync (package:cached_network_image/src/cached_network_image_provider.dart:75:18)
...

**Comment by AresVampire** [comment]
I have the same problem

**Comment by didyqian** [comment]
I have the same problem

**Comment by wdlmm** [comment]
imageUrl:http://fistchain.org/download/icons/USDT.png   
i have the same problem

**Comment by renefloor** [comment]
Let's discuss this in #320
