### ISSUE TITLE
How to prevent re fetching image for empty imageUrl

### ISSUE THREAD

**Issue by NerditLtd** [Baseflow/flutter_cached_network_image#282]
I used cached_network_manager inside Slidable whenever I swipe right or left the CachedNetworkImage tries to reload imageUrl which is not required as I set placeholder and it blinks twice by swiping. what is a workaround to prevent this

**Comment by renefloor** [comment]
I'm not sure what you try to do. Do you use an empty url because you actually don't really want to load an image and just show the placeholder?

**Comment by mo-ah-dawood** [comment]
isURL(url)?CachedNetworkImage(...):errorWidget()
isURL is method in validators package

**Comment by renefloor** [comment]
Closing this because of no response.
