### ISSUE TITLE
started getting errors before move to rc 

### ISSUE THREAD

**Issue by greggdourgarian** [Baseflow/flutter_cached_network_image#285]
Was receiving error messages like 

> Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:

>  - TextInputClient.connectionClosed

These went away after moving to release candidate for this package.

**Comment by renefloor** [comment]
I don't think this has anything to do with CachedNetworkImage. Both ChipsInputState and TextInputClient are not used in the package.
