### ISSUE TITLE
Request to add cacheHeight and cacheWidth params

### ISSUE THREAD

**Issue by alectogeek** [Baseflow/flutter_cached_network_image#286]
Is there an ability to add cacheHeight and cacheWidth params in order to control imageCache? I have problems with running an app containing about 60 pictures on devices with RAM less than 2 GB, so I need to optimize caching images. I guess, it would be useful for many developers

**Comment by DyaryRaoof** [comment]
Hi. @renefloor When will see this feature added to cached network image. Currently 
we can't sheep our app to production because of crashes from Cached_Network_image which may be solved by adding of `cacheHeight `and `cacheWidth `parameters.

Your help is highly appreciated.
Thanks.

**Comment by renefloor** [comment]
I think it is better to already have the images of smaller size when getting them from the server as that limits the use of data, but it is a good feature request.

**Comment by humblerookie** [comment]
@DyaryRaoof @ alectogeek I made a small port of this library which respects container sizes while storing and loading to/from cache. Here it is https://pub.dev/packages/optimized_cached_image

**Comment by renefloor** [comment]
@humblerookie Some of the features you added are also already being added to flutter_cache_manager, such as [saving a file using a streamed http response](https://github.com/Baseflow/flutter_cache_manager/commit/fefc4d0fa0a53aa010fbcbae8008285fa01b7489). I'm open to PR's if you want to add things to this library. Currently I'm focussed on improving the cache manager with tests and requested features (for example progress is next on my list).

**Comment by humblerookie** [comment]
@renefloor  Is there some way we could collaborate more effectively? like over chat. I had a couple of queries.

**Comment by renefloor** [comment]
@humblerookie I'm often online on fluttercommunity.slack.com

**Comment by renefloor** [comment]
For memory cache I added memCacheHeight and width in 2.3.0-beta

**Comment by danielappelgren0** [comment]
@renefloor Just updated to use beta version 2.3.0-beta, don't i don't have access to the properties?

**Comment by renefloor** [comment]
@danielappelgren0 Maybe try pub upgrade?
I just added version 2.3.0-beta in a test project and I do have the properties:
```
CachedNetworkImage(memCacheHeight: 200, memCacheWidth: 200,),
```

**Comment by danielappelgren0** [comment]
@renefloor Just did that as well and it works, not use why it's not working in my app :)

**Comment by danielappelgren0** [comment]
@renefloor is where somewhere i can reach you, which is not Github ? i have some questions regarding the plugin?

**Comment by renefloor** [comment]
@danielappelgren0 I guess easiest is on the community slack: fluttercommunity.slack.com

**Comment by imtoori** [comment]
@danielappelgren0 did you manage to make it work? I'm having the same issue
