### ISSUE TITLE
Random problems while downloading images

### ISSUE THREAD

**Issue by aleaforny** [Baseflow/flutter_cached_network_image#287]
Hello all,

I'm facing a very strange issue while attempting to download a single PNG file, about 300 kb, not so large (perhaps 1024x768) and hosted on the same network. 

Sometimes, it works, and sometimes (most of the times, actually), I'm receiving these only messages :

```
I/flutter ( 5008): CacheManager: Failed to download file from http://test.lan/solar_panels.png with error:
I/flutter ( 5008): Connection closed while receiving data
I/flutter ( 5008): CacheManager: Failed to download file from http://test.lan/solar_panels.png with error:
I/flutter ( 5008): Connection closed while receiving data
```

I have no idea why; I can successfully retrieve this file from any web browser, every time and without a problem.

I've not found any issue similar to this here, but perhaps I've missed something (I hope so) 

Is there a more verbose output? Is there a way to fix this?

Thanks for your help, all

**Comment by aleaforny** [comment]
Just in addition to this, I've also reviewed the logs from my webserver, which correctly states the successful responses to the two requests sent by the Flutter app (also with the correct size) :

```
[12/Nov/2019 17:53:45] "GET /solar_panels.png HTTP/1.1" 200 319614
[12/Nov/2019 17:53:47] "GET /solar_panels.png HTTP/1.1" 200 319614
```

**Comment by MoacirSchmidt** [comment]
Same issue here. Which server are you using?

**Comment by aleaforny** [comment]
I thought I mentioned it, my bad.

I'm facing this issue with Django server (when Django serves static files itself)

Perhaps it's useful to mention that I'm not facing any issue when I'm testing from a real Android device, it's only happening on an emulated device, but it's still annoying.

**Comment by MoacirSchmidt** [comment]
I'm also not facing any issue from a real device.

My server is a Delphi Indy TIdHttpServer but I think this problem is not related with the server. It seems to be a problem with http as noticed on issues 

https://github.com/dart-lang/sdk/issues/33321

and

https://github.com/flutter/flutter/issues/22951

**Comment by renefloor** [comment]
You could try to extend the webhelper and use dio, maybe that helps. If it is a problem with the HttpClient I cannot help it, so I'll close the issue
