### ISSUE TITLE
CacheManager: Failed to download file (Permission denied, 403, Firebase Storage)

### ISSUE THREAD

**Issue by joknjokn** [Baseflow/flutter_cached_network_image#291]
Hi,

The plugin works, and it loads the images, but I get this error. No symptoms besides the error message. If I visit the image-url in my browser, Firebase returns "Permission denied". For some reason it works in the app anyway, so I'm not sure what is going on?

```
CacheManager: Failed to download file from https://firebasestorage.googleapis.com/myimageurl with error:
I/flutter (30817): HttpException: No valid statuscode. Statuscode was 403
```

Thanks,
- Jonas

**Comment by sandeep9607** [comment]
hello @joknjokn did you find solution?

**Comment by renefloor** [comment]
403 means you are not logged in. You probably have to send some headers with it. I don't know what you mean with 'for some reason it works in the app anyway'. So it loads once with success and fails once? If it is still a problem please reopen the issue.
