### ISSUE TITLE
global settings for error, placeholder

### ISSUE THREAD

**Issue by codecomeon** [Baseflow/flutter_cached_network_image#292]
we should not must to wrap cache_network_image to a custom widget

if we can set error, placeholder in global, will helpful

**Comment by bagus-repository** [comment]
What's wrong with making a custom widget, I do not get any problem wrapping CachedNetworkImage with a Container.

**Comment by MichaelMarner** [comment]
Wrapping the cached_network_image in a custom Widget to simplify configuration for repeated uses is the better approach here.

**Comment by renefloor** [comment]
I agree with @MichaelMarner and @bagus-repository. Making a global error and placeholder somewhere in this package will make it more complex.
