### ISSUE TITLE
 In the debugging state, if the imageUrl is empty, the impact will be interrupted

### ISSUE THREAD

**Issue by gs01md** [Baseflow/flutter_cached_network_image#293]
I think, without throwing an error, you can display the placeholder; the reason is that imageUrl may be empty at the beginning, because it may be the data requested by the network

**Comment by renefloor** [comment]
@gs01md I don't understand your problem. You want to show an image without url because you are downloading that url? Why show the image at all in that case? And why just in debugging state?
