### ISSUE TITLE
Not showing image from imageUrl in flutter web, instead showing placeholder image

### ISSUE THREAD

**Issue by dheerajsarwaiya** [Baseflow/flutter_cached_network_image#294]
version ^2.0.0-rc.1 is working perfectly with IOS and Android but not working in web. It is by default picking what ever is there in placeholder. Not showing error either. What am I missing in flutter web?

Output of flutter doctor
[✓] Flutter (Channel dev, v1.12.11, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (2 available)

**Comment by guidota** [comment]
Same here.

**Comment by YouBin-Choi** [comment]
same here

**Comment by JoaoArmando** [comment]
Sam here, you got it?

**Comment by LuizLeite** [comment]
Same here

**Comment by renefloor** [comment]
closing this and keeping #303
