### ISSUE TITLE
Incompatible with Flutter v1.13.0

### ISSUE THREAD

**Issue by AbdoXLabs** [Baseflow/flutter_cached_network_image#297]
Error Message after `flutter run`

> Compiler message:
> ../../../../../.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error:
> The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
>   ImageStreamCompleter load(CachedNetworkImageProvider key) {
>                        ^
> ../../../../sdks/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method
> ('load').
>   ImageStreamCompleter load(T key, DecoderCallback decode);
>                        ^
> Target kernel_snapshot failed: Exception: Errors during snapshot creation: null

**Comment by shervn-r** [comment]
As mentioned in [cached_network_image](https://pub.dev/packages/cached_network_image#-readme-tab-) , this is due to "Breaking change with ImageProvider.load in Flutter 1.10"

upgrading to `2.0.0-rc.` solves the problem.

**Comment by renefloor** [comment]
please use version 2.0.0
