### ISSUE TITLE
Channel stable, v1.12.13+hotfix.5    Incompatible

### ISSUE THREAD

**Issue by wang-zeqi** [Baseflow/flutter_cached_network_image#308]
cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);

**Comment by arnold-parge** [comment]
Looks like it is resolved in `2.0.0-rc`.
https://pub.dev/packages/cached_network_image/versions/2.0.0-rc#-installing-tab-

**Comment by MichaelMarner** [comment]
Duplicate of #270
