### ISSUE TITLE
Add MacOS Support

### ISSUE THREAD

**Issue by EliasDeuss** [Baseflow/flutter_cached_network_image#316]
It would be nice to get MacOS support

**Comment by renefloor** [comment]
![image](https://user-images.githubusercontent.com/15101411/79200164-52296600-7e36-11ea-9792-3a9323ef15ee.png)

It's working :)

**Comment by mateusfccp** [comment]
Here I get an error on `path_provider` when trying to `getTemporaryDirectory` on macOS.
