### ISSUE TITLE
The 'imageBuilder' of the CachedNetworkImage is called and action multiple.

### ISSUE THREAD

**Issue by eugenejeonme** [Baseflow/flutter_cached_network_image#319]
Is it intended?
If not, let me know how to solve it. 
Does anyone know how to solve this?

![image](https://user-images.githubusercontent.com/36671804/71883353-9fcc6d80-3179-11ea-9146-f7ff11a98f37.png)

**Comment by renefloor** [comment]
Just like the build function of a widget this can be called multiple times yes, no harm done. Never do logic in build functions that only should execute once.
