### ISSUE TITLE
How can i catch event when image loaded? plz help...

### ISSUE THREAD

**Issue by thanhnguyen1121** [Baseflow/flutter_cached_network_image#322]
Did you update to the latest Flutter SDK and getting errors about `CachedNetworkImageProvider.load` or `ScaledFileImage.load`, please upgrade to 2.0.0-rc: https://pub.dev/packages/cached_network_image/versions/2.0.0-rc

**Comment by renefloor** [comment]
If you use ImageBuilder you at least know when the image is build.
