### ISSUE TITLE
Version 2.0.0 crash App on startup in new flutter sdk version

### ISSUE THREAD

**Issue by ErmindoLopes** [Baseflow/flutter_cached_network_image#327]
solved.... error only im flutter master channel - stable is ok

Error 
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
√ Built build\app\outputs\apk\debug\app-debug.apk.
W/FlutterEnginePluginRegistry( 1414): Attempted to register plugin (io.flutter.plugins.pathprovider.PathProviderPlugin@4f52ab8) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@1b77091).
W/FlutterEnginePluginRegistry( 1414): Attempted to register plugin (io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin@8d4bf6) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@1b77091).
D/EGL_emulation( 1414): eglMakeCurrent: 0xebe2f4e0: ver 3 0 (tinfo 0xebe5c200)
D/eglCodecCommon( 1414): setVertexArrayObject: set vao to 0 (0) 1 0

flutter doctor --verbose
[√] Flutter (Channel master, v1.14.5-pre.28, on Microsoft Windows [versÃ£o 10.0.18363.592], locale pt-BR)
    • Flutter version 1.14.5-pre.28 at C:\development\flutter
    • Framework revision 93a5b7d419 (7 hours ago), 2020-01-25 01:23:01 -0800
    • Engine revision 4218f8026f
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\development\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\development\Android\Sdk
    • Java binary at: C:\development\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\development\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\ermin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by luan-silva** [comment]
I tried 1.12.13hotfix7 that it's in stable now and only gives me white screen when app start

**Comment by renefloor** [comment]
@ErmindoLopes as it is solved I'll close the issue
@luan-silva if you still have a problem could you submit a well written bug report so I can investigate it?

**Comment by AiYouWei** [comment]
Process: team.opay.pay.alpha, PID: 7618
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/util/concurrent/ThreadFactoryBuilder;
        at io.flutter.plugins.pathprovider.PathProviderPlugin.<init>(PathProviderPlugin.java:35)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:19)


cached_network_image: ^2.3.3

nothing wrong in module, but as an aar for my project, it appears
