### ISSUE TITLE
Flutter: ImageCache from Network make application crash

### ISSUE THREAD

**Issue by viktor-morin** [Baseflow/flutter_cached_network_image#332]
See my issue here:

[https://stackoverflow.com/questions/60122111/flutter-imagecache-from-network-make-application-crash](https://stackoverflow.com/questions/60122111/flutter-imagecache-from-network-make-application-crash)

**Comment by renefloor** [comment]
I don't really know what is happening here. Can you create a minimal example to reproduce this issue?

**Comment by viktor-morin** [comment]
Problem is solved, see stackoverflow issue.

**Comment by renefloor** [comment]
@viktor-morin so was the solution in the slivergrid with addAutomaticKeepAlives: false
or in making sure that:
All images exist (no 404)
All images is max 500x500 (before some where 4000x4000)
All images is now compressed

**Comment by viktor-morin** [comment]
@renefloor 
I did both, but my feeling is that following changes had most impact:

> All images exist (no 404)
> All images is max 500x500 (before some where 4000x4000)
> All images is now compressed

**Comment by renefloor** [comment]
Thanks, probably a combination of #273 and #260 than
