### ISSUE TITLE
Crash app when have list of image

### ISSUE THREAD

**Issue by RenanDelfanti** [Baseflow/flutter_cached_network_image#339]
The plugin crashes the app when there is an list with images between 2 / 10mb.

**Comment by renefloor** [comment]
What's the exact error? Do you think it's a memory issue?

**Comment by RenanDelfanti** [comment]
@renefloor yes, it's memory leak!
Don't have output error, simple app crash in this situation

**Comment by renefloor** [comment]
I guess it's a duplicate of #260 than. I'm not sure whether this is a bug of the library of of Flutter though. If you could help me with finding out what is going wrong that would be great. Closing this issue now as duplicate.
