### ISSUE TITLE
Enable/Disable caching

### ISSUE THREAD

**Issue by TarekMedhat** [Baseflow/flutter_cached_network_image#345]
## 🚀 Feature Requests

Sometimes I need to get the benefit of cachednetworkimage such as placeholder and error widget without caching the images on disk.
So would be great if there is a bool that widget takes as a parameter that enables/disables caching

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
duplicate of #22
