### ISSUE TITLE
Can't Load Img with Special symbol

### ISSUE THREAD

**Issue by lmanliang** [Baseflow/flutter_cached_network_image#347]
使用 ads-e-01.png 無法載入
使用 adse01.png 正常載入

應為特殊符合因素

**Comment by renefloor** [comment]
Can you give me an url that should work but doesn't?

**Comment by lmanliang** [comment]
you can try

false

CachedNetworkImage(
  imageUrl: 'https://app.wydiet.com/ads/ads-e-01.png',
  placeholder: (context, url) => CircularProgressIndicator(),
  errorWidget: (context, url, error) => Icon(Icons.error),
),

TRUE

CachedNetworkImage(
  imageUrl: 'https://app.wydiet.com/ads/adse01.png',
  placeholder: (context, url) => CircularProgressIndicator(),
  errorWidget: (context, url, error) => Icon(Icons.error),
),

  TRUE

CachedNetworkImage(
  imageUrl: 'https://app.wydiet.com/ads/ads_e_01.png',
  placeholder: (context, url) => CircularProgressIndicator(),
  errorWidget: (context, url, error) => Icon(Icons.error),
),


Rene Floor <notifications@github.com> 於 2020年3月9日 週一 下午2:53寫道：

**Comment by renefloor** [comment]
When I try these 3 on my phone they all 3 load normally.

Which version of the library do you use and which OS?

**Comment by lmanliang** [comment]
C:\Users\lman\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel master, v1.15.19-pre.17, on Microsoft Windows [Version
10.0.18363.657], locale zh-TW)
    • Flutter version 1.15.19-pre.17 at C:\Users\lman\flutter
    • Framework revision 5b0a79dbdb (8 hours ago), 2020-03-08 21:16:01 -0400
    • Engine revision 981c03631e
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[√] Android toolchain - develop for Android devices (Android SDK version
29.0.2)
    • Android SDK at C:\Users\lman\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native
profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10
(API 29) (emulator)

• No issues found!
Process finished with exit code 0


Running "flutter pub get" in wydiet...                              0.6s
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Debug service listening on ws://127.0.0.1:59162/tsAhVVkYxHU=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation(27635): eglMakeCurrent: 0xe241a4e0: ver 3 0 (tinfo
0xe240f820)
D/eglCodecCommon(27635): setVertexArrayObject: set vao to 0 (0) 1 0
I/m.brainc.wydie(27635): Background young concurrent copying GC freed
18277(2027KB) AllocSpace objects, 7(140KB) LOS objects, 83% free,
1231KB/7375KB, paused 13.475ms total 34.428ms
I/flutter (27635): null
I/flutter (27635): abc
I/flutter (27635): news is null
I/flutter (27635): news news news
I/flutter (27635): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE
╞════════════════════════════════════════════════════
I/flutter (27635): The following _Exception was thrown resolving an image
codec:
I/flutter (27635): Exception: Could not instantiate image codec.
I/flutter (27635):
I/flutter (27635): When the exception was thrown, this was the stack:
I/flutter (27635): #0      _futurize (dart:ui/painting.dart:4419:5)
I/flutter (27635): #1      instantiateImageCodec
(dart:ui/painting.dart:1722:10)
I/flutter (27635): #2      PaintingBinding.instantiateImageCodec
(package:flutter/src/painting/binding.dart:88:12)
I/flutter (27635): #3      FileImage._loadAsync
(package:flutter/src/painting/image_provider.dart:847:24)
I/flutter (27635): <asynchronous suspension>
I/flutter (27635): #4      FileImage.load
(package:flutter/src/painting/image_provider.dart:828:14)
I/flutter (27635): #5      ImageProvider.resolveStreamForKey.<anonymous
closure> (package:flutter/src/painting/image_provider.dart:491:13)
I/flutter (27635): #6      ImageCache.putIfAbsent
(package:flutter/src/painting/image_cache.dart:359:22)
I/flutter (27635): #7      ImageProvider.resolveStreamForKey
(package:flutter/src/painting/image_provider.dart:489:80)
I/flutter (27635): #8      ScrollAwareImageProvider.resolveStreamForKey
(package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
I/flutter (27635): #9      ImageProvider.resolve.<anonymous closure>
(package:flutter/src/painting/image_provider.dart:330:9)
I/flutter (27635): #10
ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous
closure> (package:flutter/src/painting/image_provider.dart:450:26)
I/flutter (27635): #11     SynchronousFuture.then
(package:flutter/src/foundation/synchronous_future.dart:41:29)
I/flutter (27635): #12
ImageProvider._createErrorHandlerAndKey.<anonymous closure>
(package:flutter/src/painting/image_provider.dart:447:11)
I/flutter (27635): #16     ImageProvider._createErrorHandlerAndKey
(package:flutter/src/painting/image_provider.dart:439:16)
I/flutter (27635): #17     ImageProvider.resolve
(package:flutter/src/painting/image_provider.dart:327:5)
I/flutter (27635): #18     _ImageState._resolveImage
(package:flutter/src/widgets/image.dart:1047:16)
I/flutter (27635): #19     _ImageState.didChangeDependencies
(package:flutter/src/widgets/image.dart:1000:5)
I/flutter (27635): #20     StatefulElement._firstBuild
(package:flutter/src/widgets/framework.dart:4661:12)
I/flutter (27635): #21     ComponentElement.mount
(package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (27635): ...     Normal element mounting (4 frames)
I/flutter (27635): #25     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (27635): #26     Element.updateChild
(package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (27635): #27     RenderObjectElement.updateChildren
(package:flutter/src/widgets/framework.dart:5580:32)
I/flutter (27635): #28     MultiChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:5957:17)
I/flutter (27635): #29     Element.updateChild
(package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (27635): #30     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (27635): #31     StatefulElement.performRebuild
(package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (27635): #32     Element.rebuild
(package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (27635): #33     BuildOwner.buildScope
(package:flutter/src/widgets/framework.dart:2627:33)
I/flutter (27635): #34     WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:883:20)
I/flutter (27635): #35     RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:283:5)
I/flutter (27635): #36     SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1108:15)
I/flutter (27635): #37     SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1047:9)
I/flutter (27635): #38     SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:963:5)
I/flutter (27635): #42     _invoke (dart:ui/hooks.dart:261:10)
I/flutter (27635): #43     _drawFrame (dart:ui/hooks.dart:219:3)
I/flutter (27635): (elided 6 frames from dart:async)
I/flutter (27635):
I/flutter (27635): Path:
I/flutter (27635):
/data/user/0/com.brainc.wydiet/cache/libCachedImageData/49816ba0-615e-11ea-db22-c90eb641bd7d.html;
I/flutter (27635): charset=UTF-8
I/flutter (27635):
════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter (27635): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled
Exception: FileSystemException: Cannot delete file, path =
'/data/user/0/com.brainc.wydiet/cache/cache_store/0ZQs6YlfbcM' (OS Error:
No such file or directory, errno = 2)
E/flutter (27635): #0      _File._delete.<anonymous closure>
(dart:io/file_impl.dart:293:9)
E/flutter (27635): #1      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (27635): #2      _CustomZone.runUnary
(dart:async/zone.dart:1031:19)
E/flutter (27635): #3      _FutureListener.handleValue
(dart:async/future_impl.dart:140:18)
E/flutter (27635): #4      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:682:45)
E/flutter (27635): #5      Future._propagateToListeners
(dart:async/future_impl.dart:711:32)
E/flutter (27635): #6      Future._completeWithValue
(dart:async/future_impl.dart:526:5)
E/flutter (27635): #7      Future._asyncComplete.<anonymous closure>
(dart:async/future_impl.dart:556:7)
E/flutter (27635): #8      _rootRun (dart:async/zone.dart:1126:13)
E/flutter (27635): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (27635): #10     _CustomZone.runGuarded
(dart:async/zone.dart:925:7)
E/flutter (27635): #11     _CustomZone.bindCallbackGuarded.<anonymous
closure> (dart:async/zone.dart:965:23)
E/flutter (27635): #12     _microtaskLoop
(dart:async/schedule_microtask.dart:43:21)
E/flutter (27635): #13     _startMicrotaskLoop
(dart:async/schedule_microtask.dart:52:5)
E/flutter (27635):
E/flutter (27635): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled
Exception: FileSystemException: Cannot delete file, path =
'/data/user/0/com.brainc.wydiet/cache/cache_store/6N806YlfeE7' (OS Error:
No such file or directory, errno = 2)
E/flutter (27635): #0      _File._delete.<anonymous closure>
(dart:io/file_impl.dart:293:9)
E/flutter (27635): #1      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (27635): #2      _CustomZone.runUnary
(dart:async/zone.dart:1031:19)
E/flutter (27635): #3      _FutureListener.handleValue
(dart:async/future_impl.dart:140:18)
E/flutter (27635): #4      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:682:45)
E/flutter (27635): #5      Future._propagateToListeners
(dart:async/future_impl.dart:711:32)
E/flutter (27635): #6      Future._completeWithValue
(dart:async/future_impl.dart:526:5)
E/flutter (27635): #7      Future._asyncComplete.<anonymous closure>
(dart:async/future_impl.dart:556:7)
E/flutter (27635): #8      _rootRun (dart:async/zone.dart:1126:13)
E/flutter (27635): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (27635): #10     _CustomZone.runGuarded
(dart:async/zone.dart:925:7)
E/flutter (27635): #11     _CustomZone.bindCallbackGuarded.<anonymous
closure> (dart:async/zone.dart:965:23)
E/flutter (27635): #12     _microtaskLoop
(dart:async/schedule_microtask.dart:43:21)
E/flutter (27635): #13     _startMicrotaskLoop
(dart:async/schedule_microtask.dart:52:5)
E/flutter (27635):

Rene Floor <notifications@github.com> 於 2020年3月9日 週一 下午5:28寫道：

**Comment by renefloor** [comment]
> /data/user/0/com.brainc.wydiet/cache/libCachedImageData/49816ba0-615e-11ea-db22-c90eb641bd7d.html;

This looks like the image was cached as html page, not sure if the headers were wrong or that it is from a 404 page or something like that. Do you also get these errors on a clean install?

**Comment by lmanliang** [comment]
You are right.
I change the filename to ads-e-02.png
it can display image.

Rene Floor <notifications@github.com> 於 2020年3月9日 週一 下午6:54寫道：
