### ISSUE TITLE
CacheManager: Failed to download file from URL with error: Invalid header field name

### ISSUE THREAD

**Issue by seb3n** [Baseflow/flutter_cached_network_image#348]
## 🐛 Bug Report

I/flutter ( 8292): CacheManager: Failed to download file from https://firebasestorage.googleapis.com/v0/b/test-223a4.appspot.com/o/media%2Fimages%2FgOmWRPRdVlenCyWmDMY8oj8sPGg2%2F2020-03-08%2022%3A34%3A03.003784?alt=media&token=2f71d996-213e-4eea-8f2d-7e9a57d20abf with error:
I/flutter ( 8292): Invalid header field name

This error only occurs if the image metadata is uploaded to Firebase/cloudstorage.

here is a link to an image without metadata: https://firebasestorage.googleapis.com/v0/b/test-223a4.appspot.com/o/media%2Fimages%2FgOmWRPRdVlenCyWmDMY8oj8sPGg2%2F2020-03-08%2022%3A53%3A10.724049?alt=media&token=dd40587c-c48a-4945-9959-eedda9be0c8e

Any help with this would be awesome!

**Version:** ^2.0.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by mohanasundaramn** [comment]
i too have same issue

**Comment by renefloor** [comment]
This is something wrong, but I don't know how and why. I tried the following and it gave the same error:

```
import 'package:http/http.dart' as http;


    http.get('https://firebasestorage.googleapis.com/v0/b/test-223a4.appspot.com/o/media%2Fimages%2FgOmWRPRdVlenCyWmDMY8oj8sPGg2%2F2020-03-08%2022%3A34%3A03.003784?alt=media&token=2f71d996-213e-4eea-8f2d-7e9a57d20abf')
      .then((_) => print('success'))
      .catchError(print);
```
Using [Dio](https://pub.dev/packages/dio) didn't make a change. However, when using postman I could normally fetch the image. 

I think you need to submit an issue at firebase and/or the flutter team.
