### ISSUE TITLE
如何去掉蓝色底？？

### ISSUE THREAD

**Issue by opennflower** [Baseflow/flutter_cached_network_image#350]
进入一个页面后，返回页面发现有个蓝色底，这个能去掉吗

**Comment by mvanbeusekom** [comment]
Please post your issues in English. Everything around the plugin is English and English is the only language we (can) support.

**Comment by opennflower** [comment]
When you go to a page, you go back to the page and you find a blue bottom. Can you get rid of that

**Comment by renefloor** [comment]
@opennflower what do you mean? Can you give me a code example and maybe a video of what is going wrong?

**Comment by opennflower** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        
            I'm sorry I made a mistake. It's my other component
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                opennflower
                            
                    
                        
                            
                                    opennflower@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年3月20日 17:57，Rene Floor<notifications@github.com> 写道： 



@opennflower what do you mean? Can you give me a code example and maybe a video of what is going wrong?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
