### ISSUE TITLE
Add log settings to show/hide download errors

### ISSUE THREAD

**Issue by Carl0395** [Baseflow/flutter_cached_network_image#351]
how can ignore this message in my debug console?

![image](https://user-images.githubusercontent.com/17973173/76685186-c70f4300-65df-11ea-98a4-444612e11539.png)

Some images of the server do not load, but it is an external problem to the app and this message is a bit annoying in the console

**Comment by renefloor** [comment]
Currently there is no way to disable the logging. I guess it is a good idea to include log settings.

**Comment by Carl0395** [comment]
I't seems to me a great idea, I will be pending the update.

Thanks

**Comment by qwertyway** [comment]
One more supporter for the ability to ignore logs. Very annoying

Thanks

**Comment by kirill-21** [comment]
Any progress?

**Comment by stlr00** [comment]
Need too

**Comment by dodatw** [comment]
We need it!
