### ISSUE TITLE
valid image url not downloaded

### ISSUE THREAD

**Issue by MangeshKadam** [Baseflow/flutter_cached_network_image#355]
## 🐛 Bug Report

my valid image url http://myipaddress/ewfile14.php?fn=T4bcnpTfBlMaihZzrMHypadHNXlXQdtQfZGj3mZ4Oq-1U7NjGQILIhwXWoomaDgV-UYhkQ..&download=false&called_from=api 
When I am using default NetworkImage, image is downloaded. But its not working with CachedNetworkImageProvider

### Expected behavior
image should be downloaded and cached
### Configuration

**Version:** 1.x

**Platform:** 

- [ ] :robot: Android

**Comment by renefloor** [comment]
Do you see any errors in the logs? I would love to test it, but I can't reproduce it if I don't have the ip address or some working code that I can host myself.

**Comment by AbhishekDoshi26** [comment]
> ## 🐛 Bug Report
> my valid image url http://myipaddress/ewfile14.php?fn=T4bcnpTfBlMaihZzrMHypadHNXlXQdtQfZGj3mZ4Oq-1U7NjGQILIhwXWoomaDgV-UYhkQ..&download=false&called_from=api
> When I am using default NetworkImage, image is downloaded. But its not working with CachedNetworkImageProvider
> 
> ### Expected behavior
> image should be downloaded and cached
> 
> ### Reproduction steps
> ### Configuration
> **Version:** 1.x
> 
> **Platform:**
> 
> * [ ]  🤖 Android

Flutter Image.network() will check whether the link ends with .jpg or .png or .jpeg! If it doesn't, Image.network() won't load the image. Try to use the links that contains directly images and not an indirect link.

**Comment by renefloor** [comment]
Let's close the issue due to no response.
