### ISSUE TITLE
Possibility to know when the image has loaded

### ISSUE THREAD

**Issue by arthurdenner** [Baseflow/flutter_cached_network_image#356]
## 💬 Questions and Help

Hi! 👋 Is it possible to know when the image has loaded, e.g. through a callback? I've looked at the examples and the source code, but couldn't find a way to achieve this.

I've checked other issues too and the closest to this would be #233, I think.

If it's not possible, would you be open for the addition of such feature? I'd gladly implement it if one it's available to help me out if needed.

**Comment by renefloor** [comment]
The feedback on loading progress I'm working on. I already did a lot of the pre-work in the cache manager.
If you just want some feedback that it is loaded you can do something like this:
```CachedNetworkImage(
  imageUrl: "http://via.placeholder.com/200x150",
  imageBuilder: (context, imageProvider) => Image(
            image: imageProvider,
          ),
  placeholder: (context, url) => CircularProgressIndicator(),
  errorWidget: (context, url, error) => Icon(Icons.error),
),```

The imageBuilder will be called after the image is loaded, but as any builder function it can be called multiple times, so keep that in mind while using it.

**Comment by arthurdenner** [comment]
Hi @renefloor, thanks for the reply.

I tried this approach yesterday before opening the issue, but as you commented, it can be called multiple times, so it's tricky. The approach is not great.

But it's good that you are working on a proper solution. Should we close this or leave it open to track progress of what you're working on?

**Comment by renefloor** [comment]
If progress will be good enough for you than I'll close this issue in favour of #233
