### ISSUE TITLE
Flutter to App Native the image load faild

### ISSUE THREAD

**Issue by yaofuyu** [Baseflow/flutter_cached_network_image#357]
## 🐛 Bug Report

Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      invokeMethod (package:sqflite/src/sqflite_impl.dart:20:13)
#2      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:34:7)
#3      SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:25:35)
#4      wrapDatabaseException (package:sqflite/src/exception_impl.dart:8:32)
#5      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:30:7)
#6      SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite_common/src/factory_mixin.dart:25:7)
#7      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite_common/src/factory_mixin.dart:143:26)
#8      getDatabasesPath (package:sqflite/sqflite.dart:168:54)
#9      CacheStore._getObjectProvider (package:flutter_cache_manager/src/cache_store.dart:39:31)

### Configuration

**Version:** 2.0.0

**Platform:** 
- [ ] :iphone: iOS 13.2
- [ ] :robot: Android

**Comment by renefloor** [comment]
As your error already shows this is an issue with `package:sqflite`, so not for here. Though it is already fixed in sqflite 1.2.1, so just a `lutter pub upgrade` should be fine for it to work.
