### ISSUE TITLE
app flash block when load image by flutter_cached_network_image

### ISSUE THREAD

**Issue by RobinYang11** [Baseflow/flutter_cached_network_image#358]
when i load image  by using  flutter_cached_network_image  , app always flash block.

**Comment by renefloor** [comment]
What do you mean with flash block?

**Comment by LYFsy** [comment]
> when i load image by using flutter_cached_network_image , app always flash block.

I have same problem，how do you fixed？

**Comment by renefloor** [comment]
@LYFsy same question for you, what do you exactly mean?

**Comment by renefloor** [comment]
I found wrong behaviour which maybe fixes the flicker. Is it fixed in version 2.1.0?

**Comment by RobinYang11** [comment]
> What do you mean with flash block?

it mean  app   force quit  with a behavior like flush . 
when i load a image which size bigger than 15m or more .
it may not the problem with flutter_cached_network_image.

**Comment by renefloor** [comment]
Ah thanks that is useful information. That's sounds like an out of memory crash.
