### ISSUE TITLE
Please include blurhash support

### ISSUE THREAD

**Issue by MoacirSchmidt** [Baseflow/flutter_cached_network_image#361]
## 🚀 Feature Requests

Please include blurhash support as described in
https://pub.dev/packages/blurhash_dart

See beautiful behavior:
https://blurha.sh/

**Comment by renefloor** [comment]
It is already possible to use blurhash. I just updated the example to include it. However, I will keep this issue open as I'm considering deeper integration.

```
  Widget _blurHashImage(){
    return SizedBox(
      width: double.infinity,
      child: CachedNetworkImage(
        placeholder: (context, url) {
          var blurHash = 'LEHV6nWB2yk8pyo0adR*.7kCMdnj';
          var pixels = decodeBlurHash(blurHash, 35, 20);
          var bitmap = Bitmap.fromHeadless(35, 20, pixels);
          return Image.memory(bitmap.buildHeaded(), fit: BoxFit.cover,);
        },
        imageUrl: 'https://blurha.sh/assets/images/img1.jpg',
        fit: BoxFit.cover,
      ),
    );
  }
```

**Comment by renefloor** [comment]
@MoacirSchmidt Do you know the difference between [blurhash_dart](https://pub.dev/packages/blurhash_dart) and [flutter_blurhash](https://pub.dev/packages/flutter_blurhash)? 

I think flutter_blurhash is a bit easier to use as you don't need to do the bitmap handling with the decode, fromHeadless and buildHeaded. You can just do `BlurHash(hash: "L5H2EC=PM+yV0g-mq.wG9c010J}I")`

**Comment by MoacirSchmidt** [comment]
@renefloor No. I haven't used any. Everything I know is [blurhash_dart](https://pub.dev/packages/blurhash_dart) is "officially" referenced at https://github.com/woltapp/blurhash and it is not dependent of flutter and image packages

**Comment by renefloor** [comment]
Ah you're right.

**Comment by renefloor** [comment]
I made an implementation for OctoImage which can easily be combined with the CachedNetworkImageProvider
