### ISSUE TITLE
Opportunity to reduce memory footprint by 100MiB

### ISSUE THREAD

**Issue by annorax** [Baseflow/flutter_cached_network_image#364]
## 🏗 Enhancement Proposal

Either don't use ImageProvider or find a way to override it so that it doesn't use the default global ImageCache to the tune of 100MiB as a pretty much useless additional caching tier.

### Pitch

By using ImageProvider in each of your 2 classes (CachedNetworkImageProvider extends it, CachedNetworkImage use the FileImage image provider under the hood), you are using the global ImageCache as a second-tier RAM-based cache, for caching the exploded (decoded) images. This is pretty much useless, since an uncompressed high-res image will easily take up much of the ImageCache, causing it to be evicted way too often to be of any use. This is why I came to use this library in the first place, after realizing that using NetworkImage is far from equivalent in terms of how caching is handled.

- If it is prohibitively difficult to override ImageProvide to not use the global ImageCache, another way to address this would be to add a comment in the docs saying that ImageCache can be easily disabled by adding the folliwing 2 lines (or either of them) to the initState() method of the top level widget (it has to be stateful, of course):
```dart
PaintingBinding.instance.imageCache.maximumSize = 0;
PaintingBinding.instance.imageCache.maximumSizeBytes = 0;
```

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
I'm not sure if I understand you correctly.
When you want to show an image, you always need to have the full exploded image in your memory. When you switch quickly between pages you don't want to throw the full image away directly when you leave the page, as you will have to process the image again. To my knowledge the ImageProvider logic is quite efficient in handling images and we should not try to replace that. Do you have any example of an app or library that shows images without using an ImageProvider? If you have problems with the ImageProvider maybe a ticket at the main Flutter repo is better.
