### ISSUE TITLE
CachedNetworkImageProvider does not support progress listener

### ISSUE THREAD

**Issue by hamberluo** [Baseflow/flutter_cached_network_image#365]
NetworkImage is ok.
CachedNetworkImageProvider for ImageChuckEvent is always null.

**Comment by renefloor** [comment]
True, it doesn't support that (yet)

**Comment by hamberluo** [comment]
when will the milestone come?

**Comment by renefloor** [comment]
I just happen to be working on it, but I don't give ETAs.

**Comment by renefloor** [comment]
Released in 2.2.0
