### ISSUE TITLE
Add Progress indicator widget while downloading image.

### ISSUE THREAD

**Issue by DhavalRKansara** [Baseflow/flutter_cached_network_image#366]
## 🚀 Feature Requests

Add one Progress indicator type widget while downloading Image. So User can identify that he/she needs to wait until the library downloading the image.

**Comment by renefloor** [comment]
What do you mean? We just added a feature last week to show a progressIndicator. The example is in the readme:
```
CachedNetworkImage(
       imageUrl: "http://via.placeholder.com/350x150",
       progressIndicatorBuilder: (context, url, downloadProgress) => 
               CircularProgressIndicator(value: downloadProgress.progress),
       errorWidget: (context, url, error) => Icon(Icons.error),
    ),
```

**Comment by DhavalRKansara** [comment]
Ohh Sorry, I was using the library at `version 2.0.0`.

**Comment by renefloor** [comment]
No problem
