### ISSUE TITLE
progressIndicatorBuilder not working

### ISSUE THREAD

**Issue by bhanuka96** [Baseflow/flutter_cached_network_image#367]
this is my version `cached_network_image: ^2.1.0+1`.
ProgressIndicator not working. 

```
CachedNetworkImage(
              progressIndicatorBuilder: (context, url, downloadProgress) {
                print(url + '  '+ '${downloadProgress.downloaded}' + ' '+ '${downloadProgress.progress}' + ' '+ '${downloadProgress.totalSize}');
                return CircularProgressIndicator(value: downloadProgress.progress);
              },
              errorWidget: (context, url, error) =>
                  Container(),
              imageUrl: widget.releaseConfig.imageUrl,
            ),
```

print result 

` https:///animationGif.gif?alt=media&token=927eb5d7-b10b-42b5-ba9a-5203461bed42 url is  0 null null`

**REASON**

I added `progressIndicatorBuilder` on alert Dialog. I have a `GridView` on the homePage with images. I used cachedNetworkImage on the GridView but not used` progressIndicatorBuilder`. One image URL is failed in GridView. I got 404 error on the console. I replace the working image URL to that item product. Now, `progressIndicatorBuilder` is working.

**Comment by renefloor** [comment]
So you are saying it works perfectly fine?
When the content size is not known downloadProgress.totalSize and downloadProgress.progress are both null. When you get a 404 it makes sense the size is not known. You say yourself that when you do have content the progressIndicator works.
