### ISSUE TITLE
Precache Image data

### ISSUE THREAD

**Issue by droidluv** [Baseflow/flutter_cached_network_image#369]
## 🚀 Feature Requests

Precache data from image urls which may or maynot be used soon by the app

### Contextualize the feature
The library is designed to cache images for easy retrieval the next time, but what if we want to precache images based on network availability and priority, so when the user visits an area where the data is used, they have the downloaded data ready for them.

### Describe the feature
Precache is a feature which allows the apps to prepare network images well in advance before its needed, simulating a faster experience and lessening wait times for the user. 

### Platforms affected (mark all that apply)
- [X ] :iphone: iOS
- [ X] :robot: Android

**Comment by dariocavada** [comment]
This would be very useful.

**Comment by gilescm** [comment]
The standard `precacheImage` function works with the `CachedNetworkImageProvider` provided by this package. I've tested and the below is working for me: 

Call the below function during apps/views preparation phase. (In my case this is in a viewmodel after retrieving results from an API call and we're looping through each one.)
```flutter
precacheImage(
    CachedNetworkImageProvider(image.url),
    context,
);
```
I then use `Image(image: CachedNetworkImageProvider(file.thumbnail));` later on in the build method of a widget created in a `ListView.builder`.

I haven't exhaustively tested this so I could be incorrectly but this looks like it achieves what is being asked. Apologies if I'm wrong.
