### ISSUE TITLE
Image memory Cached

### ISSUE THREAD

**Issue by dekadevelop** [Baseflow/flutter_cached_network_image#375]
## 🏗 Enhancement Proposal

Hi, 
I used **flutter_advanced_networkimage**, but it didn't provide a nice FirebaseStorage File cache functionality as this one.
But it was a lot nicer navigating through pages (also via Heroes widgets), because it provides a memory cache of the downloaded image (I guess).
With **flutter_cached_network_image** the widgets has always to read from files, and it's slow, showing white/loading background all the time, fetching the image always, making Heroes widget not working.
A perfect widget will be a fusion of both flutter_advanced_networkimage and flutter_cached_network_image

Would it be possibile to have also the benefits of memory caching?

**Comment by renefloor** [comment]
The ImageProvider logic of Flutter itself already contains memory caching of decoded images. I'm not sure what else you expect. I'm working on improving the effects for the Hero widgets though.

**Comment by dekadevelop** [comment]
Ah ok, perfect, 
just when I used the _networkimage_ package, it was loading the image only first time, then the image was always loaded without a blink in every case. But with _cached_, when the widget is initialised, first build, I see the black white space under, for maybe more or less 0.5 sec, so it seems not fluid

**Comment by dekadevelop** [comment]
Sorry I made a mistake, I was using cache_image instead of cache_image_network...
this can be closed,
it would be nice to have to Firebase Storage support (I saw there is a topic opened for that)
