### ISSUE TITLE
The application crashes continuously when I use more than 10 images to load at the same time

### ISSUE THREAD

**Issue by AnhTu6610** [Baseflow/flutter_cached_network_image#376]
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
Could you be a bit more specific? Is it a memory issue?

**Comment by PrismaSoftGC** [comment]
Same problem here.

Error log:  increase max job count 40 flutter

**Comment by renefloor** [comment]
@PrismaSoftGC and @AnhTu6610 can you try with version 2.3.0-beta? In that version you can also try to set the memCacheHeight and width to limit the memory usage.
