### ISSUE TITLE
Intermittent problem to download image from valid URL

### ISSUE THREAD

**Issue by gbmiranda** [Baseflow/flutter_cached_network_image#378]
90% of requests work, but some have this error. In this case it happened in sequence when I tried to open a gridview with images.

Logs:

flutter: CacheManager: Failed to download file from https://s3-sa-east-1.amazonaws.com/araujo-app/small_4005900669261_1571852954464.jpg with error:
Connection closed before full header was received

flutter: CacheManager: Failed to download file from https://s3-sa-east-1.amazonaws.com/araujo-app/small_7898919412280_1530715853248.jpg with error:
Connection closed before full header was received

flutter: CacheManager: Failed to download file from https://s3-sa-east-1.amazonaws.com/araujo-app/small_4005900004956_1558038582313.jpg with error:
Connection closed before full header was received

flutter: CacheManager: Failed to download file from https://s3-sa-east-1.amazonaws.com/araujo-app/small_7898919412273_1530218108359.jpg with error:
Connection closed before full header was received

flutter: CacheManager: Failed to download file from https://s3-sa-east-1.amazonaws.com/araujo-app/small_4005900669285_1571852676375.jpg with error:
Connection closed before full header was received

flutter: CacheManager: Failed to download file from https://s3-sa-east-1.amazonaws.com/araujo-app/small_7896094912762_1527183601578.jpg with error:
Connection closed before full header was received

**Comment by gbmiranda** [comment]
Someone?

**Comment by renefloor** [comment]
Maybe it's better to ask in stackoverflow, because I don't think it is a problem of this package.

**Comment by renefloor** [comment]
Closing this in favor of #443
