### ISSUE TITLE
CachedNetworkImage does not work with latest  1.19.0-1.0.pre • channel dev 

### ISSUE THREAD

**Issue by huynhducloi00** [Baseflow/flutter_cached_network_image#387]
only CachedNetworkImageProvider works. please check the https://pub.dev/packages/cached_network_image#-example-tab-

**Comment by renefloor** [comment]
What's the error?

**Comment by ricardochen** [comment]
I'm getting these errors

I/erentrega.stor(24055): The ClassLoaderContext is a special shared library.
V/NativeCrypto(24055): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
W/erentrega.stor(24055): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (greylist, reflection, allowed)
D/NetworkSecurityConfig(24055): No Network Security Config specified, using platform default
I/ProviderInstaller(24055): Installed default security provider GmsCore_OpenSSL
W/erentrega.stor(24055): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection, allowed)
W/erentrega.stor(24055): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, linking, allowed)
W/erentrega.stor(24055): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, linking, allowed)
W/erentrega.stor(24055): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (greylist, JNI, allowed)
W/erentrega.stor(24055): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (greylist, reflection, allowed)
W/erentrega.stor(24055): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (greylist,core-platform-api, linking, allowed)
W/erentrega.stor(24055): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)

**Comment by ricardochen** [comment]
iOS works fine, this happens in Android

**Comment by renefloor** [comment]
Maybe you can try version 2.3.0-beta, because that uses the CachedNetworkImageProvider instead of a FileImage. The widget should work about the same.
