### ISSUE TITLE
No named parameter with the name 'animation'.

### ISSUE THREAD

**Issue by EngAddow** [Baseflow/flutter_cached_network_image#388]
When i was running my project I got this problem :extended_image_slide_page_route.dart:331:9: Error: No named parameter with the name 'animation'. Any solution?

Launching lib\main.dart on Android SDK built for x86 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
../../../../../Programs/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.5.3/lib/src/gesture/extended_image_slide_page_route.dart:331:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
../../../../../Programs/flutter/packages/flutter/lib/src/cupertino/route.dart:436:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Compiler message:
../../../../../Programs/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.5.3/lib/src/gesture/extended_image_slide_page_route.dart:331:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
../../../../../Programs/flutter/packages/flutter/lib/src/cupertino/route.dart:436:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'E:\from F\Programs\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\from F\Programs\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 12s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by renefloor** [comment]
Looks like you have this error because you use an outdated version of extended_image. You use 0.5.3, while 0.8.0 is already available. And I've no idea how you ended up asking help on a github page of CachedNetworkImage while the error only shows extended_image and cupertino.

**Comment by EngAddow** [comment]
I am sorry first error was about CachedNEtworkImage but than I solved and I was thinking it is the same error.
