### ISSUE TITLE
Retry option 

### ISSUE THREAD

**Issue by NicolasCELLA** [Baseflow/flutter_cached_network_image#392]
Hello, it's possible to have an option "retry" like "flutter_advanced_networkimage" when this image doesn't load she retry ?

**Comment by renefloor** [comment]
There are already multiple issues about this, such as #41 and #125. Retry logic is high on my list, but I can't give an eta.

**Comment by ztigunes** [comment]
Hello. i think useDiskCache, cacheRule, retryDuration, retryDurationFactor, retryLimit, timeoutDuration properties of "flutter_advanced_networkimage" is useful.  
Are they posssible on this widget? Best regards, Good luck with
