### ISSUE TITLE
error when trying to work with cached_network_image

### ISSUE THREAD

**Issue by mostafa2142** [Baseflow/flutter_cached_network_image#394]
i get this error when i want to work with CachedNetworkImage :

`E/flutter ( 3877): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
E/flutter ( 3877): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter ( 3877): <asynchronous suspension>
E/flutter ( 3877): #1      MethodChannelPathProvider.getTemporaryPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:34:26)
E/flutter ( 3877): #2      getTemporaryDirectory (package:path_provider/path_provider.dart:27:39)
E/flutter ( 3877): #3      DefaultCacheManager.getFilePath (package:flutter_cache_manager/src/cache_manager.dart:42:27)
E/flutter ( 3877): #4      BaseCacheManager._createFileDir (package:flutter_cache_manager/src/cache_manager.dart:244:41)
E/flutter ( 3877): #5      new BaseCacheManager (package:flutter_cache_manager/src/cache_manager.dart:83:20)
E/flutter ( 3877): #6      new DefaultCacheManager._ (package:flutter_cache_manager/src/cache_manager.dart:38:29)
E/flutter ( 3877): #7      new DefaultCacheManager (package:flutter_cache_manager/src/cache_manager.dart:34:39)
E/flutter ( 3877): #8      CachedNetworkImageState._cacheManager (package:cached_network_image/src/cached_image_widget.dart:404:35)
E/flutter ( 3877): #9      CachedNetworkImageState._createFileStream (package:cached_network_image/src/cached_image_widget.dart:242:19)
E/flutter ( 3877): #10     CachedNetworkImageState.initState (package:cached_network_image/src/cached_image_widget.dart:219:5)
E/flutter ( 3877): #11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter ( 3877): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 3877): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 3877): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 3877): #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 3877): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 3877): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 3877): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 3877): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 3877): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 3877): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 3877): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 3877): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 3877): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 3877): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 3877): #26     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5551:32)
E/flutter ( 3877): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 3877): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 3877): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 3877): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 3877): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 3877): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 3877): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 3877): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 3877): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 3877): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 3877): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 3877): #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 3877): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 3877): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 3877): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 3877): #42     Element.rebuild (
E/flutter ( 3877): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
E/flutter ( 3877): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter ( 3877): <asynchronous suspension>
E/flutter ( 3877): #1      invokeMethod (package:sqflite/src/sqflite_impl.dart:17:13)
E/flutter ( 3877): #2      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:31:7)
E/flutter ( 3877): #3      SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:25:35)
E/flutter ( 3877): #4      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:32)
E/flutter ( 3877): #5      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:27:7)
E/flutter ( 3877): #6      SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite_common/src/factory_mixin.dart:25:7)
E/flutter ( 3877): #7      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite_common/src/factory_mixin.dart:143:26)
E/flutter ( 3877): #8      getDatabasesPath (package:sqflite/sqflite.dart:168:54)
E/flutter ( 3877): #9      CacheStore._getObjectProvider (package:flutter_cache_manager/src/cache_store.dart:43:33)
E/flutter ( 3877): #10     new CacheStore (package:flutter_cache_manager/src/cache_store.dart:39:49)
E/flutter ( 3877): #11     new BaseCacheManager (package:flutter_cache_manager/src/cache_manager.dart:83:9)
E/flutter ( 3877): #12     new DefaultCacheManager._ (package:flutter_cache_manager/src/cache_manager.dart:38:29)
E/flutter ( 3877): #13     new DefaultCacheManager (package:flutter_cache_manager/src/cache_manager.dart:34:39)
E/flutter ( 3877): #14     CachedNetworkImageState._cacheManager (package:cached_network_image/src/cached_image_widget.dart:404:35)
E/flutter ( 3877): #15     CachedNetworkImageState._createFileStream (package:cached_network_image/src/cached_image_widget.dart:242:19)
E/flutter ( 3877): #16     CachedNetworkImageState.initState (package:cached_network_image/src/cached_image_widget.dart:219:5)
E/flutter ( 3877): #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter ( 3877): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 3877): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 3877): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 3877): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 3877): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 3877): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 3877): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 3877): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 3877): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 3877): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 3877): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 3877): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 3877): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 3877): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 3877): #32     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5551:32)
E/flutter ( 3877): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 3877): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 3877): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 3877): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 3877): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 3877): #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 3877): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 3877): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 3877): #41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 3877): #42     Element.inflateWidget (package:flutter/src/widgets/f`

this is my code :

` 
CachedNetworkImage(
                          imageUrl:  UrlAddress().getterUrlImageHandout()+imageAddress,
                          fit: BoxFit.cover,
                          progressIndicatorBuilder: (context, url, downloadProgress) {

                            return Container(
                                alignment: Alignment.center,
                                child: CupertinoActivityIndicator(animating: true,));
                          },
                          placeholder: (context, url) {
                            return Container(
                              alignment: Alignment.center,
                              child: CupertinoActivityIndicator(),);
                          },
                          errorWidget: (context, url, error){

                            return Icon(Icons.error);
                          }
                      ),`

it work fine with simple image.network() but after using CachedNetworkImage i get the above error i mentioned

**Comment by renefloor** [comment]
@mostafa2142 try to clean and rebuild your project.
Hot reload doesn't work well when adding packages.

Do you add to an existing native app or just flutter?

**Comment by mostafa2142** [comment]
> @mostafa2142 try to clean and rebuild your project.
> Hot reload doesn't work well when adding packages.
> 
> Do you add to an existing native app or just flutter?

after i got this error i was resting little bit drinked some coffee when i returned  i didnt get the error anymore thanks
