### ISSUE TITLE
Ability to load image without caching it

### ISSUE THREAD

**Issue by egprojects** [Baseflow/flutter_cached_network_image#397]
## 🚀 Feature Requests

Sometimes I don't need to cache image, but I can't control CachedNetworkImage.
### Contextualize the feature

For example, you can't see the result if you're running your app in Linux/Windows natively because Linux and Windows is not supported by sqflite but flutter_cache_manager depends on it. So, it just throws MissingPluginException and you can't see any image at all.
### Describe the feature

Just add boolean flag: `CachedNetworkImage(
    imageUrl: url,
    cache: false
)`
### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :apple: MacOS
- [x] Linux
- [x] Windows

**Comment by renefloor** [comment]
Why can't you just use networkimage when you don't want caching?

**Comment by apgapg** [comment]
@renefloor  We can have bool flag controlling this. Somethings in dynamic use case one may need to control this param from json.
For eg on Linux cachednetwork image doesnt work because of cache, hence for that i can add a check
