### ISSUE TITLE
App terminate and restart, image re download

### ISSUE THREAD

**Issue by gjrjf** [Baseflow/flutter_cached_network_image#401]
Thank you for making a great plugin.

My question is, when I quit the app and restart it, the image is downloaded again.

I wonder if this is the intended behavior.

In my guess, the image of the same URL once downloaded, should be taken from the local disk cache.

Please answer, and have a nice day.

**Comment by renefloor** [comment]
No indeed it should not download the image again. Hard to tell what's going wrong without any more information. Maybe the server is setting the cache-control headers to 0 or something like that.

**Comment by gjrjf** [comment]
> No indeed it should not download the image again. Hard to tell what's going wrong without any more information. Maybe the server is setting the cache-control headers to 0 or something like that.


thank you.

Let's change my server settings.

If I have a question again, may I ask a question again?

Thank you very much!!

**Comment by renefloor** [comment]
You can always ask, but maybe you get answers quicker on stackoverflow.

**Comment by gjrjf** [comment]
> You can always ask, but maybe you get answers quicker on stackoverflow.

Thanks!

it works.

-- server side added
res.setHeader("Cache-Control", "max-age=604800");
