### ISSUE TITLE
^2.2.0+1 was error

### ISSUE THREAD

**Issue by bluecrea** [Baseflow/flutter_cached_network_image#403]
add cached_network_image: ^2.2.0+1 to pubspec.yaml
run flutter run:
Error running pod install
Error launching application on iPhone 11 Pro.

flutter doctor -v
`[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F96, locale
    zh-Hans-CN)
    • Flutter version 1.17.2 
    • Framework revision 5f21edf8b6 (5 hours ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • iPhone 11 Pro • 362801A4-A00E-4CCC-A347-6345F468AC33 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)`

**Comment by renefloor** [comment]
I just switched to flutter 1.17.2, created a new project and added cachednetworkimage. Everything runs fine, so it is not broken on the latest stable.

It looks like it has something to do with you cocoapods, perhaps you can try this: https://github.com/flutter/flutter/issues/45853#issuecomment-561688326
