### ISSUE TITLE
How to update cache without changing url?

### ISSUE THREAD

**Issue by ed5on** [Baseflow/flutter_cached_network_image#405]
## 💬 Questions and Help

1. The image is downloaded in cache from the url.
2. The image changes on the server but not the url.
Is it possible to update the cache with the new image ?.

**Comment by renefloor** [comment]
If you know in the app that the image has changed you can call `DefaultCacheManager().removeFile(url)` and it will be removed from the cache. Next time you need the file it should update the file. 
Though it is better to set your `Cache-Control: max-age=<seconds>` to a value you find acceptable that the old image is shown or use a new url.
