### ISSUE TITLE
CachedImageWidget WITHOUT animation !

### ISSUE THREAD

**Issue by Xgamefactory** [Baseflow/flutter_cached_network_image#406]
It would be nice to have ability to disable animation at all. currently if fadeOutDuration is null 
it takes animation with duration 1 seconds by default.

<img width="686" alt="Screen Shot 2020-06-03 at 02 13 23" src="https://user-images.githubusercontent.com/22529051/83575199-12325580-a540-11ea-939a-5f97b19d0c1f.png">

**Comment by renefloor** [comment]
you can set duration to `Duration.zero`. `null` doesn't mean 0 seconds, but it means not set.

**Comment by Xgamefactory** [comment]
We are setting zero but inpackage source code still animation controller is using.

**Comment by renefloor** [comment]
@Xgamefactory why is that a problem?

**Comment by Xgamefactory** [comment]
it is not a correct to createresources and object if not needed.
itis like rendering a circular animation with zero opacity no one can see but there is impact on performance on huge project.

**Comment by renefloor** [comment]
the placeholder widget is removed after the animation is finished, because that was indeed a problem, but it shouldn't be anymore.
