### ISSUE TITLE
need some way to get the internal cached image

### ISSUE THREAD

**Issue by a43mrk** [Baseflow/flutter_cached_network_image#407]
Hello!
I'm trying to show the cached image from CachedNetworkImage inside another plugin but he wants an ImageProvider :(
how can i pass the cached image to the plugin?
or is there somehow to cast to that type?

**Comment by renefloor** [comment]
You can just use the CachedNetworkImageProvider like this (from the readme): `Image(image: CachedNetworkImageProvider(url))`

**Comment by a43mrk** [comment]
Thank you so much @renefloor
