### ISSUE TITLE
flutter_cached_network_image not loading image stuck on place holder widget

### ISSUE THREAD

**Issue by Chimba123** [Baseflow/flutter_cached_network_image#409]
## 🔙 Regression

I like this package it has been working fine but when I upgraded to the latest Flutter stable version 1.17.2 it has started exhibiting strange behavior, for example, the place holder widget both when I use a circular indicator or blur hash widget remains stuck and is not replaced with the actual image from the network when loaded. Further, it like breaks my camera code.

I made another project the camera worked fine but when I installed the package and used on several pages it again started getting stuck on the place holder and the camera code which is not even related to the widgets using it broke 
### Old (and correct) behavior
before the update to 1.17.2 the placeholder widget would be replaced with the loaded image from the url and the camera code worked fine
### Current behavior
placeholder widget not being replaced with the loaded image even though the data loads as shown by the flutter_bloc transition states in the console and my camera code is somehow getting affected by the package
### Reproduction steps
create a flutter project and fetch data from the internet using bloc pattern state management and while state is loading show circular indicator when state from the network is loaded show CachedNetworkImage() widget with placeholder being a blur hash and url being the loaded data. The placeholder is not replaced with the actual image from the url

### Configuration

**Version:** 2.2.0+1

**Platform:** 
- 

- [  #] :iphone: iOS

**Comment by renefloor** [comment]
Is the error what you actually posted in the other issue?
Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)

Could you give me a small concrete example in code, because I don't know how you would combine bloc with this library

**Comment by Chimba123** [comment]
> Is the error what you actually posted in the other issue?
> Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
> 
> Could you give me a small concrete example in code, because I don't know how you would combine bloc with this library

As in it keeps compounding after I try fixes from Stackoverflow and Github it started with the error int the other issue

**Comment by Chimba123** [comment]
`CupertinoPageScaffold(
      navigationBar: feedsBar(context, widget.currentIndex),
      child: PrimaryScrollController(
        controller: scrollController,
        child: CupertinoScrollbar(
            controller: scrollController,
            child: BlocBuilder<SocialsFeedBloc, SocialsFeedState>(
              builder: (context, SocialsFeedState state) {
                if (state is SocialsFeedLoading) {
                  print(state);
                  return socialsFeedLoading();
                }
                if (state is SocialsFeedLoaded) {
                  final List<SocialsFeedModel> data = state.feedData;
                  print(data);
                  return CustomScrollView(
                    slivers: <Widget>[
                      CupertinoSliverRefreshControl(
                          onRefresh: () async => await Future<void>.delayed(
                              const Duration(seconds: 2))),
                      listViewWidget(data)
                    ],
                  );
                }
                if (state is SocialsFeedError) {
                  return Center(
                    child: Text(
                      'Something went wrong!',
                      style: TextStyle(color: Colors.red),
                    ),
                  );
                }
                return socialsFeedLoading();
              },
            )),
      ),
    )`


`  Widget listViewWidget(List<SocialsFeedModel> hits) {
    return SliverList(
      delegate: SliverChildListDelegate(
        new List<Widget>.generate(hits.length, (int index) {
          return Container(
            padding: EdgeInsets.fromLTRB(2.0, 0.0, 2.0, 0.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.start,
              children: <Widget>[
                Container(
                  margin: EdgeInsets.all(5.0),
                  child: Row(
                    children: <Widget>[
                      Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          GestureDetector(
                            onTap: () =>
                                Navigator.of(context, rootNavigator: true)
                                    .pushNamed('/othersSocialsProfilePage'),
                            child: Container(
                              margin: EdgeInsets.fromLTRB(0.0, 0.0, 4.0, 0.0),
                              child: CircleAvatar(
                                radius: 17.0,
                                backgroundImage:
                                    ExactAssetImage('${_items[index]}'),
                              ),
                            ),
                          ),
                          Container(
                            margin: EdgeInsets.fromLTRB(0.0, 9.0, 210.0, 0.0),
                            child: SizedBox(
                              width: 89.0,
                              child: Text('${_names[index]}',
                                  style: TextStyle(
                                      fontFamily: 'Avenir-Medium',
                                      fontSize: 12.0,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.black)),
                            ),
                          ),
                        ],
                      ),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.end,
                        children: <Widget>[
                          GestureDetector(
                            onTap: () => _showBottomSheet(),
                            child: Container(
                                margin: EdgeInsets.fromLTRB(0.0, 9.0, 0.0, 0.0),
                                child: Icon(
                                  Icons.more_horiz,
                                  color: Colors.black,
                                )),
                          ),
                        ],
                      )
                    ],
                  ),
                ),
                GestureDetector(
                  onLongPress: () => _incrementCounter1(),
                  onDoubleTap: () => onJoin('${hits[index].largeImageURL}'),
                  child: Container(
                    child: SizedBox(
                        width: double.infinity,
                        height: 230,
                        child:

                        CachedNetworkImage(
                          imageUrl: '${hits[index].largeImageURL}',
                          placeholder: (context, url) => const AspectRatio(
                            aspectRatio: 1.6,
                            child: BlurHash(hash: 'LEHV6nWB2yk8pyo0adR*.7kCMdnj'),
                          ),
                          errorWidget: (context, url, error) => const Icon(Icons.refresh),
                          fit: BoxFit.cover,
                        ),

                    ),

                    /*
                    CachedNetworkImage(
                        imageUrl: '${hits[index].largeImageURL}',
                        placeholder: (context, url) => const AspectRatio(
                          aspectRatio: 1.6,
                          child: BlurHash(hash: 'LEHV6nWB2yk8pyo0adR*.7kCMdnj'),
                        ),
                        errorWidget: (context, url, error) => const Icon(Icons.refresh),
                        fit: BoxFit.cover,


                      ),
                    Image.network('${hits[index].largeImageURL}'),
                    CachedNetworkImage(
                      placeholder: (context, url) => CupertinoActivityIndicator(
                        radius: 5.5,
                      ),
                      imageUrl: '${hits[index].largeImageURL}',
                      fit: BoxFit.contain,
                      errorWidget: (context, url, error) => new Icon(
                        Icons.refresh,
                      ),
                    ),

                    */
                    //  imageUrl: '${hits[index].largeImageURL}',
                  ),
                ),
                Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.max,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      Container(
                        child: Row(
                          children: <Widget>[
                            IconButton(
                              icon: Icon(
                                IconData(
                                  0xe900,
                                  fontFamily: 'love0',
                                ),
                                color: Colors.blueGrey[800],
                                size: 30.0,
                              ),
                              onPressed: () {
                                _incrementCounter1();
//                                FlutterRingtonePlayer.play(
//                                  android: AndroidSounds.notification,
//                                  ios: IosSounds.chime,
//                                  looping: true, // Android only - API >= 28
//                                  volume: 0.1, // Android only - API >= 28
//                                  asAlarm: false, // Android only - all APIs
//                                );
                              },
                            ),
                            Container(
                                margin: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 3.0),
                                child: SizedBox(
                                    width: 15.0,
                                    child: Text.rich(TextSpan(
                                        text: '$_counter1',
                                        style: TextStyle(
                                            fontSize: 12.0,
                                            color: Colors.blueGrey[800])))))
                          ],
                        ),
                      ),
                      Row(
                        children: <Widget>[
                          IconButton(
                            icon: Icon(
                              IconData(
                                0xe900,
                                fontFamily: 'comment2',
                              ),
                              color: Colors.blueGrey[800],
                              size: 20.0,
                            ),
                            onPressed: () {
                              _moveToCommentsPage(
                                  '${hits[index].largeImageURL}');
                            },
                          ),
                          Container(
                              margin: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 3.0),
                              child: SizedBox(
                                  width: 30.0,
                                  child: Text.rich(TextSpan(
                                      text: '${hits[index].comments}',
                                      style: TextStyle(
                                          fontSize: 12.0,
                                          color: Colors.blueGrey[800])))))
                        ],
                      ),
                      Row(
                        children: <Widget>[
                          Container(
                            margin: EdgeInsets.fromLTRB(0.0, 0.0, 71.0, 0.0),
                            child: IconButton(
                              icon: Icon(
                                IconData(
                                  0xe900,
                                  fontFamily: 'np_webcam0',
                                ),
                                color: Colors.blueGrey[800],
                                size: 20.0,
                              ),
                              onPressed: () {
//                                Navigator.of(context, rootNavigator: true)
//                                    .pushNamed('/rtc');
                                onJoin('${hits[index].largeImageURL}');
                              },
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
                Container(
                  margin: const EdgeInsets.fromLTRB(13.0, 0.0, 0.0, 15.0),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      Container(
                        child: secondHalf.isEmpty
                            ? new Text(firstHalf)
                            : new Column(
                                children: <Widget>[
                                  new Text(
                                    flag
                                        ? (firstHalf + "...")
                                        : (firstHalf + secondHalf),
                                    style: TextStyle(
                                        fontSize: 12.0,
                                        fontFamily: 'Avenir-Medium'),
                                  ),
                                  GestureDetector(
                                    onTap: () {
                                      setState(() {
                                        flag = !flag;
                                      });
                                    },
                                    child: new Container(
                                      child: flag
                                          ? Icon(
                                              Icons.arrow_drop_down,
                                              color: Colors.grey,
                                            )
                                          : Icon(Icons.arrow_drop_up,
                                              color: Colors.grey),
                                    ),
                                  ),
                                ],
                              ),
                      )
                    ],
                  ),
                ),
              ],
            ),
          );
        }),
      ),
    );
  }
`

**Comment by Chimba123** [comment]
``  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: feedsBar(context, widget.currentIndex),
      child: PrimaryScrollController(
        controller: scrollController,
        child: CupertinoScrollbar(
            controller: scrollController,
            child: BlocBuilder<SocialsFeedBloc, SocialsFeedState>(
              builder: (context, SocialsFeedState state) {
                if (state is SocialsFeedLoading) {
                  print(state);
                  return socialsFeedLoading();
                }
                if (state is SocialsFeedLoaded) {
                  final List<SocialsFeedModel> data = state.feedData;
                  print(data);
                  return CustomScrollView(
                    slivers: <Widget>[
                      CupertinoSliverRefreshControl(
                          onRefresh: () async => await Future<void>.delayed(
                              const Duration(seconds: 2))),
                      listViewWidget(data)
                    ],
                  );
                }
                if (state is SocialsFeedError) {
                  return Center(
                    child: Text(
                      'Something went wrong!',
                      style: TextStyle(color: Colors.red),
                    ),
                  );
                }
                return socialsFeedLoading();
              },
            )),
      ),
    );
  }

**Comment by Chimba123** [comment]
``Widget listViewWidget(List<SocialsFeedModel> hits) {
    return SliverList(
      delegate: SliverChildListDelegate(
        new List<Widget>.generate(hits.length, (int index) {
          return Container(
            padding: EdgeInsets.fromLTRB(2.0, 0.0, 2.0, 0.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.start,
              children: <Widget>[
                Container(
                  margin: EdgeInsets.all(5.0),
                  child: Row(
                    children: <Widget>[
                      Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          GestureDetector(
                            onTap: () =>
                                Navigator.of(context, rootNavigator: true)
                                    .pushNamed('/othersSocialsProfilePage'),
                            child: Container(
                              margin: EdgeInsets.fromLTRB(0.0, 0.0, 4.0, 0.0),
                              child: CircleAvatar(
                                radius: 17.0,
                                backgroundImage:
                                    ExactAssetImage('${_items[index]}'),
                              ),
                            ),
                          ),
                          Container(
                            margin: EdgeInsets.fromLTRB(0.0, 9.0, 210.0, 0.0),
                            child: SizedBox(
                              width: 89.0,
                              child: Text('${_names[index]}',
                                  style: TextStyle(
                                      fontFamily: 'Avenir-Medium',
                                      fontSize: 12.0,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.black)),
                            ),
                          ),
                        ],
                      ),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.end,
                        children: <Widget>[
                          GestureDetector(
                            onTap: () => _showBottomSheet(),
                            child: Container(
                                margin: EdgeInsets.fromLTRB(0.0, 9.0, 0.0, 0.0),
                                child: Icon(
                                  Icons.more_horiz,
                                  color: Colors.black,
                                )),
                          ),
                        ],
                      )
                    ],
                  ),
                ),
                GestureDetector(
                  onLongPress: () => _incrementCounter1(),
                  onDoubleTap: () => onJoin('${hits[index].largeImageURL}'),
                  child: Container(
                    child: SizedBox(
                        width: double.infinity,
                        height: 230,
                        child:

                        CachedNetworkImage(
                          imageUrl: '${hits[index].largeImageURL}',
                          placeholder: (context, url) => const AspectRatio(
                            aspectRatio: 1.6,
                            child: BlurHash(hash: 'LEHV6nWB2yk8pyo0adR*.7kCMdnj'),
                          ),
                          errorWidget: (context, url, error) => const Icon(Icons.refresh),
                          fit: BoxFit.cover,
                        ),

                    ),

                    /*
                    CachedNetworkImage(
                        imageUrl: '${hits[index].largeImageURL}',
                        placeholder: (context, url) => const AspectRatio(
                          aspectRatio: 1.6,
                          child: BlurHash(hash: 'LEHV6nWB2yk8pyo0adR*.7kCMdnj'),
                        ),
                        errorWidget: (context, url, error) => const Icon(Icons.refresh),
                        fit: BoxFit.cover,


                      ),
                    Image.network('${hits[index].largeImageURL}'),
                    CachedNetworkImage(
                      placeholder: (context, url) => CupertinoActivityIndicator(
                        radius: 5.5,
                      ),
                      imageUrl: '${hits[index].largeImageURL}',
                      fit: BoxFit.contain,
                      errorWidget: (context, url, error) => new Icon(
                        Icons.refresh,
                      ),
                    ),

                    */
                    //  imageUrl: '${hits[index].largeImageURL}',
                  ),
                ),
                Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.max,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      Container(
                        child: Row(
                          children: <Widget>[
                            IconButton(
                              icon: Icon(
                                IconData(
                                  0xe900,
                                  fontFamily: 'love0',
                                ),
                                color: Colors.blueGrey[800],
                                size: 30.0,
                              ),
                              onPressed: () {
                                _incrementCounter1();
//                                FlutterRingtonePlayer.play(
//                                  android: AndroidSounds.notification,
//                                  ios: IosSounds.chime,
//                                  looping: true, // Android only - API >= 28
//                                  volume: 0.1, // Android only - API >= 28
//                                  asAlarm: false, // Android only - all APIs
//                                );
                              },
                            ),
                            Container(
                                margin: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 3.0),
                                child: SizedBox(
                                    width: 15.0,
                                    child: Text.rich(TextSpan(
                                        text: '$_counter1',
                                        style: TextStyle(
                                            fontSize: 12.0,
                                            color: Colors.blueGrey[800])))))
                          ],
                        ),
                      ),
                      Row(
                        children: <Widget>[
                          IconButton(
                            icon: Icon(
                              IconData(
                                0xe900,
                                fontFamily: 'comment2',
                              ),
                              color: Colors.blueGrey[800],
                              size: 20.0,
                            ),
                            onPressed: () {
                              _moveToCommentsPage(
                                  '${hits[index].largeImageURL}');
                            },
                          ),
                          Container(
                              margin: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 3.0),
                              child: SizedBox(
                                  width: 30.0,
                                  child: Text.rich(TextSpan(
                                      text: '${hits[index].comments}',
                                      style: TextStyle(
                                          fontSize: 12.0,
                                          color: Colors.blueGrey[800])))))
                        ],
                      ),
                      Row(
                        children: <Widget>[
                          Container(
                            margin: EdgeInsets.fromLTRB(0.0, 0.0, 71.0, 0.0),
                            child: IconButton(
                              icon: Icon(
                                IconData(
                                  0xe900,
                                  fontFamily: 'np_webcam0',
                                ),
                                color: Colors.blueGrey[800],
                                size: 20.0,
                              ),
                              onPressed: () {
//                                Navigator.of(context, rootNavigator: true)
//                                    .pushNamed('/rtc');
                                onJoin('${hits[index].largeImageURL}');
                              },
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
                Container(
                  margin: const EdgeInsets.fromLTRB(13.0, 0.0, 0.0, 15.0),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      Container(
                        child: secondHalf.isEmpty
                            ? new Text(firstHalf)
                            : new Column(
                                children: <Widget>[
                                  new Text(
                                    flag
                                        ? (firstHalf + "...")
                                        : (firstHalf + secondHalf),
                                    style: TextStyle(
                                        fontSize: 12.0,
                                        fontFamily: 'Avenir-Medium'),
                                  ),
                                  GestureDetector(
                                    onTap: () {
                                      setState(() {
                                        flag = !flag;
                                      });
                                    },
                                    child: new Container(
                                      child: flag
                                          ? Icon(
                                              Icons.arrow_drop_down,
                                              color: Colors.grey,
                                            )
                                          : Icon(Icons.arrow_drop_up,
                                              color: Colors.grey),
                                    ),
                                  ),
                                ],
                              ),
                      )
                    ],
                  ),
                ),
              ],
            ),
          );
        }),
      ),
    );
  }

**Comment by renefloor** [comment]
You could try this : https://github.com/Baseflow/flutter_cached_network_image/issues/290#issuecomment-637304457

**Comment by Chimba123** [comment]
@renefloor thanks just realized I had commented out GeneratedRegistrantPlugin in my AppDelegate.swift file sometime back when writing some native swift code to call a third party SDK but had forgotten to uncomment it because sometimes Xcode doesn't recognize it when you clean the build folder within it 🤦🏾‍♂️.  

The package now works properly. Thanks for the help and the package great plugin. keep it up
