### ISSUE TITLE
Why does caching still consume network traffic?

### ISSUE THREAD

**Issue by didyqian** [Baseflow/flutter_cached_network_image#410]
## 💬 Questions and Help

For questions or help we recommend checking:

Why does cache still consume network traffic? I wrapped the flutter_cached_network_image in Swiper and the app occupies 50M of traffic per minute.

**Comment by renefloor** [comment]
I don't know, could be anything. Maybe using lots of images once, or maybe the cache-control header indicates a very short max-age? 50MB per minute would be a lot even without any caching. You probably should make your images a bit smaller if it is really 50MB of images.
