### ISSUE TITLE
Pre-Load Images

### ISSUE THREAD

**Issue by leopries** [Baseflow/flutter_cached_network_image#411]
## 🚀 Feature Requests

It would be really helpful if there would be an option to preload the image before displaying it. 

### Contextualize the feature
In is often desirable to load all images while waiting on a loading screen and displaying a page with all images to avoid a visual change afterwards.

### Describe the feature
This could be possible by using something like the "precacheImage" function from flutter. 

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
The precacheImage should just work. See https://github.com/Baseflow/flutter_cached_network_image/issues/369#issuecomment-623601555
