### ISSUE TITLE
Local Placeholder

### ISSUE THREAD

**Issue by Dhruv245** [Baseflow/flutter_cached_network_image#414]
I want to add a  local placeholder but it is showing error

**Comment by renefloor** [comment]
Sorry, I can't help you without more information

**Comment by Dhruv245** [comment]
I want to add a local placeholder image i.e. the placeholder image should be inside the project

**Comment by renefloor** [comment]
Yes? What's wrong with an asset image as placeholder?
https://api.flutter.dev/flutter/widgets/Image/Image.asset.html

**Comment by Dhruv245** [comment]
In place of
placeholder: (context, url) => CircularProgressIndicator(),
I want to use 
placeholder: 'assets/loading.gif',
But is is showing error
The argument type 'String' can't be assigned to the parameter type 'Widget Function(BuildContext, String)'

**Comment by Dhruv245** [comment]
I mean that how to use a custom placeholder

**Comment by renefloor** [comment]
The placeholder should be a builder that returns a widget, but it can be any widget.
Just do 
```
placeholder: (context, url) => Image.asset('assets/loading.gif')
```
