### ISSUE TITLE
counldn' t show image in iOS native project as flutter module

### ISSUE THREAD

**Issue by siyangstar** [Baseflow/flutter_cached_network_image#419]
while using flutter "as a module" in native iOS project, the plugin couldn't work well. the image couldn't load successfully. only show the placeholder.

the issue didn't appear in android project.
the issue didn't appear in flutter project even if in ios platform.

flutter sdk version:  1.17.3
mac os version: 10.15.5
both ios simulator and iphone 11 failed.

**Comment by renefloor** [comment]
Did the project give any error?

**Comment by siyangstar** [comment]
> Did the project give any error?

flutter module was made to framework to be migrate to ios project, and didn't find any error log in xcode.

it's easy to reproduce:
1. create a new ios project
2.create a flutter module with a simple cachedNetworkImage.
3.make the module into a framework
4.migrate the framework to ios project

**Comment by siyangstar** [comment]
> Did the project give any error?

Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)

**Comment by 15809284891** [comment]
I encountered the same problem, how did you solve it?

**Comment by 15809284891** [comment]
I encountered the same problem, how did you solve it?，But i don't get any error.
