### ISSUE TITLE
Clear Cache for an update image

### ISSUE THREAD

**Issue by dekadevelop** [Baseflow/flutter_cached_network_image#421]
## 🏗 Enhancement Proposal

Hi,
what if we have updated an image,
how do we clear the cache for that image?

**Comment by ph55** [comment]
https://github.com/Baseflow/flutter_cached_network_image/issues/280

**Comment by dekadevelop** [comment]
I tried DefaultCacheManager().emptyCache() (also with url)
but it's not working, I have to go into the settings/app/clear cache manually

**Comment by dekadevelop** [comment]
it seems that is pointing to its own cache db name 'libCachedImageData' but it's not the same of this plugin

**Comment by baptistecassar** [comment]
not working anymore. version ^2.2.0

**Comment by dekadevelop** [comment]
for me neither

**Comment by P-B1101** [comment]
not working for me too.
i downgrade to version 2.0.0 (that work earlier). but not working on that version too :| 
i had to use dependency_overrides. its ok now but there is a problem in version 2.0.0 and it's that when there is no correct file on the correct url it throw an exception. this problem solved in version 2.2.0.
i'd rather to use the older version.
