### ISSUE TITLE
placeholder used even when image is in cache

### ISSUE THREAD

**Issue by yanivshaked** [Baseflow/flutter_cached_network_image#426]
## 🐛 Bug Report

The placeholder is displayed for a short while even when the image already exists in cache prior to using CachedNetworkImage.

### Expected behavior

Show the image immediately, without using placeholder.

### Reproduction steps

I'm using CachedNetworkImage (with an http URL pointing to some Firebase storage).
Launching the application on the first time, the placeholder is displayed and then the requested image. I assume that at this point, since the image is already displayed, it is saved to cache.
Closing the application, and starting it again. The placeholder is displayed again, and replaced by the requested image later.

Reproduced on Android.

**Comment by renefloor** [comment]
@yanivshaked yes that's right, at the moment the placeholder is shown when the image is loaded from the cache. We don't expect this will change any time soon.

**Comment by yanivshaked** [comment]
Ok, in that case, is it possible to use CachedNetworkImageProvider just to prefetch the image from the cache so when CachedNetworkImage is used, the image will be displayed instantly (on the first refresh event)?
(I'm trying to suggest a workaround to solve this issue)

**Comment by renefloor** [comment]
Version 2.2 uses a FileImage for the widget, but when you use version 2.3.0-rc you can use [the precacheImage function](https://api.flutter.dev/flutter/widgets/precacheImage.html) to load the image into memory.
