### ISSUE TITLE
HttpException: No valid statuscode.

### ISSUE THREAD

**Issue by raphaaugustosilva** [Baseflow/flutter_cached_network_image#433]
## 🐛 Bug Report

My app is crashing when there is an invalid, not found, or malformed url.

Exception is :
`
I/flutter ( 8040): CacheManager: Failed to download file from https://firebasestorage.googleapis.com/v0/b/yes4track-b20a3/o/card_experiencia_peralles.JPG?alt=media&token=10738ca2-ef34-4156-9a60-744c24f562072 with error:

I/flutter ( 8040): HttpException: Invalid statusCode: 403, uri = https://firebasestorage.googleapis.com/v0/b/yes4track-b20a3/o/card_experiencia_peralles.JPG?alt=media&token=10738ca2-ef34-4156-9a60-744c24f562072
`

### Expected behavior
It would just render the "errorWidget" and if necessary by the component, it could even log, but without throwing an exception to app.

### Reproduction steps
`
return Container(
        height: 100,
        width: 100,
        child: CachedNetworkImage(
          imageUrl: _myUrl,
          imageBuilder: (context, imageProvider) => CircleAvatar(backgroundImage: imageProvider),
          placeholder: (context, url) => any_widget,
          errorWidget: (context, url, error) => any_widget,
        ),
      );
`

### Configuration

**Version:** ^2.3.0-beta.1+1 (or ^2.2.0+1 too)

**Platform:** 
- [ can`t say ] :iphone: iOS
- [X] :robot: Android

**Comment by renefloor** [comment]
Is it really crashing or is just the debugger pausing your app? It should at most pause your debugger. If you can create a video of a crashing app please reopen this issue.

**Comment by juanlabrador** [comment]
Please use this link, it's return 403 status 
http://s3.amazonaws.com/enbola-prod/product/images/628d86ed8bf6fe3c3af8817f/original.628d86ed8bf6fe3c3af8817f.jpg?1653442285
