### ISSUE TITLE
Not caching image after app restart

### ISSUE THREAD

**Issue by vegidio** [Baseflow/flutter_cached_network_image#434]
Hi,

I'm not sure if this is a bug or if I'm doing something terribly wrong, but I'm using the exact same piece of code provided in the example:

```
CachedNetworkImage(
  imageUrl: "http://via.placeholder.com/350x150",
  placeholder: (context, url) => CircularProgressIndicator(),
  errorWidget: (context, url, error) => Icon(Icons.error),
),
```

The cache is used while the app is still open and I try to send download the image from the same URL more than once, however if I kill the app and open it again then the cache is gone.

I'm using version ^2.2.0+1.

**Comment by tonyzolnoski** [comment]
@vegidio It appears that **flutter_cached_network_image** uses the **[flutter_cache_manager](https://pub.dev/packages/flutter_cache_manager)** library.  According to their documentation the OS has control over the cache.  The OS is most likely clearing the cache when you close the app.

**Comment by vegidio** [comment]
@tonyzolnoski Thanks for the reply. However, this library is running in the early development stages of my app and I'm downloading a single image so far. I don't think the OS would be need to clear just one image.

In any case, is there a way to prevent to OS from clearing the cache?

**Comment by xJon** [comment]
Did you end up finding a solution for this?
