### ISSUE TITLE
Is there any option to disable cache functionality of cachednetworkimage for a particular image while retaining other functionality?

### ISSUE THREAD

**Issue by shujaatak** [Baseflow/flutter_cached_network_image#435]
I was wondering if there is any option/property like `cache: false;` to disable caching for a specific image while retaining the remaining  awesome functionality like `placeholder` and `errorWidget` of the cachednetworkimage.

**Comment by renefloor** [comment]
@shujaatak If you just want placeholder and errorWidget functionality you could also use [https://pub.dev/packages/octo_image](octo_image). CachedNetworkImage v2.3.0 uses that under the hood.
