### ISSUE TITLE
CachedNetworkImageProvider web support

### ISSUE THREAD

**Issue by zsyphon** [Baseflow/flutter_cached_network_image#436]
I am having trouble with CORS when  I run my  app as a web  app. 

I've added the allow-origin  header, but nothing is working.

e.g. CachedNetworkImageProvider('imageURL',  headers: {'Access-Control-Allow-Origin': '*'})

Thank you for any  suggestions you may have

**Comment by zsyphon** [comment]
I was able to solve this because I was using firebase storage. Had to follow the CORS steps here: https://firebase.google.com/docs/storage/web/download-files

**Comment by percula** [comment]
@zsyphon I'm running into an issue getting it to work with Firebase Storage too. I've tried adding the header and enabling CORS like you mentioned, but no luck. The CachedNetworkImage keeps failing with the unhelpful error of an empty `Event` object and an empty stack trace. Did you need to do anything else to get it to work? Thanks in advance!

**Comment by percula** [comment]
Nevermind, found the fix! i needed to specify `imageRenderMethodForWeb: ImageRenderMethodForWeb.HttpGet`
