### ISSUE TITLE
Image is not getting Displayed. Spinner keeps on Loading

### ISSUE THREAD

**Issue by vinoopks** [Baseflow/flutter_cached_network_image#437]
## 🐛 Bug Report

The image is not getting loaded using CachedNetworkImage, but Image.network call works without any issues. 
I used the code from the official documentation.

```
import 'package:flutter/material.dart';
import 'package:cached_network_image/cached_network_image.dart';

class App extends StatelessWidget {
  const App({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    final title = 'Cached Images';
    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Center(
          child: CachedNetworkImage(
            placeholder: (context, url) => CircularProgressIndicator(),
            imageUrl: 'https://picsum.photos/250?image=9',
          ),
        ),
      ),
    );
  }
}
```

### Observations- From Debug Console

First time load works as expected. But second time on wards getting the following issues. 
E/flutter ( 7071): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)

E/flutter ( 7071): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] **Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)**

Progress spinner is spinning forever, I am not sure if this is some kind of configuration issue from my end.
But when I user Image.network(url), Images gets displayed as expected.

### Configuration

**Version:**   cached_network_image: ^2.2.0+1
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.329], locale en-IN) 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.2)
[√] Connected device (1 available)
• No issues found!

**Comment by omidraha** [comment]
You need to reinstall the app, hot reloading not working at first installing.

**Comment by vinoopks** [comment]
@omidraha 
Reinstalled the app. Still I was getting the same error. 

I checked online for solutions, but none of them actually worked for me.
MainActivity.kt seemed to be normal 
```
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
```

AndroidManifest.xml 
 ```
  <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>

```

**Comment by yourshinsuke** [comment]
but, `flutter_advanced_networkimage` worked.

**Comment by renefloor** [comment]
@vinoopks what is the platform you have this error on?

**Comment by Satyam953** [comment]
1. Install the latest dependency for cached_network_image:
2. Stop the app if you are debugging or running
3. Flutter clean
4. Quite from IDE
5. Reopen your IDE and run pub get
6.Run the app/web/...
