### ISSUE TITLE
How to create a subclass of CachedNetworkImageProvider

### ISSUE THREAD

**Issue by sandart** [Baseflow/flutter_cached_network_image#438]
## 💬 Questions and Help

Hi, guys. I want to create a new subclass of CachedNetworkImageProvider. i want to compress image when the image has download completed.  but  i don`t know how to write here, Can you write a demo for me? thank you !

**Comment by renefloor** [comment]
You can download the file manually, compress it and put it in the cache here: https://pub.dev/documentation/flutter_cache_manager/latest/flutter_cache_manager/BaseCacheManager/putFile.html
