### ISSUE TITLE
The HEIC image on iOS support

### ISSUE THREAD

**Issue by yuanzhiying** [Baseflow/flutter_cached_network_image#442]
## 🚀 Feature Requests

When i pick HEIC image from image picker on iOS，the image can not cache to the disk and show on the widget.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS

**Comment by renefloor** [comment]
@yuanzhiying you can follow support on HEIC images here: https://github.com/flutter/flutter/issues/20522

**Comment by dnfield** [comment]
iOS HEIF/HEIC support was added in 1.21.0-7.0.pre - can you try with that version or later and see if it works?

**Comment by renefloor** [comment]
@yuanzhiying can you try if it works for you?
