### ISSUE TITLE
App Crash when large number of image is loading

### ISSUE THREAD

**Issue by AhmedKhattab95** [Baseflow/flutter_cached_network_image#444]
## 🐛 Bug Report

it's related to this bug and not solved yet from flutter team could be solved in this plugin
https://github.com/flutter/flutter/issues/20910

**Platform:** 
- [-] :iphone: iOS
- [-] :robot: Android

**Comment by hossam-zaki** [comment]
I have the same exact issue, can someone comment on this?

**Comment by renefloor** [comment]
The ticket you are referring to is about the logging in Flutter when an url is invalid or the image can't be downloaded from the url for a different reason. The logging is an info log about the exception and not about a crashing app.

If your app really crashes on loading a large number of images it could be a duplicate of #429. If it is something else please reopen the issue with some more information on the exception and some code to replicate.
