### ISSUE TITLE
clear cache for update image

### ISSUE THREAD

**Issue by P-B1101** [Baseflow/flutter_cached_network_image#446]
## 🔙 Regression
in version prior of 2.0.0 we could clear image cache using flutter_cache_manager package. but now its not working.
### Old (and correct) behavior
clear image cache using flutter_cache_manager package.
### Current behavior
cache could not clear
### Reproduction steps
1. create hello world app and add flutter_cache_manager and cached_network_image.
2. load some image.
3. change source image (with same name/url).
4. clear cache with DefaultCacheManager().removeFile(url).
5. setState for rebuild ui.
nothing happen (image would not update).
close app and open it again. the image will be updated.
**Version:** 2.2.0+1

**Platform:** 
- [ ] :robot: Android
- [ ] :iphone: iOS

**Comment by ThomasMiddel** [comment]
I didn't fully dive into it, but we had a similar issue and I'm assuming it has something to do with Flutter's ImageCache. Under the hood `CachedNetworkImage` is eventually using `ResizeImage`, which makes use of the in-memory `ImageCache`. 

I was able to solve it here by only using the `CachedNetworkImageProvider` for file caching purposes & clearing both de in-memory cache as well as the file when needed. This would trigger an actual refresh of the image. 

A quick snippet of how I'm using it now (no guarantees, free-handed this just now 🤓):

```
Widget _getImage() {
  final imageProvider = ResizeImage.resizeIfNeeded(
    width,
    height,
    CachedNetworkImageProvider(
      url,
    ),
  );

  final image = Image(
    image: imageProvider,
  );

  if (refresh) {
    return FutureBuilder<void>(
      future: Future.wait([imageProvider.evict(), DefaultCacheManager().removeFile(url)]),
      builder: (_, __) => image,
    );
  }

  return image;
}
```

**Comment by P-B1101** [comment]
> I didn't fully dive into it, but we had a similar issue and I'm assuming it has something to do with Flutter's ImageCache. Under the hood `CachedNetworkImage` is eventually using `ResizeImage`, which makes use of the in-memory `ImageCache`.
> 
> I was able to solve it here by only using the `CachedNetworkImageProvider` for file caching purposes & clearing both de in-memory cache as well as the file when needed. This would trigger an actual refresh of the image.
> 
> A quick snippet of how I'm using it now (no guarantees, free-handed this just now 🤓):
> 
> ```
> Widget _getImage() {
>   final imageProvider = ResizeImage.resizeIfNeeded(
>     width,
>     height,
>     CachedNetworkImageProvider(
>       url,
>     ),
>   );
> 
>   final image = Image(
>     image: imageProvider,
>   );
> 
>   if (refresh) {
>     return FutureBuilder<void>(
>       future: Future.wait([imageProvider.evict(), DefaultCacheManager().removeFile(url)]),
>       builder: (_, __) => image,
>     );
>   }
> 
>   return image;
> }
> ```

it work for change image but it fail in one scenario.
imagine there is three image source. A and B and C.
A and B are fine image but the C is a broken image file (therefore the errorBuilder will show if i try to show C).
i change image between A and B, everything is perfect and images will update every time.
but if i load A first it will show A image and then load C (the broken image) it will show errorBuilder and then i try to load A or B, nothing happen (continuously show errorBuilder).
i have to change page or exit the app and reopen it again to update image.
i hope that i could describe the problem.
thanks anyway.

**Comment by ThomasMiddel** [comment]
I'm assuming, in that case, it fails on clearing the cache because there's no image cached?

**Comment by P-B1101** [comment]
yes. that is the main problem i guess.

**Comment by ThomasMiddel** [comment]
What if, in the case of the error, you retry loading the image without trying to clear the cache. Does that work?

**Comment by maxlapides** [comment]
I am also having an issue with the latest version, 2.3.1. Previously, I could call `DefaultCacheManager().removeFile(url)` but now this doesn't seem to work.

**Comment by AcmeField** [comment]
> I am also having an issue with the latest version, 2.3.1. Previously, I could call `DefaultCacheManager().removeFile(url)` but now this doesn't seem to work.

Could you please tell me what are the flutter_cache_manager And cached_network_image And version that you could use normally before?

**Comment by maxlapides** [comment]
> > I am also having an issue with the latest version, 2.3.1. Previously, I could call `DefaultCacheManager().removeFile(url)` but now this doesn't seem to work.
> 
> Could you please tell me what are the flutter_cache_manager And cached_network_image And version that you could use normally before?

cached_network_image: 2.2.0+1
flutter_cache_manager: 1.4.1

**Comment by renefloor** [comment]
Version 2.3 uses ImageProviders more efficiently, so you'll also need to clear the image from the ImageProvider cache. 
Here is an example of how to do it with NetworkImage, but that should also work for CachedNetworkImage: https://api.flutter.dev/flutter/painting/ImageProvider/evict.html
```
  void evictImage() {
    final NetworkImage provider = NetworkImage(url);
    provider.evict().then<void>((bool success) {
      if (success)
        debugPrint('removed image!');
    });
```

This package needs a method like this to clear an image both from the file cache and memory cache.

**Comment by gjrjf** [comment]
> Version 2.3 uses ImageProviders more efficiently, so you'll also need to clear the image from the ImageProvider cache.
> Here is an example of how to do it with NetworkImage, but that should also work for CachedNetworkImage: https://api.flutter.dev/flutter/painting/ImageProvider/evict.html
> 
> ```
>   void evictImage() {
>     final NetworkImage provider = NetworkImage(url);
>     provider.evict().then<void>((bool success) {
>       if (success)
>         debugPrint('removed image!');
>     });
> ```
> 
> This package needs a method like this to clear an image both from the file cache and memory cache.

not working..

**Comment by yoniker** [comment]
> Version 2.3 uses ImageProviders more efficiently, so you'll also need to clear the image from the ImageProvider cache.
> Here is an example of how to do it with NetworkImage, but that should also work for CachedNetworkImage: https://api.flutter.dev/flutter/painting/ImageProvider/evict.html
> 
> ```
>   void evictImage() {
>     final NetworkImage provider = NetworkImage(url);
>     provider.evict().then<void>((bool success) {
>       if (success)
>         debugPrint('removed image!');
>     });
> ```
> 
> This package needs a method like this to clear an image both from the file cache and memory cache.

This doesn't work is, for example, the scale parameter was set (eg scale:4.0) when creating the image widget. 

Is there a reasonable way to clear an image by url (it will totally suck having to worry about the scale parameter when clearing the cache)

**Comment by renefloor** [comment]
Nope, not at the moment

**Comment by francomacri17** [comment]
> Version 2.3 uses ImageProviders more efficiently, so you'll also need to clear the image from the ImageProvider cache. Here is an example of how to do it with NetworkImage, but that should also work for CachedNetworkImage: https://api.flutter.dev/flutter/painting/ImageProvider/evict.html
> 
> ```
>   void evictImage() {
>     final NetworkImage provider = NetworkImage(url);
>     provider.evict().then<void>((bool success) {
>       if (success)
>         debugPrint('removed image!');
>     });
> ```
> 
> This package needs a method like this to clear an image both from the file cache and memory cache.

Thanks man, this aproach work for me!
