### ISSUE TITLE
CERTIFICATE VERIFY FAILED ISSUE IN ANDROID

### ISSUE THREAD

**Issue by SureShDood** [Baseflow/flutter_cached_network_image#448]
## 🐛 Bug Report

**Platform:** 
- [ ] :robot: Android

![2020-08-25 12 26 19](https://user-images.githubusercontent.com/63809582/91142379-4d22d000-e6ce-11ea-90d8-7675cab7ff6b.jpg)

Please let me know, why this issue occurred in android only. image displayed perfectly in iOS. Please help on this asap.

**Comment by danielroek** [comment]
Hi @SureShDood ,

When running `http.get('https://prod_cdn.gumlet.com/images/logo-light.jpg').then((value) => print('test success'), onError: (error) => print('test failed $error'));` it fails. This seems to be an issue outside of CachedNetworkImage, please contact the Dart team @ `https://github.com/dart-lang/http` for more help.
