### ISSUE TITLE
when the image url updated it's image content, widget shows doesn't update 

### ISSUE THREAD

**Issue by jinfagang** [Baseflow/flutter_cached_network_image#450]
how to make it update ?

**Comment by danielroek** [comment]
Hi @jinfagang , 

The DefaultCacheManager manages when the images should be updated. It is possible to override the `DefaultCacheManager`.

You could also clear the cache by calling `DefaultCacheManager().emptyCache();` or clear a single image from the cache by calling `DefaultCacheManager().removeFile(url);`

**Comment by renefloor** [comment]
In addition to @danielroek, the server should give an indication for how long the image is valid, the cache-control header. The image is automatically being updated when it is outdated according to these headers. For more info see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

**Comment by jinfagang** [comment]
@danielroek Thanks. @renefloor Thanks for your solutions.

In my case, I can removeFile after I updated users avatar. then problem solved.

**Comment by hanswimtj** [comment]
**Update 2023.12:** 
`DefaultCacheManager().removeFile(url);` not working for me. Use `await CachedNetworkImage.evictFromCache(url);` instead.
See this: https://stackoverflow.com/a/64581347/4033727
