### ISSUE TITLE
Evict key ImageProvider on failed loading

### ISSUE THREAD

**Issue by lionnner** [Baseflow/flutter_cached_network_image#451]
if load error, should add : PaintingBinding.instance.imageCache.evict(key); the provider will cache in _pendingImages.

**Comment by renefloor** [comment]
What do you mean exactly? Do you have an example of other Image Widgets (such as NetworkImage) where they do this? I'm don't really understand what is the problem and how to solve it.

**Comment by lionnner** [comment]
if you load a net image but it not exist, the provider of it will in _pendingImages, when the net image exist, flutter first use old provider (_pendingImages from the key),  you can see NetworkImage, it has code:
      if (response.statusCode != HttpStatus.ok) {
        // The network may be only temporarily unavailable, or the file will be
        // added on the server later. Avoid having future calls to resolve
        // fail to check the network again.
        PaintingBinding.instance.imageCache.evict(key);
        throw image_provider.NetworkImageLoadException(statusCode: response.statusCode, uri: resolved);
      }

**Comment by renefloor** [comment]
You're right. It is about these lines I guess: https://github.com/flutter/flutter/blob/e8c942104bb4b414b67e303a54b00e8fc45c67a6/packages/flutter/lib/src/painting/_network_image_io.dart#L115-L122

**Comment by lionnner** [comment]
yes, you'd better add a hotfix. thx!

**Comment by Zazo032** [comment]
This is also happening to our app. We're using a GridView with image cards, if one image fails to load because the image doesn't exist, it shows the `errorWidget`. As these cards are generated based on a text field query, if the query changes and the new image exists, it won't load the new one. Logs (url requested + error from `errorWidget`):

```
```

**Comment by Zazo032** [comment]
@renefloor I'm still experiencing this issue in `2.3.2+1`, use case is a `SliverGrid` with `SliverChildBuilderDelegate` that takes a list of images, and upon change (search field clear), card images that failed to load are not re-tried. Logs are similar to the ones I provided earlier:

```
I/flutter (15457): <elided>/pmi.jpg
I/flutter (15457): HttpException: Invalid statusCode: 404, uri = <elided>/hob.jpg
```

These 2 lines are `url` and `error` from `errorWidget` builder. The request is made to a image that exists, but the error is returned from a previous image that doesn't exist.

**Comment by renefloor** [comment]
Sounds more like the image is re-tried but with the old url. This fix was indeed not related to loading a new image with a new url, that already should have worked. 
@Zazo032 did that work with version 2.2? Can you share some example code to show the issue?

**Comment by Zazo032** [comment]
Yes, that works with version 2.2. Also, managed to fix it by adding a `key` parameter to the widget that has the `CachedNetworkImage`. I will try to provide a code sample later.
