### ISSUE TITLE
Custom decoding of image data obtained from the server

### ISSUE THREAD

**Issue by kostasoft** [Baseflow/flutter_cached_network_image#454]
Hello! Thank you so much for the library!
Can you please tell us if there is any way to get in between getting an array of bytes by reference and passing it on for decoding?
This may be necessary, for example, in case of storing an encoded image on a server.
And there is a method of decoding: 
`Future<Uint8List> decodeSha256(Uint8List inputData) {...};`
Can this be done?

PS: And to make it work for WEB as well.

**Comment by renefloor** [comment]
At this moment it is not possible, you can make your own imageprovider while still using the cachemanager.
You can have a look to the ImageProvider code here:https://github.com/Baseflow/flutter_cached_network_image/blob/develop/lib/src/image_provider/_image_provider_io.dart
You'd have to change this part:
```
        if (result is FileInfo) {
          var file = result.file;
          var bytes = await file.readAsBytes();
          var decoded = await decode(bytes);
          yield decoded;
        }
```

If you still want to use placeholder and errorwidgets you can combine with octo_image.

Though I think it would be better in general to decode the image server-side and send it with auth over https, than it is decoded/encoded using web standards.
