### ISSUE TITLE
Cache does not re-try when internet is back

### ISSUE THREAD

**Issue by Sorunome** [Baseflow/flutter_cached_network_image#458]
## 🏗 Enhancement Proposal

Sometimes you might randomly lose internet due to e.g. going through a rural area. If you try to load an image during that time, that, of course, fails. Now, when you have internet again, the image should be downloaded and displayed. Currently you need to restart the app or that to happen, no matter if you generate a new widget with that same URL - it caches somehow that the image was "not found", which is, in this case, undesierable.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS (no ios device to test)
- [x] :robot: Android

**Comment by renefloor** [comment]
@Sorunome I assume it is the same issue as #451, which is fixed in PR #460.
