### ISSUE TITLE
First time fetching image got uncaught error

### ISSUE THREAD

**Issue by aliftaufik** [Baseflow/flutter_cached_network_image#459]
## 🐛 Bug Report

I've got a list of objects that contains an image URL. But some of the objects don't contain the URL (could be a null or empty string), and possibly invalid URL (I just named a few errors that occurred on my project).

```
CachedNetworkImage(
  imageUrl: object.imageUrl // could be null, empty or invalid URL string,
  fit: BoxFit.cover,
  errorWidget: (context, url, error) => Image.asset(
  'assets/default_image.png'),
)
```

The problem is when the URL is invalid, the debugger catches the CachedNetworkImage exception, causing the whole app to pause. Seemed like the error hasn't been handled. But shouldn't it be the CachedNetworkImage responsibility to handle it, which is why there's errorWidget param?

But actually CachedNetworkImage handled it in the next images. So, this is the weirdest part: The uncaught exception only happens at first time (when I do full reload), the subsequent requests of the Image were handled correctly by CachedNetworkImage.

### Expected behavior

I expect CachedNetworkImage to handle those errors (by logging it, for example), and errorWidget should be called immediately.

### Reproduction steps

```
CachedNetworkImage(
  imageUrl: null,
  fit: BoxFit.cover,
  errorWidget: (context, url, error) => Image.asset(
  'assets/default_image.png'),
)
```

The exception caught by my debugger brings me to "_image_provider_io.dart" file on this line:

```
Stream<ui.Codec> _loadAsync(
    CachedNetworkImageProvider key,
    StreamController<ImageChunkEvent> chunkEvents,
    DecoderCallback decode,
  ) async* {
    assert(key == this);
    try {
      var mngr = cacheManager ?? DefaultCacheManager();
      await for (var result in mngr.getFileStream(key.url,
          withProgress: true, headers: headers)) {
        if (result is DownloadProgress) {
          chunkEvents.add(ImageChunkEvent(
            cumulativeBytesLoaded: result.downloaded,
            expectedTotalBytes: result.totalSize,
          ));
        }
        if (result is FileInfo) {
          var file = result.file;
          var bytes = await file.readAsBytes();
          var decoded = await decode(bytes);
          yield decoded;
        }
      }
    } catch (e) {
      errorListener?.call();
      rethrow; // This is where the app stops
    } finally {
      await chunkEvents.close();
    }
  }
```

### Configuration

**Version:** 2.3.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
Hi @aliftaufik. The exception is handled by the image widget, but that the debugger stops is an issue from the Dart VM. The Dart VM doesn't always know whether an exception is caught or not. You can read more about it here: https://github.com/flutter/flutter/issues/33427#issuecomment-504529413

**Comment by aliftaufik** [comment]
So what should I do to handle this case? Should I just turn off the debugger on my IDE? Is it okay to just let it be since it's just the debugger doesn't know the exception had been handled?

**Comment by renefloor** [comment]
If it is annoying you can disable Dart Exception Breakpoints:
![image](https://user-images.githubusercontent.com/15101411/92449943-11523500-f1bb-11ea-9069-3b15d02ffdcf.png)

You get here easily by right-click on a breakpoint and go to 'more'
![image](https://user-images.githubusercontent.com/15101411/92450020-2dee6d00-f1bb-11ea-9df7-6f8e3e90af9e.png)
