### ISSUE TITLE
Improve pub.dev listing

### ISSUE THREAD

**Issue by Zazo032** [Baseflow/flutter_cached_network_image#463]
### Pitch

Currently, if you search `cached_network_image` on pub.dev with `Flutter` filter active, this plugin will not show up because it's not correctly labeled.
![image](https://user-images.githubusercontent.com/2807712/92714421-7f822d80-f35c-11ea-9f2e-fafef177165e.png)
![image](https://user-images.githubusercontent.com/2807712/92714451-86a93b80-f35c-11ea-8d45-84da460fbc32.png)

Also, pub.dev score reports some issues with the plugin:

![image](https://user-images.githubusercontent.com/2807712/92714659-c53ef600-f35c-11ea-9d56-58cc38c66b21.png)
![image](https://user-images.githubusercontent.com/2807712/92714720-d7b92f80-f35c-11ea-81c7-e2ea53da494f.png)
![image](https://user-images.githubusercontent.com/2807712/92714775-ebfd2c80-f35c-11ea-86f5-46c8c65073d6.png)

**Comment by renefloor** [comment]
I assume the listing is mainly broken because of `ui.webOnlyInstantiateImageCodecFromUrl`, however we need this for web.
If you know how to improve the listing that would be nice.

**Comment by Zazo032** [comment]
That one may be blocked by https://github.com/flutter/flutter/issues/52899

**Comment by renefloor** [comment]
Good find. I upvoted the issue.

**Comment by renefloor** [comment]
PR #464 didn't help in fixing the webOnly method, the analyser ignores the ignores.

![image](https://user-images.githubusercontent.com/15101411/92736297-6e481980-f37a-11ea-9ff0-411de64fbaf8.png)


Pedantic 1.9.2 is not (yet) compatible with Flutter stable.
```\The current Dart SDK version is 2.9.0.

Because every version of flutter_test from sdk depends on meta 1.1.8 and pedantic >=1.9.2 <1.10.0-nullsafety depends on meta ^1.2.2, flutter_test from sdk is incompatible with pedantic >=1.9.2 <1.10.0-nullsafety.
And because pedantic >=1.10.0-nullsafety requires SDK version >=2.10.0-0 <2.10.0, flutter_test from sdk is incompatible with pedantic >=1.9.2.
So, because cached_network_image depends on both flutter_test any from sdk and pedantic ^1.9.2, version solving failed.
```

commit 18485f5741181a5bd2ed785f670229ba222fe137 downgrades to 1.9.0

**Comment by Zazo032** [comment]
Hmmmm maybe you can open an issue on pub repo to check if there's any workaround for the 2 missing errors (analysis + supported platforms), or the team can provide some further guidance to improve score

**Comment by aragonet** [comment]
Any updates on this?
