### ISSUE TITLE
Images are not loaded when 400 status is returned

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [Baseflow/flutter_cached_network_image#470]
Hi,

I am on latest flutter_cached_network_image and flutter. I see this issues for a very long time maybe it is time to fix it?
Just pointing to older discussion
https://github.com/Baseflow/flutter_cached_network_image/issues/273

How we can release our apps with such bug? :(

CacheManager: Failed to download file from https://s3.amazonaws.com/uifaces/faces/twitter/hugocornejo/128.jpg with error:
I/flutter (11066): HttpException: Invalid statusCode: 400, uri = https://s3.amazonaws.com/uifaces/faces/twitter/hugocornejo/128.jpg

You can check an url it works. 
It also works on my emulator but not on device. not on Android not on iOS

**Comment by vytautas-pranskunas-** [comment]
But I noticed that this issue was gone for some time until I have updated to latest flutter version. I will try to downgrade in upcoming days to check.

**Comment by vytautas-pranskunas-** [comment]
No, Flutter downgrade did not help. Same issue
Guys are you planning to fix it? People are havily depended on this - i Cannot release my app

**Comment by vytautas-pranskunas-** [comment]
I found an issue. For me it was that i was sending Beare header to s3 and it was deying it. So i added condition that for auth headers would not be sent to external urls.

**Comment by jeancarlos2020** [comment]
String tipo = ContentType.parse(res.headers['content-type']).primaryType;
    if (tipo == 'image') {

    }

**Comment by Yannx237** [comment]
broo please i have the same issues
