### ISSUE TITLE
FileSystemException: Cannot copy file to .... OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by pojoba02** [Baseflow/flutter_cached_network_image#471]
## 🐛 Bug Report

Getting this error after iOS 14 upgrade from iOS 13, everything was running smooth and perfect.

flutter: FileSystemException: Cannot copy file to '/Users/selorm/Library/Developer/CoreSimulator/Devices/4E0B4516-276C-
4F49-8D34-ECAE363FA4FF/data/Containers/Data/Application/5D97F93A-31C2-489B-9639-FCB8D1C7F6EB/Library/Caches/mediaCache/68f8efd1-8e36-4a4e-aa72-9b1c2188d24bversion=1&uuid=CC95F08C-88C3-4012-9D6D-64A413D254B3&mode=compatible.jpeg', path = '/Users/selorm/Library/Developer/CoreSimulator/Devices/4E0B4516-276C-4F49-8D34-ECAE363FA4FF/data/Containers/Shared/AppGroup/43C0F4B4-63CB-4400-B51A-A29734BA5F0E/File Provider Storage/photospicker/version=1&uuid=CC95F08C-88C3-4012-9D6D-64A413D254B3&mode=compatible.jpeg' (OS Error: No such file or directory, errno = 2)

Code
```
final tempPath = await _getTempPath();
    final String mediaUuid = _uuid.v4();
    String mediaExtension = basename(media.file.path);
    var copiedFile = media.file.copySync('$tempPath/$mediaUuid$mediaExtension');
```

### Version:
cached_network_image: ^2.3.2+1

**Platform:** 
- [🟢 ] :iphone: iOS
- [ ] :robot: Android

**Comment by renefloor** [comment]
What are you doing here? This isn't just showing the image right? Does the 'media' come from the cache manager?
