### ISSUE TITLE
HandshakeExceptionrelated to ImageProvider

### ISSUE THREAD

**Issue by joknjokn** [Baseflow/flutter_cached_network_image#472]
## 🐛 Bug Report

Lately I have seen many HandshakeExceptions in Crashlytics. I primarily use cached_network_image for images (firebase storage), so I suspect it's related to this plugin. It has happened for at least the devices Huawei P10 and Mate 10 Lite, Xiaomi 9t Pro and several older and new iPhone models.

The only content in the StackTrace in Crashlytics:
`Non-fatal Exception: java.lang.Exception: HandshakeException: Connection terminated during handshake`

And log attached to the error report:
`D/CrashlyticsCore Instance of 'DiagnosticsProperty<ImageProvider<dynamic>>'`

I am not sure how this error is experienced by the user, and I have no clue about the cause or how to reproduce it.

**Version:** 2.3.1

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
I don't think I can really help you without more information. Looks like just the http.get call fails because of some ssl error. It isn't really caused by this library per se.

**Comment by vishalpatel1327** [comment]
@renefloor  yes u r right brother, but I think it should be handled from the error widget.
because that affected firebase crash reports.

```
CachedNetworkImage(
                          placeholder: (context, url) => loadingIndicator(),
                          imageUrl: imgUrl,
                          errorWidget: (context, url, error) =>
                              Icon(Icons.error),
                        ))
```

in my cash when the user put an app into the background having that kind of report
![image](https://user-images.githubusercontent.com/14329287/201276795-bbd1725b-429d-4579-afc7-0a4f9c6f6d56.png)

**Comment by abdalazeezalyosfi** [comment]
same here 
@joknjokn can you please reopen it ?
its happen in ios and cause crash if you keep on same page for 5 minutes then go will throw crash
