### ISSUE TITLE
Support for Flutter Desktop/Windows

### ISSUE THREAD

**Issue by andrebadini** [Baseflow/flutter_cached_network_image#476]
### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ X ] :desktop: Windows

**Comment by renefloor** [comment]
You are lucky, last week we released an update of the CacheManager, which is compatible with Windows and Linux.
You can already try it by overriding the depedency as it is fully compatible with the latest version of CachedNetworkImage:
```
dependency_overrides:
  flutter_cache_manager: ^2.0.0-beta
```
