### ISSUE TITLE
Facing issue due to sqflite

### ISSUE THREAD

**Issue by pradeepkarth** [Baseflow/flutter_cached_network_image#479]
I am facing this issue recently. If i comment cached_network_image related codes, the project gets builded otherwise it throws this error. 

Launching lib/main.dart on Redmi Note 7S in debug mode...
Running Gradle task 'assembleDebug'...
../../software/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.1+1/lib/src/factory_impl.dart:70:39: Error: Type 'SqfliteDatabaseFactoryMixin' not found.
class SqfliteDatabaseFactoryImpl with SqfliteDatabaseFactoryMixin {
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../software/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.1+1/lib/src/factory_impl.dart:70:7: Error: The type 'SqfliteDatabaseFactoryMixin' can't be mixed in.
class SqfliteDatabaseFactoryImpl with SqfliteDatabaseFactoryMixin {
      ^
../../software/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.1+1/lib/src/factory_impl.dart:51:76: Error: A value of type 'SqfliteDatabaseFactoryImpl' can't be assigned to a variable of type 'SqfliteDatabaseFactory'.
 - 'SqfliteDatabaseFactoryImpl' is from 'package:sqflite/src/factory_impl.dart' ('../../software/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.1+1/lib/src/factory_impl.dart').
 - 'SqfliteDatabaseFactory' is from 'package:sqflite_common/src/factory.dart' ('../../software/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite_common-1.0.2+1/lib/src/factory.dart').
SqfliteDatabaseFactory get sqlfliteDatabaseFactory => _databaseFactory ??= SqfliteDatabaseFactoryImpl();
                                                                           ^
../../software/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.1+1/lib/src/factory_impl.dart:63:75: Error: A value of type 'SqfliteDatabaseFactoryImpl' can't be assigned to a variable of type 'SqfliteDatabaseFactory'.
 - 'SqfliteDatabaseFactoryImpl' is from 'package:sqflite/src/factory_impl.dart' ('../../software/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.1+1/lib/src/factory_impl.dart').
 - 'SqfliteDatabaseFactory' is from 'package:sqflite_common/src/factory.dart' ('../../software/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite_common-1.0.2+1/lib/src/factory.dart').
SqfliteDatabaseFactory get sqfliteDatabaseFactory => _databaseFactory ??= SqfliteDatabaseFactoryImpl();
                                                                          ^
../../software/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.1+1/lib/src/factory_impl.dart:95:18: Error: The method 'fixPath' isn't defined for the class 'SqfliteDatabaseFactoryImpl'.
 - 'SqfliteDatabaseFactoryImpl' is from 'package:sqflite/src/factory_impl.dart' ('../../software/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.1+1/lib/src/factory_impl.dart').
Try correcting the name to the name of an existing method, or defining a method named 'fixPath'.
    path = await fixPath(path);
                 ^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script '---/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command ---/Desktop/software/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by renefloor** [comment]
Maybe something is outdated? 

Can you try
```
flutter upgrade
flutter clean
flutter pub upgrade
```

**Comment by safety-dispatch** [comment]
> Maybe something is outdated?
> 
> Can you try
> 
> ```
> flutter upgrade
> flutter clean
> flutter pub upgrade
> ```

^^this worked^^ Was having the same issue. I think it was due to some of its dependencies needing to upgrade
