### ISSUE TITLE
Can not build android aar

### ISSUE THREAD

**Issue by xiaofanqingzjj** [Baseflow/flutter_cached_network_image#480]
版本：2.2.0
使用集成到现有的app的方式集成Flutter。

当我引入cached_network_image 运行flutter build aar的时候会报如下的错误：
`
* Where:
Initialization script '/Users/my/dev/flutter/packages/flutter_tools/gradle/aar_init_script.gradle' line: 20

* What went wrong:
Android property not found. 
`
我找到flutter sdk对应的代码查看：

`
...
void configureProject(Project project, String outputDir) {
    if (!project.hasProperty("android")) {
        throw new GradleException("Android property not found. ")
    }
...
`

然后我在这里添加了一个打印工程路径的代码：

`
void configureProject(Project project, String outputDir) {
    if (!project.hasProperty("android")) {
        throw new GradleException("Android property not found. Project:${project.toString()}")
    }
...
`

重新运行flutter build aar后的错误：

`
* Where:
Initialization script '/Users/xiaofanqing/dev/flutter/packages/flutter_tools/gradle/aar_init_script.gradle' line: 20

* What went wrong:
Android property not found. Project:project ':path_provider_linux'
`

然后我在.pub_cache里找到对应的包手动删掉，然后编译就通不过了。

 请问这是什么问题？

**Comment by renefloor** [comment]
Sorry, I can't really help you this way. Did you try to clean? You can also try to run ./gradlew clean in the android folder of your project.

**Comment by xiaofanqingzjj** [comment]
> Sorry, I can't really help you this way. Did you try to clean? You can also try to run ./gradlew clean in the android folder of your project.

Thank you. I changed the version of Flutter without this error. I think it's a bug in that version of the flutter.

**Comment by CentForever** [comment]
> > Sorry, I can't really help you this way. Did you try to clean? You can also try to run ./gradlew clean in the android folder of your project.
> 
> Thank you. I changed the version of Flutter without this error. I think it's a bug in that version of the flutter.

the version of Flutter is >???
