### ISSUE TITLE
CachedNetworkImageProvider and a placeholder

### ISSUE THREAD

**Issue by giacomok** [Baseflow/flutter_cached_network_image#482]
## 🚀 Feature Requests

I need to use an ImageProvider with a placeholder and an errorwidget.  
I can not use CachedNetworkImageProvider cause it does not have these 2 features. Is there a way to use it?

**Comment by aliftaufik** [comment]
```
CachedNetworkImage(
  imageUrl: "http://via.placeholder.com/350x150",
  placeholder: (context, url) => CircularProgressIndicator(),
  errorWidget: (context, url, error) => Icon(Icons.error),
),
```

I took it from the official documentation on pub.dev. So, which features that it doesn't have?

**Comment by renefloor** [comment]
@giacomok an imageprovider is not a widget, but really what it name says, it is meant to provide an image. The imageprovider does have callbacks about loading and errors so image widgets can do whatever they want with that. Why do you need the imageprovider to have a placeholder? What is the CachedNetworkImage widget missing that you want?

**Comment by giacomok** [comment]
This is the code I have:

    Container(
      height: 150.0,
      decoration:
          BoxDecoration(
              image:
                  DecorationImage(
        fit: BoxFit
                .fitWidth,
        alignment:
            FractionalOffset
                .center,
        image: CachedNetworkImageProvider(item.cover_photo),
      ))

`image` attribute must be a provider, but sometimes `item.cover_photo` returns a 404 error, so I need to handle that with an error image.

**Comment by renefloor** [comment]
You'd need to do that the other way around:
```
CachedNetworkImage(
  imageUrl: item.cover_photo,
  imageBuilder: (context, imageProvider) => Container(
    height: 150.0,
    decoration:
      BoxDecoration(
          image:
              DecorationImage(
                  fit: BoxFit.fitWidth,
                  alignment:  FractionalOffset.center,
                  image: imageProvider,
  )),
  errorWidget: (context, url, error) => Container(height: 150.0, child: Icon(Icons.error),),
),
```

**Comment by benPesso** [comment]
> The imageprovider does have callbacks about loading and errors

@renefloor Where do you see a callback for loading updates? The signature shows only an `errorListener`:

```dart
CachedNetworkImageProvider CachedNetworkImageProvider(
  String url, {
  double scale,
  void Function() errorListener,
  Map<String,
  String> headers,
  BaseCacheManager cacheManager,
  ImageRenderMethodForWeb imageRenderMethodForWeb,
})
```

**Comment by benPesso** [comment]
> The imageprovider does have callbacks about loading and errors

@renefloor While the `ImageProvider` has the ability to add such listers, the `CachedNetworkImageProvider` does not. (It only exposes an `errorListener`, but not a loading-status listener.)

To add a listener, you'd have to take the returned `CachedNetworkImageProvider` and then `resolve()` and `addListener()` to it, which is not straightforward or obvious to developers expecting this package to "handle it for them".

**Comment by renefloor** [comment]
But the image widget is responsible for loading the image from the imageprovider and is the one listening to the result stream: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/image.dart#L1167

What is the use case that you want to directly do this on the imageprovider?

**Comment by benPesso** [comment]
The image widget is responsible for _displaying_ the image. Not loading it.

What most developers want is to prepare the UI beforehand, and then display it when the image is ready for display. So for example: you may want to lay out a profile page with an avatar image, but you want to show place-holding content while the image is loading. For this, you'd need to have an external event dispatcher to "sync" everything. Which is where the need for the loading state listener comes from.

(I'm just advocating here, to be clear, so my points may be offbase from what @giacomok is actually saying.)

**Comment by renefloor** [comment]
For that Flutter has a precacheImage function. I'd see we could extend that so it also gives progress
https://api.flutter.dev/flutter/widgets/precacheImage.html

**Comment by renefloor** [comment]
I'm not sure what you mean.

> you may want to lay out a profile page with an avatar image, but you want to show place-holding content while the image is loading

You can do that with just CachedNetworkImage right? You can add a placeholder in that.
You can also use the imageFrameBuilder of the default [Image](https://api.flutter.dev/flutter/widgets/Image/Image.html) widget.

> a developer may not want to show a partial widget until all data is available

In this case you can use precacheImage right? 
For example if you only want to show a widget when 3 images and some other data are loaded, you can do:

```
await Future.wait([
    precacheImage(image1, context),
    precacheImage(image2, context),
    precacheImage(image3, context),
    loadTextData(),
]);
setState(() => loaded = true);
```

If you don't know yet what the image url will be that you just create a full placeholder widget.

In my opinion, the (image) widget is responsible for **when** to load an image and the imageprovider is responsible for **how**.
For example the imageprovider has no idea whether the image widget is on screen, or very low in a list.

**Comment by kamleshwebtech** [comment]
Is there any solution of this problem?

**Comment by aliftaufik** [comment]
I think the doc already answered the problem, about the placeholder and the errorwidget. And @renefloor already mentioned about doing it the other way around. That should solve the problem.

**Comment by piyushyadav4904** [comment]
you can wrap the cachednetworkimageprovider with photoview and using the function errorbuilder and loadingbuilder it will help in my case

**Comment by OpenJarvisAI** [comment]
Am afraid only widget hanldes error it not a flexiable way. For example ,when used in Container backgroundImage, it just doens fit all the time. Not flexiable dude.
Please try listen developers voice, just add error handling such as return a placeholder image Url to handle it....
