### ISSUE TITLE
Storing local images in the cache directory

### ISSUE THREAD

**Issue by afnx** [Baseflow/flutter_cached_network_image#483]
## 🚀 Feature Requests

I'm using this package to show images from the internet, but sometimes need to show an image that I uploaded from the same device. Since the image is already stored in the temp directory of that device, it's unnecessary to download and cache it again. I'm looking for a way to manually move it to the cache directory of CachedNetworkImage and display it by using its download url just like it's downloaded from the internet.

Therefore, even if the cache is cleared, the image still can be downloaded from the server with the download url and no data usage will be wasted in the beginning.

Can this nice package have such a feature like this?

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
Yes, there are 2 methods to put an existing file in the cache.
https://pub.dev/documentation/flutter_cache_manager/latest/flutter_cache_manager/CacheManager/putFile.html
https://pub.dev/documentation/flutter_cache_manager/latest/flutter_cache_manager/CacheManager/putFileStream.html

The first expect bytes, the second a byte stream. The stream is better if you already have a file.
You can set the validity and if the file is no longer valid or removed it is being downloaded again.

**Comment by Muhammed-Ayad** [comment]
How can i change relativePath ?
@renefloor
