### ISSUE TITLE
Manage dynamic url

### ISSUE THREAD

**Issue by huanghui1998hhh** [Baseflow/flutter_cached_network_image#486]
## 🚀 Feature Requests

My image URL is dynamic,if i wanna use the image stored on the server,i need use a signature method to the image storage path first,then i can get the image URL.So in this case, how to cache the image?

**Comment by renefloor** [comment]
The work for that is done in the cache_manager, it just needs to be used in the image widget and is tracked with #265
The idea is that you can use a key to get an image from the cache, separate from the url. You could also extend the FileFetcherService in the cache manager.
