### ISSUE TITLE
FadeWidget is rendered every time

### ISSUE THREAD

**Issue by hvasc** [Baseflow/flutter_cached_network_image#488]
## 💬 Questions and Help

HI, my image url is dynamic for security.

so I using custom CacheManager for using [custom cache key](https://github.com/Baseflow/flutter_cache_manager/pull/179) excluded auth parameter.

this is very good. but OctoImage rendered every time FadeWidget(when resume, scrolled..).

so what's wrong? CachedNetworkImage using static url, just once fadein.

OctoImage has check key and url? Please tell me if I have more work to do.

**Comment by renefloor** [comment]
What's your code? I don't really understand how you use the custom cache key with CachedNetworkImage at this moment.

**Comment by hvasc** [comment]
> What's your code? I don't really understand how you use the custom cache key with CachedNetworkImage at this moment.

Hi, I override CacheManager and using key parameter. here is my code

```dart
import 'package:flutter_cache_manager/flutter_cache_manager.dart';

class CustomKeyCacheManager extends CacheManager {
  static const key = 'libCachedImageData';

  static CustomKeyCacheManager _instance;
  factory CustomKeyCacheManager() {
    _instance ??= CustomKeyCacheManager._();
    return _instance;
  }

  CustomKeyCacheManager._() : super(Config(key));

  @override
  Stream<FileResponse> getFileStream(String url, {String key, Map<String, String> headers, bool withProgress}) {
    return super.getFileStream(url, key: url.split('?')[0], headers: headers, withProgress: withProgress);
  }
}

```

then using this code.

```dart
CachedNetworkImage(imageUrl: url, cacheManager: CustomKeyCacheManager());
```

using key from getFileStream method none parameter url.
cuz using CachedNetworkImage in DefaultCacheManager has using getFileStream method.
so my CustomKeyCacheManager has cached from key in CachedNetworkImageProvider get cacheObject.
what's wrong?

**Comment by renefloor** [comment]
The image provider has a check whether or not it is the same that is based on URL. So the image is fetched again from the cachemanager every time the image is loaded if the url changes:

https://github.com/Baseflow/flutter_cached_network_image/blob/develop/lib/src/image_provider/_image_provider_io.dart#L110

**Comment by hvasc** [comment]
> The image provider has a check whether or not it is the same that is based on URL. So the image is fetched again from the cachemanager every time the image is loaded if the url changes:
> 
> https://github.com/Baseflow/flutter_cached_network_image/blob/develop/lib/src/image_provider/_image_provider_io.dart#L110

thank you very much!

**Comment by hvasc** [comment]
> The image provider has a check whether or not it is the same that is based on URL. So the image is fetched again from the cachemanager every time the image is loaded if the url changes:
> 
> https://github.com/Baseflow/flutter_cached_network_image/blob/develop/lib/src/image_provider/_image_provider_io.dart#L110

one more question. can I override this operator? looks CachedNetworkImage constructor is imposible
