### ISSUE TITLE
Invalid Image Data

### ISSUE THREAD

**Issue by chinkysight** [Baseflow/flutter_cached_network_image#491]
## 💬 Questions and Help

I don't know why but I am getting `Invalid Image Data` using this package which is an runtime error and it doesn't crash my app but it does pause my app while running on emulator using VSCODE.

**Comment by renefloor** [comment]
What's the url? I'd guess the image from the url is not really an image.

**Comment by chinkysight** [comment]
> What's the url? I'd guess the image from the url is not really an image.

The fun part that, when I press the continue button on VSCODE when my app pause due to the exception, the images shows up

**Comment by renefloor** [comment]
Maybe the placeholder is incorrect?

**Comment by chinkysight** [comment]
> Maybe the placeholder is incorrect?

I am a circular progress bar as a placeholder widget and its working perfectly fine. The link that I had used is https://covers.feedbooks.net/book/6632.jpg?size=large

**Comment by chinkysight** [comment]
The package is doing it work but the problem is that I am getting that Exception, even still it does not crashes my app but still why I am a getting an exception which does noting XDXD

**Comment by chinkysight** [comment]
And the fun fact is that, I am not getting this exception when using Android Studio

**Comment by renefloor** [comment]
I don't know where the image is coming from. Do you have a bit more logging? Which place does this exception throw?

**Comment by chinkysight** [comment]
> I don't know where the image is coming from. Do you have a bit more logging? Which place does this exception throw?

![Screenshot from 2020-11-07 10-13-12](https://user-images.githubusercontent.com/53231016/98431946-0005a600-20e2-11eb-9102-4f5fb5f17e10.png)

I repeat this exception does not crashes my app and when I run the project using Android Studio, I am not getting this exception. I am getting image from an Api response, to be exact I am getting the image from this link: https://covers.feedbooks.net/book/6632.jpg?size=large

**Comment by briankariuki** [comment]
I'm getting this error when loading webp images

**Comment by briankariuki** [comment]
```  CachedNetworkImage(
                  imageUrl:
                      "https://fantasy.premierleague.com/dist/img/shirts/standard/shirt_8-66.webp",
                  height: 30,
                  fit: BoxFit.cover,
                  errorWidget: (context, url, error) => CachedNetworkImage(
                    imageUrl:
                        "https://platform-static-files.s3.amazonaws.com/premierleague/photos/players/250x250/Photo-Missing.png",
                  ),
                ),```

**Comment by briankariuki** [comment]
You can reproduce the issue using the above code snippet, i'm using flutter 1.22.3 stable

**Comment by carman247** [comment]
I'm also getting this ... I have to disable breaking on "Uncaught Exceptions" because is a nightmare to develop/debug with the constant pauses

**Comment by ibrahim-demirci** [comment]
I got 'Invalid image' error in Flutter. And i select Carto in Mapkit Style it fixed.
![image](https://user-images.githubusercontent.com/75900229/115869216-3e9bdc80-a446-11eb-815a-620abd5095af.png)

**Comment by renefloor** [comment]
@briankariuki and @chinkysight I tried your examples with cachednetworkimage version 3.0.0 and the latest flutter stable and had no problems. If you still have this problem please reopen the issue.

**Comment by Nazarii77** [comment]
> 
> 
> @briankariuki and @chinkysight I tried your examples with cachednetworkimage version 3.0.0 and the latest flutter stable and had no problems. If you still have this problem please reopen the issue.

I am able to reproduce with the version 3.0.1:

If the image url was broken yesterday, and currently it is 100% working, the cached_network_image for some reason does not check the URL but assumes it  was broken == it is broken and paints errorWidget

**Comment by Nazarii77** [comment]
So how I fixed this issue: 
I simply clean cache on the refresh as this package CACHES broken image data, for example server was down and the image was not possible to get = package caches that error :(
 
DefaultCacheManager().emptyCache();

**Comment by Nazarii77** [comment]
Or event better way: 1.get from cache 2 if cached error - trying from online if online still responds with error - showing custom error  

  CachedNetworkImage(
               imageUrl: "www.google.com/image1",
               fit: BoxFit.cover,
               errorWidget: (context, url, error) =>
                   Image.network(url, fit: BoxFit.cover,
                       errorBuilder: (BuildContext context,
                           Object exception,
                           StackTrace? stackTrace) {
                         return Image(
                             image: AssetImage(
                                 "assets/images/no-photo.png"),
                             fit: BoxFit.cover);
                       })
               ),

P.S. that was expected to work out of the box that way

**Comment by rvvarasdiya** [comment]
Does anyone have the same issue now?

I can't be able to load this link on the cached widget but it works on` SVGPicture.network`

https://images.ctfassets.net/06cjgnb3y4oq/3rr2ufUhjoQulMpgkt7ViE/4bdad1961fd1d85565be40cb71f57938/user.svg

**Comment by romreed** [comment]
i have same issue!

**Comment by submetu** [comment]
Me too!

**Comment by ArefkhattabGit** [comment]
me to

**Comment by cnrblm** [comment]
same here

**Comment by Abolfazl-MI** [comment]
same here

**Comment by zhuwei** [comment]
Me too!

**Comment by yigtkaya** [comment]
Still the same going to try this :( 

> Or event better way: 1.get from cache 2 if cached error - trying from online if online still responds with error - showing custom error
> 
> CachedNetworkImage( imageUrl: "www.google.com/image1", fit: BoxFit.cover, errorWidget: (context, url, error) => Image.network(url, fit: BoxFit.cover, errorBuilder: (BuildContext context, Object exception, StackTrace? stackTrace) { return Image( image: AssetImage( "assets/images/no-photo.png"), fit: BoxFit.cover); }) ),
> 
> P.S. that was expected to work out of the box that way
