### ISSUE TITLE
Does this plugin uses sqflite for image caching

### ISSUE THREAD

**Issue by luis901101** [Baseflow/flutter_cached_network_image#498]
I have not had time to review the code of this plugin to know exactly where the **sqflite** dependency is used, but I assume that it must be in relation to the cache of the images ... maybe not to save the image itself, but to save some reference to the image in storage where the image is finally left. I've been using this plugin for a while now and it seems great to me, but lately I've been experiencing issues with the iOS build and transitive dependency on **sqflite** [Issue 496](https://github.com/Baseflow/flutter_cached_network_image/issues/496).
So my question, why use **sqflite** instead of [hive](https://pub.dev/packages/hive) which according to benchmarks outperforms **sqflite** and also does not require **native dependencies**???

**Comment by chcarmen** [comment]
As i remember, there is corresponding database files in data/data/<app-name>/files directory.

**Comment by renefloor** [comment]
Yes it uses sqflite for caching the information. For windows and linux it uses a variant without sqflite. In some time that will also be the default for the other platforms, but you can already use it if you want.

You can customize the CacheManager and use the JsonCacheInfoRepository: https://github.com/Baseflow/flutter_cache_manager#customize
