### ISSUE TITLE
FileSystemException: Cannot open file, path = 

### ISSUE THREAD

**Issue by tree1891** [Baseflow/flutter_cached_network_image#501]
```
I/flutter ( 5692): CacheManager: Failed to download file from https://storage.googleapis.com/squarefit-2020.appspot.com/profile/SCkTsMnJ843PLB3VQ3bD/image_picker376659318.jpg?GoogleAccessId=firebase-adminsdk-g31bl%40squarefit-2020.iam.gserviceaccount.com&Expires=1896134400&Signature=QjE%2Bhny3TTZ5nSzn15Hro4CUVX%2F2CFQb6ncmU8NrkcOdGxRSRT5oDZTU37ChjAWUFDx7KnFworsP081vp%2Bs%2BTXp%2BeMS%2F5sviInkbat%2BV%2BEGrvoy6FmZJ0SbKEp2tdsdklPnqU3gGiihWy9ACGjriKyfnbTWFDzJK2u272BinZ69bEPA%2BlSw%2B%2FBDD0FhB74oIx%2Boo7N%2FP6JbdJFYS5LujlZ3nVGXCxJRelEbB8H8XwWzKCjDXHjS41EeI%2FkD%2F1hZw1Bl0ng1q9X5sE6sDoZMWwIbGbdU45WBBTKQBOFA3K4y4NjyxEM%2F1aoYwLn9V7vqtP6ZnjI3QlxOhYkpNcVXaLQ%3D%3D with error:
I/flutter ( 5692): FileSystemException: Cannot open file, path = '/data/data/com.app.name/cache/libCachedImageData/de4a4130-2503-11eb-aab3-01f0424a6cef.image/png' (OS Error: No such file or directory, errno = 2)
```

cached_network_image: ^2.3.3

**Comment by chcarmen** [comment]
I also encounter the same exception after clearing local cache directory(getTemporaryDirectory() returned value).

 it supposes to redownload the image file from url when file is not available any more, so why cache network image still try to access to the local disk file?

**Comment by renefloor** [comment]
`de4a4130-2503-11eb-aab3-01f0424a6cef.image/png` is a weird file name. It could go wrong there.

I tried your url in postman, and got indeed a weird content-type: `image/image/png`. It parses 'image' as main-type and 'image/png' as subtype and uses that as extension (as it doesn't recognize this subtype).

Do you know why it gives this weird content-type?

**Comment by tree1891** [comment]
The image is on firebase store.
