### ISSUE TITLE
The UI become unresponsive when image is downloading

### ISSUE THREAD

**Issue by y0unghe** [Baseflow/flutter_cached_network_image#508]
## 🐛 Bug Report

I have a ListView, and its child contains a CachedNetworkImage, when the image is downloaded at the first time, the UI become unresponsive, can't scroll up and down. After the image is downloaded and appear, the UI become responsive.

### Expected behavior
CachedNetworkImage should not block UI thread.

### Reproduction steps
Add CachedNetworkImage to ListView

**Version:** 
2.3.3

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by dgilperez** [comment]
I saw this as well just randomly, could not reproduce again. The difference in my case was that this lead to a crash (probably after the network request timed-out?)

**Comment by renefloor** [comment]
I also have this on Android, weird thing is that only the scrolling seems to be blocked. I am able to click on the list items and interact with other UI elements in the app.

**Comment by renefloor** [comment]
@y0unghe I just switched to Flutter Stable and the bug is gone, so I guess it is a bug in the Flutter framework. Can you verify that you are not on stable?

**Comment by dgilperez** [comment]
Our app runs on 1.22.4 (current stable) app and I saw it happening last week, on stable. I can't reproduce though :(

**Comment by martin-braun** [comment]
I recently upgraded a Flutter 2 project to Flutter 3 which uses the CachedNetworkImage package. Old version was `3.2.0` on Flutter `2.10.5`. After porting I'm using version `3.2.3` on Flutter `3.10.5`.

The app uses heavy amounts of `CachedNetworkImage` instances and I have the very same issue:

![PXL_20230712_202301184](https://github.com/Baseflow/flutter_cached_network_image/assets/24259245/5e30401d-22f2-4e71-877e-f016fef5d966)

I can't scroll and the UI becomes unresponsive. I can't click on item as well.

I think it can be reproduced with a low spec device and slow internet connection and many `CachedNetworkImage`s in the view.

@renefloor, could you please re-open this issue?

**Comment by martin-braun** [comment]
Update: I found a solution. It seems the `safe_device` package collides with `cached_network_image`. I removed `safe_device` and now everything works again.
