### ISSUE TITLE
Flickering before fade out transition from placeholder to actual image starts

### ISSUE THREAD

**Issue by blaueeiner** [Baseflow/flutter_cached_network_image#515]
## 🐛 Bug Report

I am using [flutter_blurhash](https://pub.dev/packages/flutter_blurhash) combined with flutter_cached_network_image and the code looks like the following:

```dart
CachedNetworkImage(
        imageUrl: image.url,
        placeholder: (context, url) {
          final blurHash = image.blurHash;

          if (blurHash != null) {
            return BlurHash(
              hash: blurHash,
              imageFit: fit,
              color: Colors.transparent,
            );
          } else {
            return Container();
          }
        },
        fit: fit,
        alignment: alignment,
      );
```

The problem I am facing is that once the image loaded and the transition from the placeholder to the actual image begins, there is a strange brief flicker before the placeholder starts fading out. 

I read a few other issues for this package that mention the same problem, but most of them were closed as if they would have been already fixed, but I am facing the problem even on the newest version of the package.

### Configuration

**Version:** 2.4.1

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by animalnots** [comment]
Same issue, can this be looked into, please? Using  cached_network_image: ^2.3.3

**Comment by renefloor** [comment]
I think it is because the placeholder is rebuild and the Blurhash is empty for 1 frame when the widget rebuilds. Maybe you can pull that out of the widget like this (I didn't test if it really helps):
```
final blurhashWidget = BlurHash(
              hash: image.blurHash,
              imageFit: fit,
              color: Colors.transparent,
            );
CachedNetworkImage(
        imageUrl: image.url,
        placeholder: (context, url) {
          final blurHash = image.blurHash;

          if (blurHash != null) {
            return blurhashWidget
          } else {
            return Container();
          }
        },
        fit: fit,
        alignment: alignment,
      );
```

**Comment by blaueeiner** [comment]
@renefloor @animalnots Indeed the problem was related to the blur hash widget, but the suggested solution unfortunately did not work. I found a workaround that looks like the following. Works like a charm 👌

``` dart
 Stack(
        children: [
          if (blurHash != null)
            Align(
              alignment: alignment,
              child: BlurHash(
                hash: blurHash,
                imageFit: fit,
                color: Colors.transparent,
              ),
            ),
          CachedNetworkImage(
            imageUrl: imageUrl,
            imageBuilder: (context, imageProvider) => Container(
              decoration: BoxDecoration(
                image: DecorationImage(
                  fit: fit,
                  image: imageProvider,
                  alignment: alignment,
                ),
              ),
            ),
          ),
        ],
      );
```

**Comment by gibahjoe** [comment]
> @renefloor @animalnots Indeed the problem was related to the blur hash widget, but the suggested solution unfortunately did not work. I found a workaround that looks like the following. Works like a charm 👌
> 
> ```dart
>  Stack(
>         children: [
>           if (blurHash != null)
>             Align(
>               alignment: alignment,
>               child: BlurHash(
>                 hash: blurHash,
>                 imageFit: fit,
>                 color: Colors.transparent,
>               ),
>             ),
>           CachedNetworkImage(
>             imageUrl: imageUrl,
>             imageBuilder: (context, imageProvider) => Container(
>               decoration: BoxDecoration(
>                 image: DecorationImage(
>                   fit: fit,
>                   image: imageProvider,
>                   alignment: alignment,
>                 ),
>               ),
>             ),
>           ),
>         ],
>       );
> ```




Your solution does work but just to take it a bit further in case anyone else is having the issue, you can use the below. Replace the `BlurHash` widget which is the cause of the issue with the `BlurHashImage` provider.

```dart
CachedNetworkImage(
 imageUrl:  '',
 fit: BoxFit.cover,
 imageBuilder:  (context, imageProvider) {
   return Container(
     decoration: BoxDecoration(
       image: DecorationImage(
         image: imageProvider,
         fit: BoxFit.cover,
       ),
     ),
   );
 },
 errorWidget: (_, __, ___) {
   return Center(
       child: Padding(
         padding: EdgeInsets.symmetric(horizontal: 20),
         child: Text(
           alt ?? '',
           textAlign: TextAlign.center,
         ),
       ), );
 },
 placeholder: (context, url) {
   return Container(
     decoration: BoxDecoration(
       image: DecorationImage(
         image: BlurHashImage(hash!),
         fit: BoxFit.cover,
       ),
     ),
   );
 },
)
```

Basically, use `BlurHashImage ` which is an image provider instead of the widget.
