### ISSUE TITLE
Only show placeholder after install image_picker (android release mode)

### ISSUE THREAD

**Issue by vukhacbiet** [Baseflow/flutter_cached_network_image#520]
My Flutter app was everything fine until I installed image_picker today.

I have followed the instructions:

- Add user permission INTERNET
- Add android:requestLegacyExternalStorage="true"

But my application not show any picture from internet (use widget CachedNetworkImage), I tried to remove image_picker package and everything work fine again.

Device: Android 9 and 10
Build: Release (Debug mode work normal)

**Platform:** 
- [ x] :robot: Android

**Comment by jyoo** [comment]
Hi @vukhacbiet,

Did you solve your problem?
