### ISSUE TITLE
How to delete the cached image after x given days if the image is not used?

### ISSUE THREAD

**Issue by BSid96** [Baseflow/flutter_cached_network_image#522]
I know there is a cacheManager, but how do I use it? Can someone write an example for it?

**Comment by Fatimamostafa** [comment]
This should work

```
DefaultCacheManager manager = new DefaultCacheManager();
manager.emptyCache();
```

**Comment by renefloor** [comment]
What do you want exactly? Do you want to change the default time? Currently the images are removed automatically after they are not used for 30 days, but you can change this by supplying your own cache manager idd.

**Comment by BSid96** [comment]
@renefloor  I was trying to find how to do that. Like @Fatimamostafa  answered how to clear the cache but how do I make it clear after lets say 15 days.

**Comment by renefloor** [comment]
You'd need to add flutter_cache_manager to your pubspec, but then you can do something like this:
```
final CacheManager customCacheManager = CacheManager(Config('customCacheKey',
    stalePeriod: Duration(days: 15)));

class CustomImageExample extends StatelessWidget {
  final String url;

  CustomImageExample(this.url);

  @override
  Widget build(BuildContext context) {
    return CachedNetworkImage(imageUrl: url, cacheManager: customCacheManager,);
  }
}
```

You need to give the cachemanager a different key, so you don't apply 2 different caching rules on the same cache.
There is at the moment no easy way to set the cache manager for all CachedNetworkImage widgets, but you can make a custom widget like this that sets the cache manager for you. You can also use something like riverpod or get_it to inject it. (A global variable like this example is pretty bad actually.)

**Comment by BSid96** [comment]
@renefloor  Oh I see thanks.
