### ISSUE TITLE
[Feature] Pre fetch

### ISSUE THREAD

**Issue by danielgomezrico** [Baseflow/flutter_cached_network_image#526]
## 🚀 Feature Requests

Have a way to prefetch an image but not show it, so the next time that the image will be shown it is already on the disk.

It will be a pleasure for me to send a PR with the code, can you give me some highlights to have in mind before I start coding?

### Contextualize the feature
It will help in a carousel of images, so you can prefetch the next or the next 2 pictures to make it more seamless the change of pictures.

### Describe the feature
One idea may be to have one static function that just does the query and save it into the cache but not show it in any place.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
Flutter has a precacheImage https://api.flutter.dev/flutter/widgets/precacheImage.html, it is best to use that function as it also decodes the image so it is really ready to be shown. 
You call it like this:
```
    precacheImage(
        CachedNetworkImageProvider(
          'https://via.placeholder.com/350x150',
        ),
        context);
```

**Comment by ariefwijaya** [comment]
@renefloor But precacheImage required a context. How to prefetch without any context ?
