### ISSUE TITLE
Reference to local file on device

### ISSUE THREAD

**Issue by polyGeek** [Baseflow/flutter_cached_network_image#531]
I have a question. I'm also using the Share plugin created by flutter.dev. (https://pub.dev/packages/share). Their plugin can attach a shared image but apparently I need a local image, not something from a URL. Is there any way to get a reference to the filename used to store a cached image so I can pass it to the Share plugin?

**Comment by renefloor** [comment]
You need to also add flutter_cache_manager as a dependency for that.
If you are sure the image is already loaded (for example because on that page you show the image), you can directly get the image from cache:
```
DefaultCacheManager().getFileFromCache(url);
```
Otherwise you can use this method:
```
DefaultCacheManager().getSingleFile(url);
```

**Comment by polyGeek** [comment]
Thanks, that's what I needed to know. And perfect timing, I'm about to update the app so I can incorporate this right away. Thanks again.
