### ISSUE TITLE
build in ios error

### ISSUE THREAD

**Issue by SnowLittleStone** [Baseflow/flutter_cached_network_image#534]
error:
    ../flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_cache_manager-2.1.0/lib/src/storage/cache_info_repositories/cache_object_provider.dart:59:18: Error:
    The method 'isDuplicateColumnError' isn't defined for the class 'DatabaseException'.
     - 'DatabaseException' is from 'package:sqflite_common/src/exception.dart'
     ('../flutter/.pub-cache/hosted/pub.flutter-io.cn/sqflite_common-1.0.1/lib/src/exception.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'isDuplicateColumnError'.
              if (!e.isDuplicateColumnError(CacheObject.columnKey)) rethrow;
                     ^^^^^^^^^^^^^^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_cache_manager-2.1.0/lib/src/storage/cache_info_repositories/cache_object_provider.dart:82:18: Error:
    The method 'isDuplicateColumnError' isn't defined for the class 'DatabaseException'.
     - 'DatabaseException' is from 'package:sqflite_common/src/exception.dart'
     ('../flutter/.pub-cache/hosted/pub.flutter-io.cn/sqflite_common-1.0.1/lib/src/exception.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'isDuplicateColumnError'.
              if (!e.isDuplicateColumnError(CacheObject.columnLength)) rethrow;
suggest:
you need update your yml file,update flutter_cache_manager library

**Comment by renefloor** [comment]
Fixed in recent versions by raising the minimal sqflite version.
