### ISSUE TITLE
App freeze when photo get 404 error

### ISSUE THREAD

**Issue by barangungor** [Baseflow/flutter_cached_network_image#537]
## 🐛 Bug Report

I'm using this in my project but app freeze when photo get 404 error. How can i fix it?

**Version:** 1.x

**Platform:** 
- 

- [x] :iphone: iOS

- [x] :robot: Android

**Comment by renefloor** [comment]
Does the app freeze, or does the debugger pause? 
Does the app freeze when you run in profile mode using `flutter run --profile`?

**Comment by barangungor** [comment]
Oh sorry, it does in debug mode, thanks.
