### ISSUE TITLE
Fail to load image when using imageBuilder inside a ListView.builder

### ISSUE THREAD

**Issue by khoadng** [Baseflow/flutter_cached_network_image#539]
## 🐛 Bug Report

Images fail to load. The placeholder is flickering while being pushed down one by one and then disappear completely. 

### Expected behavior
Images should be displayed, no flickering from the placeholder.

### Reproduction steps
I'm using a slightly modified version of ListContent from the official example
Reproduce source code
```dart
import 'package:flutter/material.dart';
import 'package:cached_network_image/cached_network_image.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: ListContent(),
    );
  }
}

/// Demonstrates a [ListView] containing [CachedNetworkImage]
class ListContent extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemBuilder: (BuildContext context, int index) => Card(
        child: Column(
          children: <Widget>[
            CachedNetworkImage(
              imageUrl: 'https://loremflickr.com/320/240/music?lock=$index',
              imageBuilder: (context, imageProvider) {
                return Container(
                  decoration: BoxDecoration(
                    image: DecorationImage(
                        image: imageProvider, fit: BoxFit.cover),
                  ),
                );
              },
              placeholder: (BuildContext context, String url) => Container(
                width: 320,
                height: 240,
                color: Colors.purple,
              ),
            ),
          ],
        ),
      ),
      itemCount: 250,
    );
  }
}

```
### Configuration

<details>
  <summary>Logs</summary>
  

```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
    • Flutter version 1.22.5 at C:\flutter
    • Framework revision 7891006299 (9 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.52.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (1 available)
    • Redmi Note 7 Pro (mobile) • eb916ab1 • android-arm64 • Android 10 (API 29)
```

</details>

**Version:** 2.5.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
Thanks for the good example. I'll look into it when I have time.

**Comment by fahadappguy** [comment]
Facing same issue  😔.

**Comment by peterbyCom** [comment]
I have the same problem... In Listview.builder. 

Are there any alternatives?  @renefloor

**Comment by peterbyCom** [comment]
Oh, yes, 
Only placeholder can be loaded, no image is displayed, and no debug log.

**Comment by renefloor** [comment]
The problem is not that the image fails loading, but that the image is shown with minimal height. A small fix is to set the height around the CachedNetworkImage Widget. I'm going to suggest multiple different fixes, as I don't know why all these other sub widgets are needed.

Shortest solution:
```
/// Demonstrates a [ListView] containing [CachedNetworkImage]
class ListContent extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemBuilder: (BuildContext context, int index) => Card(
        child: CachedNetworkImage(
          fit: BoxFit.cover,
          imageUrl: 'https://loremflickr.com/320/240/music?lock=$index',
          placeholder: (BuildContext context, String url) => Container(
            width: 320,
            height: 240,
            color: Colors.purple,
          ),
        ),
      ),
      itemCount: 250,
    );
  }
}
```

It goes wrong in combination with the Container. I guess that container wants to go minimal size.
```
/// Demonstrates a [ListView] containing [CachedNetworkImage]
class ListContent extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemBuilder: (BuildContext context, int index) => Card(
        child: Column(
          children: <Widget>[
            SizedBox(
              height: 240,
              child: CachedNetworkImage(
                imageUrl: 'https://loremflickr.com/320/240/music?lock=$index',
                imageBuilder: (context, imageProvider) {
                  return Container(
                    decoration: BoxDecoration(
                      image: DecorationImage(
                          image: imageProvider, fit: BoxFit.cover),
                    ),
                  );
                },
                placeholder: (BuildContext context, String url) => Container(
                  width: 320,
                  height: 240,
                  color: Colors.purple,
                ),
              ),
            ),
          ],
        ),
      ),
      itemCount: 250,
    );
  }
}
```

Or you can set the height to the Container in the imageBuilder:
```
/// Demonstrates a [ListView] containing [CachedNetworkImage]
class ListContent extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemBuilder: (BuildContext context, int index) => Card(
        child: Column(
          children: <Widget>[
            CachedNetworkImage(
              imageUrl: 'https://loremflickr.com/320/240/music?lock=$index',
              imageBuilder: (context, imageProvider) {
                return Container(
                  width: double.infinity,
                  height: 320,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                        image: imageProvider, fit: BoxFit.cover),
                  ),
                );
              },
              placeholder: (BuildContext context, String url) => Container(
                width: 320,
                height: 240,
                color: Colors.purple,
              ),
            ),
          ],
        ),
      ),
      itemCount: 250,
    );
  }
}
``

The other option is to remove the imageBuilder in your function:
```
/// Demonstrates a [ListView] containing [CachedNetworkImage]
class ListContent extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemBuilder: (BuildContext context, int index) => Card(
        child: Column(
          children: <Widget>[
            CachedNetworkImage(
              imageUrl: 'https://loremflickr.com/320/240/music?lock=$index',
              placeholder: (BuildContext context, String url) => Container(
                width: 320,
                height: 240,
                color: Colors.purple,
              ),
            ),
          ],
        ),
      ),
      itemCount: 250,
    );
  }
}
```

If you still want to have the 'cover' you can remove the column or set crossAxisAlignment to stretch:

```
/// Demonstrates a [ListView] containing [CachedNetworkImage]
class ListContent extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemBuilder: (BuildContext context, int index) => Card(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            CachedNetworkImage(
              fit: BoxFit.cover,
              imageUrl: 'https://loremflickr.com/320/240/music?lock=$index',
              placeholder: (BuildContext context, String url) => Container(
                width: 320,
                height: 240,
                color: Colors.purple,
              ),
            ),
          ],
        ),
      ),
      itemCount: 250,
    );
  }
}
```
or
```
/// Demonstrates a [ListView] containing [CachedNetworkImage]
class ListContent extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemBuilder: (BuildContext context, int index) => Card(
        child: CachedNetworkImage(
          fit: BoxFit.cover,
          imageUrl: 'https://loremflickr.com/320/240/music?lock=$index',
          placeholder: (BuildContext context, String url) => Container(
            width: 320,
            height: 240,
            color: Colors.purple,
          ),
        ),
      ),
      itemCount: 250,
    );
  }
}
```

**Comment by peterbyCom** [comment]
> The problem is not that the image fails loading, but that the image is shown with minimal height. A small fix is to set the height around the CachedNetworkImage Widget. I'm going to suggest multiple different fixes, as I don't know why all these other sub widgets are needed.
> 
> Shortest solution:
> 
> ```
> /// Demonstrates a [ListView] containing [CachedNetworkImage]
> class ListContent extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return ListView.builder(
>       itemBuilder: (BuildContext context, int index) => Card(
>         child: CachedNetworkImage(
>           fit: BoxFit.cover,
>           imageUrl: 'https://loremflickr.com/320/240/music?lock=$index',
>           placeholder: (BuildContext context, String url) => Container(
>             width: 320,
>             height: 240,
>             color: Colors.purple,
>           ),
>         ),
>       ),
>       itemCount: 250,
>     );
>   }
> }
> ```
> 
> It goes wrong in combination with the Container. I guess that container wants to go minimal size.
> 
> ```
> /// Demonstrates a [ListView] containing [CachedNetworkImage]
> class ListContent extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return ListView.builder(
>       itemBuilder: (BuildContext context, int index) => Card(
>         child: Column(
>           children: <Widget>[
>             SizedBox(
>               height: 240,
>               child: CachedNetworkImage(
>                 imageUrl: 'https://loremflickr.com/320/240/music?lock=$index',
>                 imageBuilder: (context, imageProvider) {
>                   return Container(
>                     decoration: BoxDecoration(
>                       image: DecorationImage(
>                           image: imageProvider, fit: BoxFit.cover),
>                     ),
>                   );
>                 },
>                 placeholder: (BuildContext context, String url) => Container(
>                   width: 320,
>                   height: 240,
>                   color: Colors.purple,
>                 ),
>               ),
>             ),
>           ],
>         ),
>       ),
>       itemCount: 250,
>     );
>   }
> }
> ```
> 
> Or you can set the height to the Container in the imageBuilder:
> 
> ```
> /// Demonstrates a [ListView] containing [CachedNetworkImage]
> class ListContent extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return ListView.builder(
>       itemBuilder: (BuildContext context, int index) => Card(
>         child: Column(
>           children: <Widget>[
>             CachedNetworkImage(
>               imageUrl: 'https://loremflickr.com/320/240/music?lock=$index',
>               imageBuilder: (context, imageProvider) {
>                 return Container(
>                   width: double.infinity,
>                   height: 320,
>                   decoration: BoxDecoration(
>                     image: DecorationImage(
>                         image: imageProvider, fit: BoxFit.cover),
>                   ),
>                 );
>               },
>               placeholder: (BuildContext context, String url) => Container(
>                 width: 320,
>                 height: 240,
>                 color: Colors.purple,
>               ),
>             ),
>           ],
>         ),
>       ),
>       itemCount: 250,
>     );
>   }
> }
> ```
> 
> The other option is to remove the imageBuilder in your function:
> 
> ```
> /// Demonstrates a [ListView] containing [CachedNetworkImage]
> class ListContent extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return ListView.builder(
>       itemBuilder: (BuildContext context, int index) => Card(
>         child: Column(
>           children: <Widget>[
>             CachedNetworkImage(
>               imageUrl: 'https://loremflickr.com/320/240/music?lock=$index',
>               placeholder: (BuildContext context, String url) => Container(
>                 width: 320,
>                 height: 240,
>                 color: Colors.purple,
>               ),
>             ),
>           ],
>         ),
>       ),
>       itemCount: 250,
>     );
>   }
> }
> ```
> 
> If you still want to have the 'cover' you can remove the column or set crossAxisAlignment to stretch:
> 
> ```
> /// Demonstrates a [ListView] containing [CachedNetworkImage]
> class ListContent extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return ListView.builder(
>       itemBuilder: (BuildContext context, int index) => Card(
>         child: Column(
>           crossAxisAlignment: CrossAxisAlignment.stretch,
>           children: <Widget>[
>             CachedNetworkImage(
>               fit: BoxFit.cover,
>               imageUrl: 'https://loremflickr.com/320/240/music?lock=$index',
>               placeholder: (BuildContext context, String url) => Container(
>                 width: 320,
>                 height: 240,
>                 color: Colors.purple,
>               ),
>             ),
>           ],
>         ),
>       ),
>       itemCount: 250,
>     );
>   }
> }
> ```
> 
> or
> 
> ```
> /// Demonstrates a [ListView] containing [CachedNetworkImage]
> class ListContent extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return ListView.builder(
>       itemBuilder: (BuildContext context, int index) => Card(
>         child: CachedNetworkImage(
>           fit: BoxFit.cover,
>           imageUrl: 'https://loremflickr.com/320/240/music?lock=$index',
>           placeholder: (BuildContext context, String url) => Container(
>             width: 320,
>             height: 240,
>             color: Colors.purple,
>           ),
>         ),
>       ),
>       itemCount: 250,
>     );
>   }
> }
> ```

Omg. My dear, the job is perfect now, thank you very much!
