### ISSUE TITLE
Error when trying to read a corrupt libCachedImageData.json file

### ISSUE THREAD

**Issue by TheYuriG** [Baseflow/flutter_cached_network_image#540]
## 🐛 Bug Report

Recently i got struck with an error that would not load any images from cache nor download new images (I cleared Temp and that did nothing). This only happened on my Windows project version after working flawlessly for 2 weeks, building the same project on Android would just work fine, which meant something was wrong with the Windows version of the build. Deleting the json file in the folder fixed the issue for me.

### Expected behavior
Load as normal. Instead, VSC stopped 4x to show me different errors being thrown.

### Reproduction steps
Replace the `libCachedImageData.json` in `C:\Users\USER\AppData\Roaming\PROJECT.DEV\PROJECTNAME` with a corrupt file.

### Configuration

**Version:** 2.5.0

**Platform:** 
- [x] Windows
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by renefloor** [comment]
Should be fixed by PR https://github.com/Baseflow/flutter_cache_manager/pull/269
