### ISSUE TITLE
Is there a way to make gif dynamic pictures without dynamic effects

### ISSUE THREAD

**Issue by stoneLee81** [Baseflow/flutter_cached_network_image#542]
When gif images are displayed more often, that will affect app performance. Is there a function to show static effects when showing gif pictures, so that will improve performance.

**Comment by renefloor** [comment]
What do you mean with the dynamic effects?

**Comment by stoneLee81** [comment]
i don't want GIF pictures to show animation, that will great affect app performance. is there a function to achieve static effects, do not show GIF animation?

**Comment by renefloor** [comment]
Not at the moment no. You don't have an option to just load an image (the first frame for example) instead of the gif?
