### ISSUE TITLE
Catch HttpException

### ISSUE THREAD

**Issue by stoneLee81** [Baseflow/flutter_cached_network_image#549]
Some picture URLs are encrypted and have time limits. Expired links need to be requested on the server side to generate a new URL. Whether the plug-in has the HTTPRESPONSE status callback listener, I can know the RESPONSE status of the calling picture. If response code is 401, that means expired, the code is initiated again Request, get a new picture link?

**Comment by renefloor** [comment]
Sorry, I don't really understand what you want.
For highly customizable http behaviour you can implement your own FileService: https://github.com/Baseflow/flutter_cache_manager/blob/develop/flutter_cache_manager/lib/src/web/file_service.dart

You can supply that in a custom CacheManager in the config: https://github.com/Baseflow/flutter_cache_manager/blob/develop/flutter_cache_manager/lib/src/cache_manager.dart#L38
