### ISSUE TITLE
Session reuse

### ISSUE THREAD

**Issue by josalhor** [Baseflow/flutter_cached_network_image#555]
Hello!

Disclosure, I am somewhat new to Dart!

I am currently using `flutter_cached_network_image` on an application that makes multiple requests to the same server. Even if the images get cached, a user may download tens or hundreds of images. Ideally, all these requests would reuse the same underlying session.

It looks like the underlying requests are being made by `flutter_cache_manager` and by a quick search in the source code it looks like the http sessions are different. Is my understanding correct?

Edit: Network analysis has confirmed this to be the case. The Handshake is repeated for every image request.

Is there anything that can be done to improve this situation?

**Comment by renefloor** [comment]
I don't think we can anything about that, as this is managed by the underlying http client or the server. If you have an idea how we might improve this please reopen the issue, but for now I'll close this as I don't think it is a solvable issue.
