### ISSUE TITLE
Getting 'HttpException: Failed to parse header value'

### ISSUE THREAD

**Issue by sivaperumal644** [Baseflow/flutter_cached_network_image#557]
## 🐛 Bug Report

When I use the above url in cachedNetworkImage(), I got the following error :
` CacheManager: Failed to download file from https://cdn-dev.archerreview.com/storage/answer/images/3a55685a-018b-481c-9833-2fb12594d8c3.jpg with error:
I/flutter (24231): HttpException: Failed to parse header value`

### Expected behavior
To render the image from the given url.

### Reproduction steps
Use this image in the cached network image url : https://cdn-dev.archerreview.com/storage/answer/images/3a55685a-018b-481c-9833-2fb12594d8c3.jpg and the image does not render and will throw the above error.

### Configuration

**Version:** 2.5.0

**Platform:** 
- [✓] :iphone: iOS
- [✓] :robot: Android

**Comment by renefloor** [comment]
This library is using the function `ContentType parse(String value)` of the http library.
Your content-type header is set to: `"application/json; charset=utf-8, image/jpg"`. This header contains 2 media-types, so the library cannot parse which type of file it is. Do you have any influence on these headers?

**Comment by sivaperumal644** [comment]
Yes this is how it come from backend and Image.network() works fine, and one more thing if  charset=utf-8 was excluded its works correctly in cached network image too, any idea on this?

**Comment by renefloor** [comment]
Image.network doesn't use the headers. Best would be to fix the header that it just returns the image part. We should also change the lib that if it can't parse the header it should just store the file without the extension instead of not storing it at all.
