### ISSUE TITLE
path_provider ^2.0.1 and cached_network_image ^2.5.0, version solving failed.

### ISSUE THREAD

**Issue by Kerwit** [Baseflow/flutter_cached_network_image#558]
Because cached_network_image >=2.5.0 <3.0.0-nullsafety depends on flutter_cache_manager ^2.1.0 which depends on path_provider ^1.6.18, cached_network_image >=2.5.0 <3.0.0-nullsafety requires path_provider ^1.6.18.

depends on both path_provider ^2.0.1 and cached_network_image ^2.5.0, version solving failed.

**Comment by renefloor** [comment]
If you want to use path_provider 2.0.1 you'll have to use CachedNetworkImage 3.0.0-nullsafety or override the dependency https://dart.dev/tools/pub/dependencies#dependency-overrides
