### ISSUE TITLE
It currently doesn't include caching.

### ISSUE THREAD

**Issue by wenrong443** [Baseflow/flutter_cached_network_image#560]
Hi,

I just notice that this library currently doesn't include caching. So any alternative solution?

**Comment by renefloor** [comment]
What makes you think it's not caching?

**Comment by wenrong443** [comment]
Hi @renefloor ,
I have try first load with Internet connection and it is working fine. 
After that, I enable airplane mode and kill and open apps again, the image is not showing out.

**Comment by renefloor** [comment]
On which platform is this? Can you also give the url of the image?

**Comment by wenrong443** [comment]
I try on Android device

Sample URL i have try: 
https://www.talkwalker.com/images/2020/blog-headers/image-analysis.png

**Comment by wenrong443** [comment]
@renefloor Hi, i try setup on a clean project and it is working, i think not working on my existing project maybe is caused by other library conflict issue. 

BTW, i saw you guys write this
The CachedNetworkImage can be used directly or through the ImageProvider. Both the CachedNetworkImage as CachedNetworkImageProvider have minimal support for web. It currently doesn't include caching.

May i know what you guys means by 'It currently doesn't include caching.'?

**Comment by renefloor** [comment]
The web version doesn't cache the images. If you just use the default I think it should automatically use the browser cache though. It is very difficult to manage files on the web.

**Comment by rshrc** [comment]
Hey @renefloor can you talk to me about an alternative cache system for images in flutter web. I've used this package and also the default Image.network(), but nothing seems to cache the images. 

My first guess was the misuse of the ListView.builder I was using. which pops off/does not load previous/next items until visible on the screen, but no, even when switching context, like (Navigating to a different page) was also reloading the images.

**Comment by FacePalmDev** [comment]
I'm also seeing that the caching is not working. Using the flutter network tools. This is a phone app not a web app in my case.

**Comment by wenrong443** [comment]
@rshrc @FacePalmDev Hi, here I write down my experience on this library.
1. Is your image url will changes after some time? 
    Because this library is using your image url as the key of the cache, so if your url is changed, then it will caused cache not working and download again.

    Please note that www.example.com/image/1.png?token=ABC is different with www.example.com/image/1.png?token=ABCD
