### ISSUE TITLE
flutter_cached_network_image doesn't detect HEIF format

### ISSUE THREAD

**Issue by RA1NO3O** [Baseflow/flutter_cached_network_image#564]
## 🚀 Feature Requests

The HEIF image contentType header is application/octet-stream
### Contextualize the feature

HEIF is a new image file format.
### Describe the feature

 Exception caught by image resource service 
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data
When the exception was thrown, this was the stack: 
0      _futurize (dart:ui/painting.dart:5275:5)
1      ImageDescriptor.encoded (dart:ui/painting.dart:5143:12)
2      instantiateImageCodec (dart:ui/painting.dart:1999:60)
<asynchronous suspension>
Image provider: NetworkImage("https://xxx.com/images/IMG_20210305_182854.HEIC", scale: 1.0)
Image key: NetworkImage("https://xxx.com/images/IMG_20210305_182854.HEIC", scale: 1.0)

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
When I look on 'the internet' I read that heif should be image/heif or image/heic. Do you have a source that it should be application/octet-stream? octet-stream is often just a binary stream.

**Comment by RA1NO3O** [comment]
I am sorry for my ignorance. Just now I realized my HTTP server doesn't respond the correct HTTP headers for HEIF file.
![image](https://user-images.githubusercontent.com/25654559/110494993-0e66db80-812f-11eb-9579-ac298f4813ba.png)
Thanks for your comment.

**Comment by RA1NO3O** [comment]
[HEIC support issue on flutter](https://github.com/vauvenal5/yaga/issues/39)
