### ISSUE TITLE
The function 'webOnlyInstantiateImageCodecFromUrl' isn't defined.

### ISSUE THREAD

**Issue by AnnaPS** [Baseflow/flutter_cached_network_image#565]
## 🐛 Bug Report

With **flutter 2** the class `_load_async_web.dart` has an error when it's try call to `webOnlyInstantiateImageCodecFromUrl` method. 
The exact error is: 
_`The function 'webOnlyInstantiateImageCodecFromUrl' isn't defined.  Try importing the library that defines 'webOnlyInstantiateImageCodecFromUrl', correcting the name to the name of an existing function, or defining a function named 'webOnlyInstantiateImageCodecFromUrl'.`_

Any idea to fix that? Thanks a lot 

![Captura de pantalla 2021-03-09 a las 10 44 10](https://user-images.githubusercontent.com/13244085/110456393-d0839c00-80c9-11eb-9f26-a9cad0d02f56.png)

### Configuration
 I have a Macbook Air with M1 chipset and this is my flutter doctor:

❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-arm, locale es-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

• No issues found!

**Version:** Flutter 2.0.1

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by renefloor** [comment]
Yep, the dart analyzer doesn't understand that function, but it's needed for web. NetworkImage uses the same: https://github.com/flutter/flutter/blob/e605b7c2250e803f46017b1d544fc8c297007546/packages/flutter/lib/src/painting/_network_image_web.dart#L91

If this is really breaking your app please reopen with a more precise problem, but this is nothing I can do about.
I tested it on mobile and web and the package works for me.
