### ISSUE TITLE
packages get version 2.5.1 on windows android studio with un-tar error

### ISSUE THREAD

**Issue by king163** [Baseflow/flutter_cached_network_image#567]
Could not un-tar (exit code 2). Error:

7-Zip (A) 9.20 Copyright (c) 1999-2010 Igor Pavlov 2010-11-18

Processing archive: C:\Users\ewu\AppData\Local\Temp\pub_fe07f7c6\archive.tar

Extracting example\ios\Flutter\Flutter.podspec

Extracting .editorconfig

. . .

Extracting example\ios\Runner\AppDelegate.h

file example\ios\Runner\AppDelegate.m

already exists. Overwrite with

example\ios\Runner\AppDelegate.m?

(Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit?

ERROR: Can't allocate required memory!

, path = '' pub get failed (66; , path = '')

**Comment by king163** [comment]
is ok on version 2.5.0

**Comment by renefloor** [comment]
Still broken in version 3.0.0? I have not seen anybody else with this issue.
