### ISSUE TITLE
Expose provider's `scale` argument on CachedNetworkImage widget

### ISSUE THREAD

**Issue by amake** [Baseflow/flutter_cached_network_image#572]
## 🚀 Feature Requests

Please expose `CachedNetworkImageProvider.scale` in the `CachedNetworkImage` constructor.

### Contextualize the feature

I would like to use the `CachedNetworkImage` widget with its nice placeholders and whatnot, but I also want to scale my images according to the screen's pixel density. The effect I want is

```dart
Image.network(myUrl, scale: MediaQuery.of(context).devicePixelRatio);
```

I can achieve this and take advantage of caching via

```dart
Image(image: CachedNetworkImageProvider(myUrl, scale: MediaQuery.of(context).devicePixelRatio));
```

But I still have to handle placeholders manually. Exposing the `scale` property on the `CachedNetworkImage` constructor and passing it along to the `CachedNetworkImageProvider` would let me have the best of both worlds.

### Describe the feature
Not sure what else to say about it.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by tgcasce** [comment]
Please just expose an init method with CachedNetworkImageProvider, either can placeholder and errorWidget
