### ISSUE TITLE
Image Does not load in release mode

### ISSUE THREAD

**Issue by athul-ain** [Baseflow/flutter_cached_network_image#580]
## 🐛 Bug Report

The app works fine on debug mode and everything works, when I run a release mode APK then the image won't load.
Already have the internet permission on Android Manifest, also other network calls are working (Firebase).

Is there any extra configuration needed to fix this issue?

I have already use cached_network_image in my multiple projects, and it was working well.
Is this the bug on the null safety version of the plugin?

### Configuration

**Version:** 3.0.0

**Platform:** 
- [ ] :robot: Android

**Comment by renefloor** [comment]
When I build an apk from the example it does show the images. Maybe something is wrong with proguard? Can you log the error (from inside the errorWidgetBuilder)?

**Comment by athul-ain** [comment]
> When I build an apk from the example it does show the images. Maybe something is wrong with proguard? Can you log the error (from inside the errorWidgetBuilder)?

![Screenshot_20210329-124306_NEXUS.png](https://user-images.githubusercontent.com/60373551/112799752-6a68b400-908c-11eb-86cb-30f517167e1a.png)

It doesn't show an error message it just shows the placeholder

The below is my code of the widget

`Card(
      clipBehavior: Clip.antiAlias,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(13)),
      child: Container(
        width: isCarousel ? double.infinity : 350,
        child: CachedNetworkImage(
          fit: BoxFit.fill,
          imageUrl: bannerData.image!,
          imageBuilder: (context, imageProvider) => Material(
            child: Ink.image(
              image: imageProvider,
              fit: BoxFit.cover,
              child: InkWell(
                  onTap: bannerData.link == null
                      ? null
                      : () {
                          gotoLinkPage(
                              link: bannerData.link!, context: context);
                        }),
            ),
          ),
          placeholder: (context, url) => Center(
            child: CircularProgressIndicator.adaptive(),
          ),
          errorWidget: (context, url, error) => Center(
            child: Text(error.toString()),
          ),
        ),
      ),
    )`

**Comment by Ali-Elganzory** [comment]
Encountered same issue. This [workaround](https://github.com/Baseflow/flutter_cached_network_image/issues/441#issuecomment-785473476) worked for me.

**Comment by patelharsh15** [comment]
I am also facing the same issue, but the only difference is that I am using cached_network_image: ^2.0.0. I think that it is bug.

**Comment by patelharsh15** [comment]
> Encountered same issue. This [workaround](https://github.com/Baseflow/flutter_cached_network_image/issues/441#issuecomment-785473476) worked for me.

Yes it also work for me. But I don't understand why it worked. Anyway thanks for your answer

**Comment by renefloor** [comment]
I think some class is removed by minifying, maybe something from sqflite, that shouldn't be removed. Strange thing though is that I use cachednetworkimage in a production app with minify enabled that just works.

**Comment by RafaelR7** [comment]
I'm having the same issue, but only when running in debug mode

**Comment by renefloor** [comment]
> I'm having the same issue, but only when running in debug mode

Doesn't really sound like the same issue. As far as I know you shouldn't enable minify on debug mode. 

Your images don't show in debug mode, but do show in production?

**Comment by ServOKio** [comment]
I have the same problem. In debug mode, the images are not loaded, but there is no error
![1](https://user-images.githubusercontent.com/51263003/113459019-ef512600-941c-11eb-90b9-aff285ac138f.gif)

**Comment by RafaelR7** [comment]
> Your images don't show in debug mode, but do show in production?

Yes, same problems as @ServOKio, some of my images won't load when running in debug mode, on release the images seems to be working fine

**Comment by renefloor** [comment]
Can you create a new ticket for that and describe how to reproduce? This ticket is about not showing in release mode (probably because of minify).

**Comment by RafaelR7** [comment]
> Can you create a new ticket for that and describe how to reproduce? This ticket is about not showing in release mode (probably because of minify).

Ok, I'll do that 👍🏻

**Comment by bhavik-multipl** [comment]
Faced same issue, image is not loading, neither in release and debug mode.

I have tried this [workaround](https://github.com/Baseflow/flutter_cached_network_image/issues/441#issuecomment-785473476) but no luck.

P.S. This does not happen everytime, it is happening at specific place but other places it works without any issues.

`CachedNetworkImage(
                  imageUrl: "https://avatars.githubusercontent.com/u/68329541?s=400&v=4",
                  fit: fit,
                  height: height,
                  width: width,
                  color: color,
                  imageBuilder: (context, imageProvider) {
                    return Material(
                      clipBehavior: Clip.antiAlias,
                      color: Colors.transparent,
                      child: Ink.image(
                        image: imageProvider,
                        fit: fit,
                        height: height,
                        width: width,
                      ),
                    );
                  },`

**Comment by TENX-S** [comment]
Still an issue on physical devices (iPhone Xs Max) iOS 15.4.1, Flutter 2.10.3 • channel stable. Works fine on Android emulator.

**Comment by manthri-mohan-sai** [comment]
Still facing this issue with release build.

**Comment by misteloo** [comment]
I faced with this bug in release mode :'(

**Comment by misteloo** [comment]
> I faced with this bug in release mode :'(

FIX
already I used container width through getx 
`Container(width : Get.width /2 )`
now i changed this to **MediaQuery.of(context).size.width**

**Comment by AwaisQazii** [comment]
@misteloo it worked. Thanks

**Comment by nadeemamanah** [comment]
@misteloo Been stuck on this for hours, This fixed it. Thanks

**Comment by MikesDevCorner** [comment]
Still an issue, please reopen ticket. loading images in production only works when setting minifyEnabled and shrinkResources to false in app/build.gradle. Would appreciate if it would be possible to minify and shrink in production and loading images still work :)

version 3.4.1 on flutter 3.26.0-0.1.pre

**Comment by paddy57** [comment]
@MikesDevCorner found any solution ?, been facing the same issue.
