### ISSUE TITLE
1.How to get the local cache path of the current url image.2.Listening after image download is complete

### ISSUE THREAD

**Issue by qcks** [Baseflow/flutter_cached_network_image#581]
1.How to get the local cache path of the current url image.
2.Listening after image download is complete

**Comment by renefloor** [comment]
To answer both questions, you can do something like this to print the current path of the image after the image download is complete (or at least when the image is shown, as this is also called when the image is not downloaded but shown from cache).

```dart
    CachedNetworkImage(
      progressIndicatorBuilder: (context, url, progress) => Center(
        child: CircularProgressIndicator(
          value: progress.progress,
        ),
      ),
      imageBuilder: (context, imageProvider) {
        DefaultCacheManager().getFileFromCache(url).then((file){
          print(file.file.path);
        });
        return Image(image: imageProvider);
      },
      imageUrl: url,
    );
```

You need to add `flutter_cache_manager: ^3.0.1` to you pubspec and `import 'package:flutter_cache_manager/flutter_cache_manager.dart';` to your file.

At the moment the cached_network_image library doesn't allow to get a notification only when the file is downloaded.
