### ISSUE TITLE
Im still getting the "Cannot clone a disposed image" bug in version 3.0.0

### ISSUE THREAD

**Issue by Yerokkim** [Baseflow/flutter_cached_network_image#588]
## 💬 Questions and Help

- 
![image](https://user-images.githubusercontent.com/37797937/114843361-09eeac00-9dda-11eb-8191-8cd0275ab200.png)

**Comment by renefloor** [comment]
Do you mean version 3.0.0?

Do you have any way to reproduce? The last example to reproduce this issue is fixed, so maybe it happens in other ways, but it will be really hard to reproduce if you can't give an example.

**Comment by renefloor** [comment]
@Yerokkim are you able to give an example where it happens?

**Comment by MartiSilvio** [comment]
it happens to me during hero animations

**Comment by HiroshiHorie** [comment]
This happens alot
