### ISSUE TITLE
Error while loading an existing image

### ISSUE THREAD

**Issue by StephanCassel** [Baseflow/flutter_cached_network_image#589]
Error while loading an existing image in debug mode. It happens now and then. 

1. An URL is hardcoded from Firebase-storage (URL A) -  Error (via  errorWidget)
2. An other URL is  hardcoded from Firebase-storage (URL B) - Success
3. Back to URL A - Error
4. Another go on URL B - Success

Restart the app:
1. URL A -Success 
2. URL B - Success
3. URL A - Success

Now everything is looking the business. It can take days/weeks before it happens again. 

Anyone seen something similar? 

/Users/stephan/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-NO)
    • Flutter version 2.0.5 at /Users/stephan/development/flutter
    • Framework revision adc687823a (2 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/stephan/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • SM G991B (mobile) • R3CR30HP9BR • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 90.0.4430.72

• No issues found!
Process finished with exit code 0

**Comment by renefloor** [comment]
The errorWidget also contains the error. Can you please add this error to your post, as we can't really do anything about 'sometimes an image doesn't load'.

**Comment by StephanCassel** [comment]
Yes, I will as soon as it happens.
