### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by MagnusJohansson** [Baseflow/flutter_cached_network_image#590]
## 🚀 Feature Requests

Please add Dart/Flutter null safety support

### Contextualize the feature

If this framework is planned to be relevant now and the future, null safety support is essential

### Describe the feature

https://dart.dev/null-safety/migration-guide

### Platforms affected (mark all that apply)
- [ x] :iphone: iOS
- [ x] :robot: Android

**Comment by renefloor** [comment]
Version cached_network_image: ^3.0.0 is migrated to null safety, see https://pub.dev/packages/cached_network_image/changelog#300---2020-03-27

**Comment by MagnusJohansson** [comment]
Ok, sorry. I was confused by the fact that null safety compatible packages has the null-safety tag on pub.dev.
This, apparently not.
My bad.

**Comment by renefloor** [comment]
I guess that is the case because of #463, but there is not really a good way to solve that I'm afraid.
