### ISSUE TITLE
Http headers ignored using CachedNetworkImageProvider

### ISSUE THREAD

**Issue by enricobenedos** [Baseflow/flutter_cached_network_image#593]
### Expected behavior
Possibility to retrieve an image with `Authorization` header with `CachedImageProvider`. With normal `CachedNetworkImage` there are no issues.

### Reproduction steps
This is an extract of my code:
```dart
openWidget: Stack(
        children: <Widget>[
          PhotoView(
            filterQuality: FilterQuality.high,
            minScale: PhotoViewComputedScale.contained,
            imageProvider: ntwImg.CachedNetworkImageProvider(
              imgUrl,
              headers: HTTPService.getHeaders(),
            ),
          ),
          const ActionRoundedButton(
            type: ActionRoundedButtonType.Pop,
          ),
        ],
      ),
```
Header is correct but this exception is returned:
```console
flutter: CacheManager: Failed to download file from https://myapi.com/v3/images/0/107/20210406_035728.jpg with error:
HttpException: Invalid statusCode: 401, uri = https://myapi.com/v3/images/0/107/20210406_035728.jpg
```
### Configuration

**Version:** 3.0.0

**Platform:** 
- [X] :iphone: iOS
- [X] :robot: Android

**Comment by renefloor** [comment]
That's close to impossible, as the CachedNetworkImage widget just passes the headers directly to the CachedNetworkImageProvider, see https://github.com/Baseflow/flutter_cached_network_image/blob/develop/lib/src/cached_image_widget.dart#L231-L239

**Comment by enricobenedos** [comment]
Now I will try to produce a complete app sample. It seems that when I use `CachedNetwork` image all works well, but with `CachedNetworkImageProvider` something is broken.

**Comment by includelife1** [comment]
same error still exists. cached_network_image: ^3.4.1
Headers works with CachedNetworkImage but not with provider.
