### ISSUE TITLE
Get Image Bytes for Printing

### ISSUE THREAD

**Issue by johncharris** [Baseflow/flutter_cached_network_image#594]
## 💬 Questions and Help

How can I get the bytes of an image for printing? I found the getImageFile method in the underlying cache, but I'm not sure how to take that Stream<FileResponse> and get bytes.

**Comment by renefloor** [comment]
What exactly do you mean? Do you just want to print how big the image is?

**Comment by johncharris** [comment]
I am writing code to print a report with the https://pub.dev/packages/printing library. To do this, I need to have the image bytes available when the document is put together so it can be rendered as a PDF.

**Comment by renefloor** [comment]
A you mean print like physical print, not printing to log.
You can get the bytes like this:
```
    var file = await DefaultCacheManager()
        .getSingleFile(url);
    var bytes = await file.readAsBytes();
```
