### ISSUE TITLE
Web-specific analysis errors

### ISSUE THREAD

**Issue by deakjahn** [Baseflow/flutter_cached_network_image#597]
As promised in that other issue, looking into your code, you seem to expect a single file with conditional import to work flawlessly. Yes, I don't think that will fly. What I have instead (and what is discussed in some places in the web) is the stub approach. A bit like federated but at a very small scale (and this isn't federated just reduced, it's much older than the idea of federated itself).

Basically, you need four files, not a single one. One that I prefer to call `interface.dart` that provides an abstract class with a factory. Then one file for each platform plus one. The plus one just throws an `UnimplementedError` when called, and the platform ones implement the abstract class. The interface has the conditional import but for both cases, not one like in your code:

    import 'worker.dart' //
        if (dart.library.io) 'worker_io.dart'
        if (dart.library.html) 'worker_web.dart';

When used, you use the factory to get the actual platform-dependent variant and simply use it with whatever API your class provides to the underlying functionality. Check out some actual code at https://github.com/deakjahn/flutter_isolate_web.

Sorry if this is something you know and tried and dismissed already but I _think_ it could be the solution to your problem. If this is enough in your case, then federated would be indeed overkill.

**Comment by renefloor** [comment]
What you say is very similar to what I've already done. The only thing I did not include was the Unimplemented version:
https://github.com/Baseflow/flutter_cached_network_image/blob/develop/lib/src/image_provider/cached_network_image_provider.dart#L5-L6
```
import '_image_provider_io.dart'
    if (dart.library.html) '_image_provider_web.dart' as image_provider;

abstract class CachedNetworkImageProvider
    extends ImageProvider<CachedNetworkImageProvider> {
  const factory CachedNetworkImageProvider(
    String url, {
    int? maxHeight,
    int? maxWidth,
    String? cacheKey,
    double scale,
    @Deprecated('ErrorListener is deprecated, use listeners on the imagestream')
        ErrorListener errorListener,
    Map<String, String>? headers,
    BaseCacheManager? cacheManager,
    ImageRenderMethodForWeb? imageRenderMethodForWeb,
  }) = image_provider.CachedNetworkImageProvider;

```

The problem is that the analyzer is still analyzing all the files, even when they are never imported, so it still fails.

This should work when you have a worker_io.dart like
```
import 'dart:io';
HttpClient client = new HttpClient();
...
```
and a worker_web.dart
```
import 'dart:html';
await HttpRequest.getString(path);
...
```

In this case you have a valid import dart:io with valid dart:io functions which just don't work on web and vice versa. The problem is that this packages uses `webOnlyInstantiateImageCodecFromUrl` from `dart:ui` which is only available in the web version of dart:ui so the analyzer doesn't understand that. 

It is not the problem that it doesn't run on web, or that it tries to run the webOnlyInstantiateImageCodecFromUrl on IO, but that the analyzer doesn't recognize the function.

So what I'll do is make a separate package so I can do like this:
```
import '_image_provider_io.dart'
    if (dart.library.html) 'package:cached_network_image_web/image_provider.dart' as image_provider;
```
If I do that the cached_network_image_web will be 'unidentified' on pub.dev, but at least cachednetworkimage has no errors.

**Comment by deakjahn** [comment]
Yes, this is something that only actual experience will tell, but I had the hunch that the difference between the two was just what makes it or breaks it. That you don't have the io version in the base file (the one I used for the `Unimplemented`) but that you have _both_ separate and refer to _both_ with conditionals, not just the web one.

I know that we had problems with `webOnlyInstantiateImageCodecFromUrl` (I did chime in in that thread much earlier) but I stopped relying on it a long time ago and I can't recall what I did. :-) Maybe just that I reproduced its functionality with my own code and I don't need to call it any more, getting rid of all the potential problems?

**Comment by deakjahn** [comment]
The situation is, I don't know if you happened to follow it, that Web missed some functionality with bitmaps and canvases and I wrote the PR to implement it in the engine. So, chances are what what I wrote in the engine already provides the functionality that replaces `webOnlyInstantiateImageCodecFromUrl` completely. I need to check out because I forgot the details since then, I just use it normally. :-)

**Comment by deakjahn** [comment]
Now that I looked into the engine source, this `webOnly...` is basically a very simple HTTP request that passes the data to the usual decoding functions. If all else fails and it isn't true what I suspected that separating the io and the web both into separate files and using conditionals for _both_ solves the analysis issues (which I'm still kinda thinking it does but I haven't tried with your actual code), what if you just provide your own simple implementation instead of calling this function?

**Comment by renefloor** [comment]
My first try was to create that separate package, however that is a bit different when using the factory method. 
The web implementation needs to implement the interface, but the interface has the factory that needs to return the io/web implementation, so I think we end up with a circular reference making it very difficult to create 2 packages.

I'm currently looking at copying the `webOnlyInstantiateImageCodecFromUrl` code. The canvas kit implementation is really similar to what I have with HttpGet. The canvaskit has the drawback that [you need to implement CORS](https://flutter.dev/docs/development/platform-integration/web-images#flutter-renderers-on-the-web). I'm currently looking at how to implement the other implementation that uses <img>. I copied almost everything already, but I'm a bit stuk on [HtmlImage](https://github.com/flutter/engine/blob/122d584d95cfe2de9758ecf47636968463183d64/lib/web_ui/lib/src/engine/html_image_codec.dart#L51). I'm not sure where to copy/import that from.

**Comment by renefloor** [comment]
@deakjahn copying HtmlImage is not an option as that gives a cast error when it tries to show the image: https://github.com/flutter/engine/blob/f45f52f5e8faa30a6442e67fa0c1d245549f23b1/lib/web_ui/lib/src/engine/bitmap_canvas.dart#L628

I don't see a way to import [HtmlCodec](https://github.com/flutter/engine/blob/122d584d95cfe2de9758ecf47636968463183d64/lib/web_ui/lib/src/engine/html_image_codec.dart#L16)

**Comment by deakjahn** [comment]
Wait a minute. Things come back now.

There was a solution I used in the blurhash module and later suggested to someone in the engine team. It got implemented although I don't know whether on my input or independently (the code does the same but it isn't a verbatim copy). Let me collect those fragments.

**Comment by deakjahn** [comment]
The idea is the we need to create a BMP on the fly from the bitmap data. The blurhash code is this: https://github.com/fluttercommunity/flutter_blurhash/blob/6bdec75a7352d1e52f3267296d5726e092d3ebec/lib/src/blurhash.dart#L96-L119

The very similar engine code is this: https://github.com/flutter/engine/blob/ccaae8d9582b275002f79f46ade56f9c1b307234/lib/web_ui/lib/src/ui/painting.dart#L495-L566

**Comment by deakjahn** [comment]
And I have my code in my internal federated plugin that I mentioned, providing the same functionality on all platforms. Actually, nothing fancy on mobile, no native plugin code, just plain Dart using the normal `ui` stuff. But on web, I do more (also using custom JS but that won't be necessary in your case).

So, while my _io_ code is a very simple:

    @override
    Future<skia.Image> getImage(Uint8List data, {int? targetWidth, int? targetHeight}) async {
      final codec = await skia.instantiateImageCodec(data, targetWidth: targetWidth, targetHeight: targetHeight);
      final frame = await codec.getNextFrame();
      return frame.image;
    }

(skia is just simple `import 'dart:ui' as skia;`, I prefer this prefix instead of the more common `ui`).

The _web_ counterpart is a bit more involved:

    Future<skia.Image> getImage(Uint8List data, {int? targetWidth, int? targetHeight}) async {
      //FIXME https://github.com/flutter/flutter/issues/57659
      final codec = await skia.instantiateImageCodec(data);
      final frame = await codec.getNextFrame();
      if (targetWidth == null && targetHeight == null) return frame.image;
      return await resizeImage(frame.image, width: targetWidth, height: targetHeight);
    }

I needed resizing and this has a still open error but you can leave that out:

    Future<skia.Image> getImage(Uint8List data, {int? targetWidth, int? targetHeight}) async {
      final codec = await skia.instantiateImageCodec(data);
      final frame = await codec.getNextFrame();
      return frame.image;
    }

**Comment by deakjahn** [comment]
So, I wouldn't worry about copying the original code. Just use the HTTP to get the image data itself and pass it directly to the code above. You'll receive a `skia.Image` all right.

**Comment by renefloor** [comment]
Just a plain HTTP get already works on canvaskit and html renderer. The problem with that is you need to set CORS correctly, and not everybody is able to do that. The plain HtmlImage uses the browser image fetching so it doesn't have the CORS requirements. I want to keep both options available.

About creating a separate package.
I have been trying to put CachedNetworkImageProvider for web in a separate package, but as I said that creates a circular dependency, or I need to drop the factory construction and create something like `CachedNetworkImage.new()` (🤮 )

However, what I can do is create separate packages for just the _loadAsync functions and use that inside CachedNetworkImage. That interface will only depend on plain Flutter code, so that will be easy.

**Comment by deakjahn** [comment]
OK but that won't be pretty, if you want to go down that rabbit hole. I did because I needed to support every single one of my bitmap operations on web but you can just say you can't be bothered. :-)

You fetch the image much like https://github.com/flutter/engine/blob/122d584d95cfe2de9758ecf47636968463183d64/lib/web_ui/lib/src/engine/html_image_codec.dart#L29-L51 does. Then you can get at the actual image contents of the browser image by doing some canvas drawing in JavaScript. Either you write some JS code directly, bundled with your package, or you might try to get away with @JS code written in Dart. Basically, you need to draw the image onto a HTML canvas and that canvas has a `toBlob()` function to extract the image to PNG or JPG.

It should be doable without using JS directly, just from Dart. But it ain't pretty.

**Comment by renefloor** [comment]
My plan is to stick with webOnlyInstantiateImageCodecFromUrl, but in a separate package.

**Comment by deakjahn** [comment]
Are you positive it will work? :-)

Because I know tried my approach and look what I got: "Error: SecurityError: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported." Sounds like CORS. :-)

Yes, `html.ImageElement` loading.

**Comment by renefloor** [comment]
@deakjahn I created a draft PR: #598
It need documentation updates and perhaps some tests, but I'd be happy if you can give an initial review.

**Comment by deakjahn** [comment]
OK, it works. another parameter was needed. It's not that terrible at all. Look, yout might be tempted to go with this solution :-)

    Future<skia.Image> _getImage(String url) {
      final completer = Completer<skia.Image>();
  
      final imgElement = html.ImageElement()
        ..src = url
        ..crossOrigin = 'anonymous';
      js_util.setProperty(imgElement, 'decoding', 'async');
      imgElement.decode().then((_) async {
        final canvas = html.CanvasElement(width: imgElement.naturalWidth, height: imgElement.naturalHeight);
        canvas.context2D.drawImage(imgElement, 0, 0);
        final blob = await canvas.toBlob('image/png');
        final data = await _getBlobData(blob);
        final codec = await skia.instantiateImageCodec(data);
        final frame = await codec.getNextFrame();
        completer.complete(frame.image);
      }).catchError((err) {
        completer.completeError(err);
      });
  
      return completer.future;
    }
  
    Future<Uint8List> _getBlobData(html.Blob blob) {
      final completer = Completer<Uint8List>();
      final reader = html.FileReader();
      reader.readAsArrayBuffer(blob);
      reader.onLoad.listen((_) => completer.complete(reader.result as Uint8List));
      return completer.future;
    }

**Comment by renefloor** [comment]
Thanks @deakjahn, I'll have a look at it :).

**Comment by deakjahn** [comment]
Is this PR already in a format that we could refer to it as GitHub url in pubspec? To try it directly from an app?

**Comment by renefloor** [comment]
It has path references, so I'm not sure that's working:
```
  cached_network_image_platform_interface:
    path: ../cached_network_image_platform_interface
```
I guess it is better to checkout the code and make a path reference to it from your app.

I tried your code, but somehow not all images loaded. It were the same images that are troubled by cors issues, so I guess that's it.
