### ISSUE TITLE
Is this  cached_network_image support  flutter web !!!!!!!!

### ISSUE THREAD

**Issue by samithe7** [Baseflow/flutter_cached_network_image#599]
can it keep image  cached  in pwa  web app

**Comment by renefloor** [comment]
You can use cached_network_image in the web, but the caching is not working. I'm having a hard time making pub.dev understand that web is supported It doesn't really cache though as that's hard to do on web. However, the web already has its own caching mechanism for images, so using html renderer (not canvas kit) the images are still cached by the browser (so also in the pwa app).

**Comment by jing-pei** [comment]
This should be explained in the description.

**Comment by steebchen** [comment]
Would it make sense to create a tracking issue for cache support for canvas kit?

**Comment by renefloor** [comment]
@steebchen in the cache manager repo there is quite an extensive issue with directions of a possible solution: https://github.com/Baseflow/flutter_cache_manager/issues/122

**Comment by alexeyinkin** [comment]
Can this package be marked as supporting web? I am adding web for my app and I try to sort out packages that do not support it to replace them. This should be achievable by looking at tops of pub.dev pages alone.

**Comment by renefloor** [comment]
@alexeyinkin that's difficult, because we cannot depend on dart:io in any way, but we do for the directory structures now.
