### ISSUE TITLE
Update dependencie on rxdart

### ISSUE THREAD

**Issue by hdavidmb** [Baseflow/flutter_cached_network_image#603]
## 🏗 Enhancement Proposal

`rxdart` package is currently at version `^0.27.0`. `cached_network_image 3.0.0` is currently depending on `rxdart ^0.26.0`. This makes `cached_network_image` package conflict with other updated packages depending on the last version of `rxdart`.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
fixed with the release of flutter_cache_manager: ^3.0.2
