### ISSUE TITLE
Library uses cached_network_image and it flagged as not supporting iOS by pub.dev

### ISSUE THREAD

**Issue by salkuadrat** [Baseflow/flutter_cached_network_image#605]
Here is the detail score evaluations from pub.dev:

Package does not support Flutter platform iOS
Because:
package:universe/universe.dart that imports:
package:universe/src/u.dart that imports:
package:universe/src/shared.dart that imports:
package:universe/src/layer/layer.dart that imports:
package:universe/src/layer/tile/tile.dart that imports:
package:universe/src/layer/tile/provider/provider.dart that imports:
package:universe/src/layer/tile/provider/network_cached.dart that imports:
package:cached_network_image/cached_network_image.dart that imports:
package:cached_network_image/src/image_provider/cached_network_image_provider.dart that imports:
package:cached_network_image/src/image_provider/_image_loader.dart that imports:
package:flutter_cache_manager/flutter_cache_manager.dart that imports:
package:flutter_cache_manager/src/web/web_helper.dart that imports:
package:flutter_cache_manager/src/cache_store.dart that imports:
package:flutter_cache_manager/src/config/config.dart that imports:
package:flutter_cache_manager/src/config/_config_io.dart that imports:
package:flutter_cache_manager/src/storage/file_system/file_system_io.dart that imports:
package:path_provider/path_provider.dart that imports:
package:path_provider_windows/path_provider_windows.dart that declares support for platforms: Windows

Anybody knows why?

**Comment by salkuadrat** [comment]
I thought it's because I use the ^3.0.0, but after I update it to latest ^3.1.0-alpha.1, the result is still the same

**Comment by renefloor** [comment]
I don't know, that's really weird. Also because flutter_cache_manager and path_provider dont' have these issues.

**Comment by renefloor** [comment]
This is fixed at least :)
