### ISSUE TITLE
when ı add this package it stays Running Gradle task 'assembleDebug'...

### ISSUE THREAD

**Issue by yildirimbhdr** [Baseflow/flutter_cached_network_image#611]
I created a new blank project and ı just add this package version 3.0.0.  Then the application gave an error while building.

**My flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19041.985], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)

• No issues found!

**Flutter version**
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (5 days ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

**Android exception output**
![dd](https://user-images.githubusercontent.com/69260315/120369817-80a91f80-c31c-11eb-898e-eb7f79d2cded.PNG)
![kj](https://user-images.githubusercontent.com/69260315/120369870-91f22c00-c31c-11eb-9b70-22aef6067fa7.PNG)

**Platform:** 
-Android

**Comment by renefloor** [comment]
![image](https://user-images.githubusercontent.com/15101411/120439402-c698ce80-c382-11eb-8284-b6bde7c75d9b.png)

This sounds like a temporary network issue on your side or on the maven side. Could you try again with an internet connection that works for sure?

**Comment by yildirimbhdr** [comment]
Reinstalling flutter sdk fixed it
