### ISSUE TITLE
cached network image still try to download the image after caching ?

### ISSUE THREAD

**Issue by AgungLaksana** [Baseflow/flutter_cached_network_image#615]
I am using `cached_network_image: ^3.0.0 and flutter 2.2.1
`
I have image URL that has time limit,  the image only available for 7 days. after that, it can't be accessed publicly
so the first 7 days, it works as expected. but I have error in the 8th day.

in the 8th day, when the image can't be accessed anymore via chrome browser ....
the image still appear in my app, because it is already cached in my app using this package (thanks)

but I have error message like below, even though my app is still running

> CacheManager: Failed to download file from https://storage.googleapis.com/xxxxxxx.appspot.com/eventTPoster/HuWQ5hoCQnOAwhnOe96K03/1926a9e2-d384-4d63-af33-87b843e%40appspot.gserviceaccount.com&Expires=16447ty%2FutIFVdM3

> HttpException: Invalid statusCode: 403, uri = https://storage.googleapis.com/kxxxxx.appspot.com/eventPoster/HuWxxxxxRQM0nOe96K03/1926a9e2-d384-4d63-a

I expect it will not show error message like that.  I mean ....
because the image comes from cache in the 8th day, I expect the package will not try to re download again from the server. in my case it is bad to re download again from server, because I have to pay more to Google Cloud Storage.

why does it try to re download the image again from server? even though the image clearly has been available from cache
am I missing something? or is it a bug? I use the widget like the code below

```
CachedNetworkImage(
        imageUrl: posterURL,
        fadeInCurve: Curves.easeIn,
        height: double.infinity,
        width: double.infinity,
        fadeInDuration: const Duration(milliseconds: 300),
);
```

**Comment by kamleshwebtech** [comment]
How long / how many days does it keep cache to images? Is there any Duration parameter to set it. Kindly confirm. Thank.

**Comment by AgungLaksana** [comment]
@kamleshwebtech 
I don't think I set duration parameter in my code, I don't even know it exists. I can still get the cache from an image created at 25 May (almost 3 weeks ago)

**Comment by renefloor** [comment]
It is taking the validity of the file from the cache headers: https://github.com/Baseflow/flutter_cache_manager/blob/develop/flutter_cache_manager/lib/src/web/file_service.dart#L85-L106

When the file is not valid anymore it still gives the file from the cache, but also tries to update the file (as it is outdated). You might be able to change the cache headers from your server to something very large or create a custom CacheManager with a custom FileService that overrides the `validTill` property. https://pub.dev/packages/flutter_cache_manager#customize
