### ISSUE TITLE
How long / how many days does it keep cache to images?

### ISSUE THREAD

**Issue by kamleshwebtech** [Baseflow/flutter_cached_network_image#616]
How long / how many days does it keep cache to images? Is there any Duration parameter to set it. Kindly confirm. Thank.

**Comment by renefloor** [comment]
If you supply a custom CacheManager you can set it by setting the stalePeriod and the maxNrOfCacheObjects. The defaults are 30 days and and 200 items. Note however that the validity of the File is defined by the cache-control headers, so a file might be available in the cache, but if it is outdated the cachemanager will try to update it. If that fails the old file is still used.

The stalePeriod means that if a file is not being used for 30 days by the app it will be removed. The maxNrOfCacheObjects are sorted by last used date.
