### ISSUE TITLE
Connection closed before full header was received in List View

### ISSUE THREAD

**Issue by AleksandrOleynik** [Baseflow/flutter_cached_network_image#617]
The following ClientException was thrown resolving an image codec:
Connection closed before full header was received
in List View when fast scroll

**Comment by renefloor** [comment]
I suspect it is related to the server. Which version of the library are you using?

Can you give a complete example so I can reproduce the issue?

**Comment by gautamchauhan1702** [comment]
Same issue in Listview.builder when fast scroll then Connection closed before full header was received 
                                 ListView.builder(
                                    itemCount: state.groupList.length,
                                    shrinkWrap: true,
                                    addAutomaticKeepAlives: false,
                                    itemBuilder: (context, index) {
                                      return CachedNetworkImage(
                                        imageUrl: "imageurl",
                                        height: SizeConfig.imageSizeMultiplier! * 17,
                                        width: SizeConfig.imageSizeMultiplier! * 17,
                                       fit: BoxFit.cover,
                                       errorWidget: (context, url, error) {                    
                                         return Container(
                          height: SizeConfig.imageSizeMultiplier! * 17,
                          width: SizeConfig.imageSizeMultiplier! * 17,
                CachedNetworkImage(
                      imageUrl: "${envConfig!.mediaUrl}${groupDTO!.image}",
                      height: SizeConfig.imageSizeMultiplier! * 17,
                      width: SizeConfig.imageSizeMultiplier! * 17,
                      fit: BoxFit.cover,
                      errorWidget: (context, url, error) {
                        print("<======== error : $error");
                        return Container(
                          height: SizeConfig.imageSizeMultiplier! * 17,
                          width: SizeConfig.imageSizeMultiplier! * 17,
                          color: AppTheme.grey4,
                        );
                      },
                      placeholder: (context, url) => Container(
                        height: SizeConfig.imageSizeMultiplier! * 17,
                        width: SizeConfig.imageSizeMultiplier! * 17,
                        color: AppTheme.grey4,
                      ),
                      
                        );
                      
                                         
              },
          ),

**Comment by CoryADavis** [comment]
I receive this error as well, and it actually doesn't concern me too much, as for my use case I'm OK with serving a placeholder every now and again.

The problem I do have though, is that after a particular image errors out and serves a placeholder, it doesn't retry again later on, it's cached as an error. Does this happen to you as well?

**Comment by kaciula** [comment]
I am also getting this kind of error when I am scrolling through a list of items that contain image urls. I show an error placeholder and then, if I scroll the item outside the visible view and bring it back to view to trigger a rebuild, the image loads fine.

So I think it has to do with fast scrolling through the list.

**Comment by luongduy2798** [comment]
I fixed it successfully
```
import 'package:flutter/material.dart';
import 'package:skeletons/skeletons.dart';
import '../../package_store.dart';

class CachedNetworkImageFixLoadError extends StatefulWidget {
  final String imageUrl;
  final double height;
  final double width;
  final BoxFit fit;

  const CachedNetworkImageFixLoadError(
      {Key key, this.imageUrl, this.height, this.width, this.fit})
      : super(key: key);

  @override
  _CachedNetworkImageFixLoadErrorState createState() =>
      _CachedNetworkImageFixLoadErrorState();
}

class _CachedNetworkImageFixLoadErrorState
    extends State<CachedNetworkImageFixLoadError> {
  ValueNotifier<String> _notifier;
  int countLoadImg = 0;

  @override
  void initState() {
    super.initState();
    _notifier = ValueNotifier(widget.imageUrl);
  }

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder(
        valueListenable: _notifier,
        builder: (BuildContext context, String value, Widget child) {
          print("rebuild $value");
          return CachedNetworkImage(
            cacheKey: _notifier.value.toString(),
            imageUrl: widget.imageUrl,
            placeholder: (context, url) => SkeletonAvatar(
              style: SkeletonAvatarStyle(
                height: widget.height,
                width: widget.width,
              ),
            ),
            errorWidget: (context, url, error) {
              print('load error $error');
              if (countLoadImg < 5) {
                Future.delayed(Duration(milliseconds: 50), () async {
                  countLoadImg++;
                  _notifier.value = _notifier.value +
                      DateTime.now().millisecondsSinceEpoch.toString();
                });
                return SkeletonAvatar(
                  style: SkeletonAvatarStyle(
                    height: widget.height,
                    width: widget.width,
                  ),
                );
              } else {
                return Image.asset(
                  ImagePaths.logo,
                  fit: BoxFit.cover,
                );
              }
            },
            fit: widget.fit ?? BoxFit.cover,
            height: widget.height,
            width: widget.width,
          );
        });
  }
}
```
