### ISSUE TITLE
The following ArgumentError was thrown resolving an image codec: Invalid argument(s): No host specified in URI undefined

### ISSUE THREAD

**Issue by ragokan** [Baseflow/flutter_cached_network_image#620]
## 🐛 Bug Report

The image shows every time, yet I receive errors in console even though there are no problem with URL or image.

![image](https://user-images.githubusercontent.com/63511519/123466228-c72a2b00-d5f7-11eb-86ee-d43085c99057.png)
As you can see the image is uploaded without any problem, but when you check the console, I get errors.

### Expected behavior
Logging for error is not expected, I was expecting to work without errors.

### Reproduction steps
I get the warning every time.

**Version:** 3.0.0

**Platform:** 
- [X] :robot: Android

**Comment by renefloor** [comment]
The image you are showing, is that really the complete code and you are not using CachedNetworkImage anywhere else?
The error shows you are trying to get an image from the url "undefined". Could it be that you are setting the url on a property and you are trying to show the image before that property is set?

**Comment by ragokan** [comment]
> The image you are showing, is that really the complete code and you are not using CachedNetworkImage anywhere else?
> The error shows you are trying to get an image from the url "undefined". Could it be that you are setting the url on a property and you are trying to show the image before that property is set?
> 
> Edit: let's close this issue and continue in #600

I will close this issue today. All the urls I am using gives error, sadly. I tried this url just to show and the url is not 'undefined'. Moreover, the image shows but I get the error.
