### ISSUE TITLE
How can I prefetch image after upgrade ?

### ISSUE THREAD

**Issue by kristijorgji** [Baseflow/flutter_cached_network_image#621]
Before upgrading the package I was looping into a fixed number of images to prefetch and doing this

```
var cimp = CachedNetworkImageProvider(photo.urls.medium);
cimp.load(cimp, null);
```
After upgrade to `cached_network_image: ^3.0.0`

how can I preload in cache images if I have no flutter context (I was doing this in app bloc on app start before rendering anything)

**Comment by renefloor** [comment]
Hmm.. To download and decode the image you can use [precacheImage](https://api.flutter.dev/flutter/widgets/precacheImage.html). You do need context for that.

To just make sure the file is downloaded you can use the cachemanager directly:
```
 var file = await DefaultCacheManager().getSingleFile(photo.urls.medium);
```

**Comment by kristijorgji** [comment]
> Hmm.. To download and decode the image you can use [precacheImage](https://api.flutter.dev/flutter/widgets/precacheImage.html). You do need context for that.
> 
> To just make sure the file is downloaded you can use the cachemanager directly:
> 
> ```
>  var file = await DefaultCacheManager().getSingleFile(photo.urls.medium);
> ```

Hi, thanks, so if i download it is already in cache, then will not be downloaded anymore, right ?
If yes, then is all great like what I was doing before preloading images that were opened in 2nd and second pages, way before usage for better experience.

**Comment by kristijorgji** [comment]
There is a problem I cannot find this class `The method 'DefaultCacheManager' isn't defined for th`

Is that part of this library version 3.0.0 flutter_cached_network_image ?

**Comment by kristijorgji** [comment]
Also why does precacheImage require context now, in previous version context was optional.
In blocs which are platform agnostics would be great be able to prefetch and store in cache (without decoding_ the images)

**Comment by renefloor** [comment]
> There is a problem I cannot find this class The method 'DefaultCacheManager' isn't defined 

It is using `flutter_cache_manager` to download and cache the files, so you should add that to your pubspec first: `flutter_cache_manager: ^3.1.2`

> Hi, thanks, so if i download it is already in cache, then will not be downloaded anymore, right ?

That's true, but it slightly depends on your http headers, if you define a `max-age` of 0 it will directly give the cached file, but also try to update the file in your cache. When the image is decoded and in memory it will not do that as long as that image is in memory.

> Also why does precacheImage require context now, in previous version context was optional.

I'm actually not sure how the previous method worked, but the `load()` of the image_provider is and has always been protected: https://github.com/flutter/flutter/blame/master/packages/flutter/lib/src/painting/image_provider.dart#L583-L584

I could make that method available in cached_network_image_provider.dart, but currently it is only available in `_image_provider_web.dart` and `_image_provider_io.dart`. But as I said, the original one is protected, so I'm not sure if that should be exposed.

The load function is not platform agnostic as it loads differently on IO than on web, so I'm also not sure if that's what you want.
