### ISSUE TITLE
'CachedNetworkImage' is not a subtype of type 'ImageProvider' when used inside of a builder

### ISSUE THREAD

**Issue by chapmacl** [Baseflow/flutter_cached_network_image#624]
I am using this alongside PhotoViewGallery, specifically the PhotoViewGallery.builder. The CachedNetworkImageProvider works great, but I would like to have a placeholder so the user knows that something is happening in the background.

In the docs and other issues here on Github, you suggest using the imagebuilder, which I have done, but the error message appears. Is there something I'm missing or is this a bug with the PhotoView library?

```
PhotoViewGallery.builder(
        builder: (BuildContext context, int index) {
            return PhotoViewGalleryPageOptions(
              imageProvider:  CachedNetworkImage(
                      imageUrl:
                          "someImageURL.com",
                      imageBuilder: (context, imageProvider) => Container(
                        decoration: BoxDecoration(
                          image: DecorationImage(
                            image: imageProvider,
                            fit: BoxFit.cover,
                          ),
                        ),
                      ),
                      placeholder: (context, url) =>
                          CircularProgressIndicator(),
                      errorWidget: (context, url, error) => Icon(Icons.error),
                    ),
            );
      }
)
```

**Comment by renefloor** [comment]
You can do it that way when you need the imageprovider, so this part is correct:
```
                  CachedNetworkImage(
                      imageUrl:
                          "someImageURL.com",
                      imageBuilder: (context, imageProvider) => Container(
                        decoration: BoxDecoration(
                          image: DecorationImage(
                            image: imageProvider,
                            fit: BoxFit.cover,
                          ),
                        ),
                      ),
```
However, the PhotoViewGallery kind of expects a list of imageproviders, which makes this solution impossible.

I saw that [PhotoViewGallery](https://pub.dev/documentation/photo_view/latest/photo_view_gallery/PhotoViewGallery-class.html) also contains a loadingBuilder, why wouldn't you use that in combination with the `CachedNetworkImageProvider`?

**Comment by chapmacl** [comment]
Thanks for the quick response. I guess I must have missed that option of PhotoView, but it works now.
