### ISSUE TITLE
Placeholder same aspect ratio of image

### ISSUE THREAD

**Issue by chitgoks** [Baseflow/flutter_cached_network_image#626]
## 🏗 Enhancement Proposal

If width and height are not specified, the code mentions it will set an intrinsic aspect ratio. 

### Pitch

Can this be possible for the placeholder? so that the height will stick to the same height

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X ] :robot: Android

**Comment by renefloor** [comment]
Do you mean that the placeholder has the size of the image? That's not really possible. It might be possible for images that are already in the cache, but while it is being loaded from the internet there is no way to already know the size of the image.

**Comment by chitgoks** [comment]
This might be flutter related but ill try to ask maybe you have an idea. what would you suggest CachedNetworkImage be wrapped in so that the loaded image will scale to its parent dimension (e.g. Card)

**Comment by renefloor** [comment]
If you want to read more about constraints I can really recommend this document: https://flutter.dev/docs/development/ui/layout/constraints

First question would be, what is the size of the Card? By default the Card size grows with its content. If you card size is fixed I think you should be able to set height or width to infinity and the image fills all the size that is available.

**Comment by chitgoks** [comment]
I got it. Funny thing i was stuck the whole morning and solved it now on a whim.
Originally the AspectRatio wrapped the CircularProgressIndicator. AspectRatio now wraps CachedNetworkImage so it is all good. Thanks

**Comment by chitgoks** [comment]
Just an additional question. Since im not sure how your lib behaves in a listview. Looks liek default behavior for the listview that when the rows come back into view, it reloads the image. which is bad ux since the image has already been downloaded so when it comes back into view, it should not show the placeholder, then the image

Do you think perhaps because the image is too big? I believe CachedNetworkImage resizes the image, right? I did not specify width and height , I figure it would resize based on the width of the listview

**Comment by renefloor** [comment]
When the image is loaded the decoded image bytes are stored in Flutter's ImageCache: https://api.flutter.dev/flutter/painting/ImageCache-class.html

When the images are very large it can indeed be that they are discarded from the cache and need to reload again. Even when reloading from disk the placeholder will be shown shortly. When you set memCacheWidth or memCacheHeight the size of the image im the memory ImageCache will be smaller.

**Comment by chitgoks** [comment]
Thank you. it worked.
I set it to
memCacheWidth: 1000,
memCacheHeight: 1000,

So the placeholder did not show up anymore. Thank you for taking time to reply rene, great lib!

**Comment by Ankit0080** [comment]
> I got it. Funny thing i was stuck the whole morning and solved it now on a whim.
> Originally the AspectRatio wrapped the CircularProgressIndicator. AspectRatio now wraps CachedNetworkImage so it is all good. Thanks

@chitgoks How did you set the height and width of placeholder ? In my case it is taking same space as image size 

My Code

CachedNetworkImage(
                                              height: 60,
                                              width: 60,
                                              useOldImageOnUrlChange: true,
                                              imageUrl: propertyList[index]
                                                  .property_url,
                                              imageBuilder:
                                                  (context, imageProvider) =>
                                                      Container(
                                                decoration: BoxDecoration(
                                                  shape: BoxShape.circle,
                                                  image: DecorationImage(
                                                    image: imageProvider,
                                                    fit: BoxFit.cover,
                                                  ),
                                                ),
                                              ),
                                              placeholder: (context, url) =>
                                                  Container(
                                                height: 20,
                                                width: 10,
                                                child:
                                                    CircularProgressIndicator(
                                                  color: AppColors.SKY_BLUE,
                                                  strokeWidth: 2,
                                                ),
                                              ),
                                            )

**Comment by chitgoks** [comment]
Hello im not going to analyze your code. This is how i did it

```
CachedNetworkImage(
      fit: BoxFit.fill,
      imageUrl: Web.root + '/files/' + item.thumbnail!,
      memCacheWidth: Web.imageCacheWidth,
      memCacheHeight: Web.imageCacheHeight,
      errorWidget: (context, url, error) => Image.asset('images/thumbnail.png', fit: BoxFit.fill),
      placeholder: (context, url) => SizedBox(
        height: 16.0,
        width: 16.0,
        child: Center(child: CircularProgressIndicator(strokeWidth: 1.5)),
      ),
    );
```

**Comment by Hanggi** [comment]
How could I get the size of image with CachedNetworkImage?
