### ISSUE TITLE
Consider compress image before save to cache directory.

### ISSUE THREAD

**Issue by phucgaoxam** [Baseflow/flutter_cached_network_image#63]
I tried to load about 200 image which each one of its resolution > 5000 x 5000. 
The plugin worked well but the problem is it saved my image with the same size of the download image (each image gonna be about ~5mb).
So if we don't compress image before saving, I think it will take a lot of storage in device.

**Comment by crazecoder** [comment]
https://github.com/renefloor/flutter_cached_network_image/pull/239
this pr might be useful

**Comment by rmahmadkhan** [comment]
It's been two years this issue is open. Any leads on the issue?

**Comment by renefloor** [comment]
@rmahmadkhan You can do this now by setting maxHeightDiskCache and/or maxWidthDiskCache. Using that it is first resized and then the resized version is stored on disk. At the moment it also stores the original size on disk, but this will be deleted if you don't use the image.

https://pub.dev/documentation/cached_network_image/latest/cached_network_image/CachedNetworkImage-class.html
