### ISSUE TITLE
Failed cache

### ISSUE THREAD

**Issue by asmith20002** [Baseflow/flutter_cached_network_image#633]
I use CachedNetworkImageProvider in a List.View and I've noticed the failed requests are not cached. As I scroll the list up and down, the failed images requests are fired over and over. Is this by design?  Is there a way to stop requesting a failed URL?

**Comment by renefloor** [comment]
Yep that is on purpose, specifically this line: https://github.com/Baseflow/flutter_cached_network_image/blob/develop/cached_network_image/lib/src/image_provider/_image_loader.dart#L68

We can't know the reason of the failure, it can be temporary. If the image would never load again when failed once it would be way more problematic for most.

When you use the error widget you can track of the errors yourself and just not show the image, but only the placeholder for the images that you expect to fail.
