### ISSUE TITLE
Web: v3.1.0 broke fetching images without CORS

### ISSUE THREAD

**Issue by eggnstone** [Baseflow/flutter_cached_network_image#634]
## 🔙 Regression

Using Flutter for Web.
Using `flutter build web --web-renderer html`

### Old (and correct) behavior
Using v3.0.0:
Images can be fetched from other sites using `sec-fetch-mode: no-cors`

### Current behavior
Images fail to be fetched from other sites because the package is using `sec-fetch-mode: cors`

### Reproduction steps
- Use `CachedNetworkImage` in a Flutter for Web app using the `html` renderer.
- Use e.g. Chrome to observe the network traffic and request headers
- Notice the difference in the request headers: `sec-fetch-mode: no-cors` (OK) vs. `sec-fetch-mode: cors` (not OK)

### Configuration

**Version:** 3.1.0

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] 🌐 Web

**Comment by MattyBoy4444** [comment]
Still doesn't seem to work for me.   Anyone else having problems?
