### ISSUE TITLE
Ability to not cache

### ISSUE THREAD

**Issue by Tom3652** [Baseflow/flutter_cached_network_image#638]
## 🚀 Feature Requests

Thanks for this package !
It would be really great if we could choose not to cache sometimes. 
I need your ```Widget``` for the good error handling but i don't want to have some images in cache and it's painful to handle cache myself in some cases.

### Describe the feature
Simply add a ```bool shouldCache``` param that allows the user to decider whether or not to cache the image.

### Platforms affected (mark all that apply)
- ✅  :iphone: iOS
- ✅  :robot: Android

**Comment by rgb1380** [comment]
This is a great plug-in that we use everywhere in out code. A web version of the plug-in (that obviously does not cache) will be hugely beneficial. As the OP stated one main reason for us to use this is its error handling and placeholder builder which is far superior to the handlers offered by Image.Network. It will also save us the trouble to having to use a replacement widget for web and potentially get inconsistent behaviour.

**Comment by renefloor** [comment]
You can [https://pub.dev/packages/octo_image](octo_image) combined with NetworkImage to have all the widget goodies without the caching. CachedNetworkImage also uses OctoImage actually for the widget.

@rgb1380 CachedNetworkImage actually already works in web (without the caching).

**Comment by Tom3652** [comment]
Thanks for the reply and the link, i didn't know about this package !

However that means that CachedNetworkImage package won't have any flag to disable cache right ? 
It's always painful to add more packages and dependencies but if i have to for now i will do... 

Regards

**Comment by rgb1380** [comment]
@renefloor thanks for the quick response and it is great that it supports web. Perhaps consider adding the 'Web' support label to the list of platforms.

**Comment by renefloor** [comment]
> However that means that CachedNetworkImage package won't have any flag to disable cache right ?

@Tom3652 that's true indeed.

> Perhaps consider adding the 'Web' support label to the list of platforms.

@rgb1380 Unfortunately there is no simple flag that web support is available. The analyzer itself tries to see if web is supported and that's quite hard to do while keeping all functionality as we cannot depend on dart:io in any way for the web part.
