### ISSUE TITLE
Invalid image data

### ISSUE THREAD

**Issue by Ankit0080** [Baseflow/flutter_cached_network_image#642]
I am having a weird issue with this package 

children: [
                  singleItem.image_url != null
                      ? CachedNetworkImage(
                          height: 30,
                          width: 30,
                          imageUrl: singleItem.image_url,
                          placeholder: (context, url) => Container(
                            height: 10,
                            width: 10,
                            child: CircularProgressIndicator(
                              color: AppColors.SKY_BLUE,
                              strokeWidth: 2,
                            ),
                          ),
                        )
                      : new Icon(Icons.error_rounded,
                          color: AppColors.SKY_BLUE),

This is my code and it is throwing exception "Invalid Image data" and it doesn't crash the app 
i am using 3.1.0 version and i have checked with 3.0.0 still same issue  and there is no option for placeholder height and width it is taking the same height and width of CachedImage

**Comment by renefloor** [comment]
Can you share the image url? Looks like the image itself is broken.

**Comment by Ankit0080** [comment]
@renefloor  Ok this is the image url "https://stud-house.s3.amazonaws.com/gallery/property_management.png" and image is loading after clicking on resume button in VS Code

**Comment by renefloor** [comment]
I just tried this code:
```dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'test',
      home: Scaffold(
          appBar: AppBar(
            title: Text('test'),
          ),
          body: CachedNetworkImage(
              height: 30,
              width: 30,
              imageUrl: 'https://stud-house.s3.amazonaws.com/gallery/property_management.png',
              placeholder: (context, url) => Container(
                    height: 10,
                    width: 10,
                    child: CircularProgressIndicator(),
                  ))),
    );
  }
}
```

I don't get any error. Are you sure that you are not first trying to load a different invalid url?

**Comment by yvone1991** [comment]
> @renefloor Ok this is the image url "https://stud-house.s3.amazonaws.com/gallery/property_management.png" and image is loading after clicking on resume button in VS Code

can you help me……issue #641 

3q very much！！！！

**Comment by renefloor** [comment]
@yvone1991 I have been on vacation, so have not been on github for some time. Can't help everybody at the same time.

**Comment by Ankit0080** [comment]
@renefloor this is the exactely same url i am using i am still having same issue even at all the places in app where i have used CachedImage this exception is thrown  . The image url are ok

**Comment by renefloor** [comment]
But do you also have the exception when you use just the code I showed you? If not there has to be some other bug somewhere.

**Comment by 528526221** [comment]
> But do you also have the exception when you use just the code I showed you? If not there has to be some other bug somewhere.

Hi, I also have this problem on Android devices. Strangely, there is no problem with the same code on IOS devices.  Here is the image url "https://hik-newportalpubs3.s3.ap-southeast-1.amazonaws.com/prd/public/all/portal/banner/2455a6af-e02c-4555-8290-e9c9da02eebd.png".  I look forward to your help :)

**Comment by kingmaster772** [comment]
I get the same error on `v2.5.1 (non null-safety)`. It looks like because I run on a slow network (2G/3G).

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Exception: Invalid image data. Error thrown Instance of 'ErrorDescription'.
       at .instantiateImageCodec(dart:ui)
       at CachedNetworkImageProvider._loadAsync(_image_provider_io.dart:120)
       at .suspension>(<asynchronous)
```

While I change back to 4G, `errorWidget` still appear. With expectation, this package request back image URL and `imageBuilder` appear properly when the device has a stable internet connection.

**Comment by doanngoctu95** [comment]
I get the same error on v3.2.0 with url is 'https://chat.ximedi.me/assets/logo_ximechat_full.svg?v=1.0.0'

What problem is? Please help me.
Thank in advance.

**Comment by bunny-pu** [comment]
Our app meet the same issue, and it has been the most frequently happened issue in live environment

**Comment by zhuwei** [comment]
+1

**Comment by nikomp** [comment]
+1, Exception: Invalid image data. Error thrown Instance of 'ErrorDescription'.
