### ISSUE TITLE
Precaching

### ISSUE THREAD

**Issue by dhcracchiolo** [Baseflow/flutter_cached_network_image#646]
## 🚀 Feature Requests

Love the package!  I may just not be doing it correctly but I can't find a way to precache images.  Unfortunately it doesn't seem to work with the built in precaching function provided by Flutter and I wasn't able to find anything in the documentation.  Let me know if I'm doing it wrong or if it doesn't exist.

**Comment by renefloor** [comment]
Not sure what you tried, but this should work:
```
precacheImage(
    CachedNetworkImageProvider(image.url),
    context,
);
```
Maybe your images are very large? The cache can only hold a certain amount of images.

**Comment by dhcracchiolo** [comment]
Hey!  Sorry, I was being a scrub.  This total works!  Thank you!
