### ISSUE TITLE
putFile and putFileStream is not updating the provider

### ISSUE THREAD

**Issue by tapkain** [Baseflow/flutter_cached_network_image#652]
Hi! When I'm uploading a file to a server, I'm putting it into the local cache (optimistic update) to display the uploaded image straight away on UI while it's being uploaded in background.
`putFileStream(
      url,
      file.content,
      eTag: file.eTag,
      key: key,
      maxAge: file.validTill.difference(DateTime.now()),
    );`
    
so the url in this case is the local file path and key is some unique key attached to this file.
the problem with this approach is that when I want later to update the local file, it is not updated on the UI because 
CachedNetworkImageProvider equality operator does not detect any change if cacheKey is being used. I'm putting a different file with the same cache key and the UI should reflect this update.

Maybe I'm doing local optimistic update wrong and there is a better approach as well?

**Comment by renefloor** [comment]
You can call `CachedNetworkImage(url).evict()` to clear the image cache and reload the image from disk. This should fix your issue. If not, please reopen this.

**Comment by Patrick386** [comment]
This doesn't work
![2021-10-13_153343](https://user-images.githubusercontent.com/49754877/137079754-09f11468-dc36-4292-8276-69ea84261848.png)
.
