### ISSUE TITLE
web support ?

### ISSUE THREAD

**Issue by amervelic** [Baseflow/flutter_cached_network_image#653]
### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by renefloor** [comment]
Web already has basic support. If you use the html version it also has default web caching mechanism. See this ticket for more information about caching development in canvaskit version: https://github.com/Baseflow/flutter_cache_manager/issues/122

Making this also appear on pub.dev is hard.
