### ISSUE TITLE
FileSystemException: Cannot open file, path = 'G:\temp\tmp\libCachedImageData\73ba21c0-21b8-11ec-b74e-85d79f7227f6.png'

### ISSUE THREAD

**Issue by kirill-21** [Baseflow/flutter_cached_network_image#658]
Error 112. Happens with message that there's no enough space on the disk. Errors is unhandled and can be caught with Flutter.onError.

I can not reproduce this issue manually, but sometimes it happens with users of my application

By the way i use errorWidget for all CachedNetworkImages
![image](https://user-images.githubusercontent.com/63228361/135405121-cc6b4436-7997-4878-bef2-dc703b3895c6.png)

**Comment by renefloor** [comment]
I'd guess this error should be registered as 'silent' and should not be logged to any crashlytics systems. There is not much as I can do as that is logic from Flutter's ImageProvider.
