### ISSUE TITLE
Need supporting http requests and https requests which have invalid ssl certs

### ISSUE THREAD

**Issue by guolingege** [Baseflow/flutter_cached_network_image#668]
as title, expecting adding it as an option
thanks

**Comment by bhlin790** [comment]
Is there a temporary solution?

**Comment by guolingege** [comment]
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.


import 'dart:async';
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;


import 'package:flutter/foundation.dart';


import 'package:flutter/painting.dart';




/// The dart:io implementation of [image_provider.NetworkImage].
class NetworkImageSSL extends ImageProvider<NetworkImage&gt; implements NetworkImage {
&nbsp; /// Creates an object that fetches the image at the given URL.
&nbsp; ///
&nbsp; /// The arguments [url] and [scale] must not be null.
&nbsp; const NetworkImageSSL(this.url, { this.scale = 1.0, this.headers })
&nbsp; &nbsp; &nbsp; : assert(url != null),
&nbsp; &nbsp; &nbsp; &nbsp; assert(scale != null);


&nbsp; @override
&nbsp; final String url;


&nbsp; @override
&nbsp; final double scale;


&nbsp; @override
&nbsp; final Map<String, String&gt; headers;


&nbsp; @override
&nbsp; Future<NetworkImage&gt; obtainKey(ImageConfiguration configuration) {
&nbsp; &nbsp; return SynchronousFuture<NetworkImage&gt;(this);
&nbsp; }


&nbsp; @override
&nbsp; ImageStreamCompleter load(NetworkImage key, DecoderCallback decode) {
&nbsp; &nbsp; // Ownership of this controller is handed off to [_loadAsync]; it is that
&nbsp; &nbsp; // method's responsibility to close the controller's stream when the image
&nbsp; &nbsp; // has been loaded or an error is thrown.
&nbsp; &nbsp; final StreamController<ImageChunkEvent&gt; chunkEvents = StreamController<ImageChunkEvent&gt;();


&nbsp; &nbsp; return MultiFrameImageStreamCompleter(
&nbsp; &nbsp; &nbsp; codec: _loadAsync(key as NetworkImage, chunkEvents, decode),
&nbsp; &nbsp; &nbsp; chunkEvents: chunkEvents.stream,
&nbsp; &nbsp; &nbsp; scale: key.scale,
&nbsp; &nbsp; &nbsp; informationCollector: () {
&nbsp; &nbsp; &nbsp; &nbsp; return <DiagnosticsNode&gt;[
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; DiagnosticsProperty<ImageProvider&gt;('Image provider', this),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; DiagnosticsProperty<NetworkImage&gt;('Image key', key),
&nbsp; &nbsp; &nbsp; &nbsp; ];
&nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; );
&nbsp; }


&nbsp; // Do not access this field directly; use [_httpClient] instead.
&nbsp; // We set `autoUncompress` to false to ensure that we can trust the value of
&nbsp; // the `Content-Length` HTTP header. We automatically uncompress the content
&nbsp; // in our call to [consolidateHttpClientResponseBytes].
&nbsp; static final HttpClient _sharedHttpClient = HttpClient()
&nbsp; &nbsp; ..badCertificateCallback =
&nbsp; &nbsp; ((X509Certificate cert, String host, int port) =&gt; true)
&nbsp; &nbsp; ..autoUncompress = false;


&nbsp; static HttpClient get _httpClient {
&nbsp; &nbsp; HttpClient client = _sharedHttpClient;
&nbsp; &nbsp; assert(() {
&nbsp; &nbsp; &nbsp; if (debugNetworkImageHttpClientProvider != null)
&nbsp; &nbsp; &nbsp; &nbsp; client = debugNetworkImageHttpClientProvider();
&nbsp; &nbsp; &nbsp; return true;
&nbsp; &nbsp; }());
&nbsp; &nbsp; return client;
&nbsp; }


&nbsp; Future<ui.Codec&gt; _loadAsync(
&nbsp; &nbsp; &nbsp; NetworkImage key,
&nbsp; &nbsp; &nbsp; StreamController<ImageChunkEvent&gt; chunkEvents,
&nbsp; &nbsp; &nbsp; DecoderCallback decode,
&nbsp; &nbsp; &nbsp; ) async {
&nbsp; &nbsp; try {
&nbsp; &nbsp; &nbsp; assert(key == this);


&nbsp; &nbsp; &nbsp; final Uri resolved = Uri.base.resolve(key.url);
&nbsp; &nbsp; &nbsp; final HttpClientRequest request = await _httpClient.getUrl(resolved);
&nbsp; &nbsp; &nbsp; headers?.forEach((String name, String value) {
&nbsp; &nbsp; &nbsp; &nbsp; request.headers.add(name, value);
&nbsp; &nbsp; &nbsp; });
&nbsp; &nbsp; &nbsp; final HttpClientResponse response = await request.close();
&nbsp; &nbsp; &nbsp; if (response.statusCode != HttpStatus.ok) {
&nbsp; &nbsp; &nbsp; &nbsp; // The network may be only temporarily unavailable, or the file will be
&nbsp; &nbsp; &nbsp; &nbsp; // added on the server later. Avoid having future calls to resolve
&nbsp; &nbsp; &nbsp; &nbsp; // fail to check the network again.
&nbsp; &nbsp; &nbsp; &nbsp; PaintingBinding.instance.imageCache.evict(key);
&nbsp; &nbsp; &nbsp; &nbsp; throw NetworkImageLoadException(statusCode: response.statusCode, uri: resolved);
&nbsp; &nbsp; &nbsp; }


&nbsp; &nbsp; &nbsp; final Uint8List bytes = await consolidateHttpClientResponseBytes(
&nbsp; &nbsp; &nbsp; &nbsp; response,
&nbsp; &nbsp; &nbsp; &nbsp; onBytesReceived: (int cumulative, int total) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; chunkEvents.add(ImageChunkEvent(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; cumulativeBytesLoaded: cumulative,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; expectedTotalBytes: total,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ));
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; );
&nbsp; &nbsp; &nbsp; if (bytes.lengthInBytes == 0)
&nbsp; &nbsp; &nbsp; &nbsp; throw Exception('NetworkImage is an empty file: $resolved');


&nbsp; &nbsp; &nbsp; return decode(bytes);
&nbsp; &nbsp; } finally {
&nbsp; &nbsp; &nbsp; chunkEvents.close();
&nbsp; &nbsp; }
&nbsp; }


&nbsp; @override
&nbsp; bool operator ==(Object other) {
&nbsp; &nbsp; if (other.runtimeType != runtimeType)
&nbsp; &nbsp; &nbsp; return false;
&nbsp; &nbsp; return other is NetworkImage
&nbsp; &nbsp; &nbsp; &nbsp; &amp;&amp; other.url == url
&nbsp; &nbsp; &nbsp; &nbsp; &amp;&amp; other.scale == scale;
&nbsp; }


&nbsp; @override
&nbsp; int get hashCode =&gt; ui.hashValues(url, scale);


&nbsp; @override
&nbsp; String toString() =&gt; '${objectRuntimeType(this, 'NetworkImage')}("$url", scale: $scale)';
}






------------------ Original ------------------
From: bhlin790 ***@***.***&gt;
Date: Thu,Jan 6,2022 5:54 PM
To: Baseflow/flutter_cached_network_image ***@***.***&gt;
Cc: 欧巴刚弄死他 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Baseflow/flutter_cached_network_image] Need supporting httprequests and https requests which have invalid ssl certs (Issue #668)





 
Is there a temporary solution?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by giaotuancse** [comment]
bring this issue back from in-active status.
Anyway to bypass this for flutter web?

**Comment by guolingege** [comment]
resolved in a global function:
```dart
import 'dart:io';
import 'dart:developer';

class VDHttpOverrides extends HttpOverrides {
  @override
  HttpClient createHttpClient(SecurityContext? context) {
    return super.createHttpClient(context)
      ..badCertificateCallback = (X509Certificate cert, String host, int port) {
        final k = '$host:$port';
        log('VDHttpOverrides_badCertificateCallback_host:port:$k');
        return k == 'api.xxxx.com:443';
      };
  }
}
```

```dart
void main(){
    HttpOverrides.global = new MyHttpOverrides();
    runApp(new MyApp());
}
```
[https://github.com/flutter/flutter/issues/19588](https://github.com/flutter/flutter/issues/19588)
