### ISSUE TITLE
imageProvider of imageBuilder from CachedNetworkImage with memCache have wrong size

### ISSUE THREAD

**Issue by bounty1342** [Baseflow/flutter_cached_network_image#686]
### Expected behavior
The provided image should be the resizedImage, equals to memCacheWidth, memCacheHeight.
This result in consuming lot of unnecessary memory.

```
════════ Exception caught by painting library ══════════════════════════════════
Image assets/images/background/bg5_opti.webp has a display size of 414×896 but a decode size of 462×1000, which uses an additional 474KB.

Consider resizing the asset ahead of time, supplying a cacheWidth parameter of 414, a cacheHeight parameter of 896, or using a ResizeImage.
════════════════════════════════════════════════════════════════════════════════
```

### Reproduction steps
        return CachedNetworkImage(
          fadeInDuration: const Duration(milliseconds: 300),
          useOldImageOnUrlChange: true,
          memCacheWidth: displaySize.width.toInt(),
          memCacheHeight: displaySize.height.toInt(),
          maxWidthDiskCache: displaySize.width >= displaySize.height
              ? EnumSize.xxl.transformToSize().width.toInt()
              : null,
          maxHeightDiskCache: displaySize.width < displaySize.height
              ? EnumSize.xxl.transformToSize().height.toInt()
              : null,
          height: displaySize.height,
          width: displaySize.width,
          fit: BoxFit.fill,
          errorWidget: (BuildContext context, String url, dynamic error) {
            CachedNetworkImage.evictFromCache(url);
            return _Error(displaySize: displaySize, error: error);
          },
          imageUrl: url,
          imageBuilder: (
            BuildContext context,
            ImageProvider<Object> imageProvider,
          ) {
            return Image(
                    // gaplessPlayback: true,
                    image: imageProvider,
                    height: displaySize.height,
                    width: displaySize.width,
                    fit: BoxFit.fill,
                  );
          },
          placeholder: (BuildContext context, __) {
            return const CupertinoActivityIndicator();
          },
        );

### Temporary solution
As stated in the Error, one could wrap a ResizeImage on top of the provider. But the Image Provider already does it :/

### Configuration
**Version:** 3.2.0

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
@bounty1342 your exception says `Image assets/images/background/bg5_opti.webp`, this doesn't sound like a web image. Is this the placeholder or error image?
