### ISSUE TITLE
Error building release in macOS desktop

### ISSUE THREAD

**Issue by Tonku** [Baseflow/flutter_cached_network_image#692]
I am getting this error while I am making a release build
/opt/homebrew/Caskroom/flutter/2.8.0/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/lib/src/cached_image_widget.dart:43:60: Error: Member not found: 'logLevel'.
  static CacheManagerLogLevel get logLevel => CacheManager.logLevel;
                                                           ^^^^^^^^
/opt/homebrew/Caskroom/flutter/2.8.0/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/lib/src/cached_image_widget.dart:46:23: Error: 'CacheManagerLogLevel' isn't a type.
  static set logLevel(CacheManagerLogLevel level) =>
                      ^^^^^^^^^^^^^^^^^^^^
/opt/homebrew/Caskroom/flutter/2.8.0/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/lib/src/cached_image_widget.dart:47:20: Error: Setter not found: 'logLevel'.
      CacheManager.logLevel = level;
                   ^^^^^^^^
So I can't complete the release build.

**Version:** 3.2.0

**Platform:** 
macOS m1

**Comment by renefloor** [comment]
Do you maybe override the flutter_cache_manager dependency? It is part of flutter_cache_manager v 3.3.0 and that's also the version cachednetworkimage is depending on.
