### ISSUE TITLE
Cached network image not showing image in android

### ISSUE THREAD

**Issue by mmustafaget** [Baseflow/flutter_cached_network_image#693]
## 🐛 Bug Report

cached network image error ..... MissingPluginException(No implementation found for method getTemporaryDirectory on channel

**Version:** 3.1.0
and also same happening in latest version

**Platform:** 
- [ ] :robot: Android

**Comment by vishalvishvakarma1111** [comment]
Facing same issue in   cached_network_image: ^3.2.0
please solve it

**Comment by vishalvishvakarma1111** [comment]
Facing same issue in cached_network_image: ^3.2.0
please solve it

**Comment by renefloor** [comment]
Is this the same issue as #497? As in, does it only happen in release or also debug?

**Comment by mmustafaget** [comment]
> Is this the same issue as #497? As in, does it only happen in release or also debug?

no, same case with release.

**Comment by renefloor** [comment]
It's probably this bug then: https://github.com/flutter/flutter/issues/95706. 
Should be fixed with the latest path provider. You can solve this by upgrading your flutter version or changing/adding path_provider in your pubspec with:
```
path_provider_android: ^2.0.11
```

If this doesn't fix it please reopen the issue.

**Comment by vishalvishvakarma1111** [comment]
ok

**Comment by mmustafaget** [comment]
> I have the same error. IOS Emulator IPhone 13. The same call works as a web app.

update your path provider plugin to the latest - hope this help.

**Comment by siloebb** [comment]
Was need to add in manifest...

<uses-permission android:name="android.permission.INTERNET"/>

**Comment by osangma** [comment]
restart app  no hot reload
