### ISSUE TITLE
can't load new image

### ISSUE THREAD

**Issue by eggysudianto** [Baseflow/flutter_cached_network_image#694]
I have first image (icon google) with name `image.jpg` and it's work normal, and then I try to replace image from (icon google) to (icon facebook) with same name `image.jpg`, but in my app still show (icon google) cannot update to show (icon facebook). how this plugin work if image is replaced ??

```
CachedNetworkImage(
  imageUrl: urlPrefixImages+widget.dataBanner[index].SliderImage,
  fit: BoxFit.fill,
  placeholder: (context, url) => Image.memory(bytes,fit: BoxFit.cover,),
  errorWidget: (context, url, error) => const Icon(Icons.error),
)
```

**Comment by renefloor** [comment]
Are they having the same url? In that case the cached version will be used for some time. You can use the cacheKey if you have a different image with the same url
