### ISSUE TITLE
Is there a way to know if an image was retrieved from the cache or from the network?

### ISSUE THREAD

**Issue by mark8044** [Baseflow/flutter_cached_network_image#695]
I have a fairly staightforward implementation, and the images show up everytime without fail 👍 

HOWEVER, I have a suspicion that nothing is being cached and everything is coming from network, as the images don't instantaneously appear when I restart my app (they fade in).

So to diagnose, as a first step I was hoping to figure out where the image came from, network vs. cache. Is there any easy way to determine this?

Here is my implementation:
```
Widget MyImage(String input, {bool showerror = true, height = 0}) {

  debugPrint('Loading an image: '+input);
  return CachedNetworkImage(
    imageUrl: input,
      width:double.infinity,
    height: (height>0) ? height : null,
    fit: BoxFit.cover,
     errorWidget: (context, url, error) => (showerror == true) ? Row(children:[Icon(Icons.error), Text(error.toString())]) : Container(),
  );
}
```

```
(...) child: MyImage(input: imageName)
```
Thanks!

**Comment by renefloor** [comment]
When loading from the disk they will also fade in. Only when they are already shown somewhere in the app and are thus in memory they are shown directly. 

You can easily try by disabling your internet connection. Currently the `CachedNetworkImage` doesn't provide the information, but you can also directly get the file from the [flutter_cache_manager](https://pub.dev/packages/flutter_cache_manager) and see if it comes from the cache.

**Comment by ken-ng-esotec** [comment]
Use `CachedNetworkImage.logLevel = CacheManagerLogLevel.verbose;` in main.dart

**Comment by bahman2000** [comment]
@renefloor There is no way to check via code?
