### ISSUE TITLE
Fetch New Image With Same URL

### ISSUE THREAD

**Issue by Ananda13th** [Baseflow/flutter_cached_network_image#696]
Hi, I have some question, is there any way to recaching different image with same URL? 
Example: 
I have a photo of doctor with url www.test/doctor/1.jpg, and after sometime, I want to replace the photo, so I delete the old one, and put a new file with the same URL. But when the app load the image, it show the old one. Some said using `cacheKey`, but I dont know what it does. Or does it have an expiring time for the cache? Thank you

```
                  child: CachedNetworkImage(
                        imageUrl: doctor.photo,
                        cacheKey: doctor.photo + DateTime.now().month.toString(),
                        imageBuilder: (context, imageProvider) =>
                            CircleAvatar(
                              backgroundImage: imageProvider,
                            ),
                        progressIndicatorBuilder: (context, url, downloadProgress) =>
                            Center(
                              child: CircularProgressIndicator(
                                  value: downloadProgress.progress,
                                  color : Constant.color
                              ),
                            ),
                        errorWidget: (context, url, error) =>   Image.asset("assets/images/profileAvatar.png"),
                      )
```

**Comment by renefloor** [comment]
The package uses [http cache-control headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control).
This means that if your server indicates the image is valid for a week it will try to refresh the image once a week. If you say it's valid for a day it will try to refresh once a day. In most cases the front-end doesn't know when an image changes, so the cache-control headers are your way to go. Note that this is set when the image is downloaded, so you can't easily force an update from the server side when you set the period to a very long time.
