### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by Rashid-Khabeer** [Baseflow/flutter_cached_network_image#697]
### Platforms affected (mark all that apply)
- [ ] 🌐 : Web

**Comment by renefloor** [comment]
@Rashid-Khabeer You can already use the library on web. Using the html renderer you will automatically get the caching mechanism of the browser. Using canvaskit you will not have any caching however. More information on that in these tickets: https://github.com/Baseflow/flutter_cache_manager/issues/122 and https://github.com/Baseflow/flutter_cache_manager/issues/339
