### ISSUE TITLE
No longer need of ! operation for Scheduler and PaintingBinding instances

### ISSUE THREAD

**Issue by chunghha** [Baseflow/flutter_cached_network_image#709]
## 🐛 Bug Report

Per this binding API clean-up, no longer need of ! operation for WidgetsBinding.instance.

https://github.com/flutter/flutter/pull/89451

### Expected behavior
No warnings below appear on console as flutter run.

```
../../../../../.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/lib/src/image_provider/multi_image_stream_completer.dart:152:22: Warning: Operand of
null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../../../tools/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.scheduleFrameCallback(_handleAppFrame);
                     ^
../../../../../.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/lib/src/image_provider/cached_network_image_provider.dart:109:29: Warning: Operand of
null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../../../../tools/flutter/packages/flutter/lib/src/painting/binding.dart').
      () => PaintingBinding.instance?.imageCache?.evict(key),
```

### Reproduction steps
Just "fluttter run" for app using cached_network_image. Might now only affect apps with master channel so at least I'd like to give a note about the warnings.

### Configuration

**Version:** on v3.2.0 with Flutter master channel

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by paulo101977** [comment]
Same here!!! I'm trying to update a project, but it's triggering this error. It just doesn't happen in this package, it happens in about 3.

**Comment by YonatanSegura97** [comment]
Same issue here!, is there any workaround?

**Comment by 7thHokage** [comment]
did you guys got any solution ?

**Comment by chunghha** [comment]
Resolved as v3.2.1 released. Thanks a lot!

**Comment by noahvelasco** [comment]
How do you solve this issue?

**Comment by JTibblesSoftcon** [comment]
> How do you solve this issue?

update your pubspec.yaml to use:
  cached_network_image: ^3.2.1
