### ISSUE TITLE
flutter 3.0.0 is detecting issue with the library

### ISSUE THREAD

**Issue by Bahrom2101** [Baseflow/flutter_cached_network_image#735]
/D:/flutter_windows_3.0.0-stable/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/lib/src/image_provider/cached_network_image_provider.dart(109,29): warning G1E0FE241: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null. [D:\FlutterProjects\billz_cashier_desktop\build\windows\flutter\flutter_assemble.vcxproj]

**Comment by MindMayhem** [comment]
dublicate of https://github.com/Baseflow/flutter_cached_network_image/issues/732

**Comment by Bahrom2101** [comment]
> dublicate of #732

sorry.

**Comment by nerder** [comment]
@Bahrom2101 please close it then.
