### ISSUE TITLE
Support loading IPFS Images

### ISSUE THREAD

**Issue by oliverbytes** [Baseflow/flutter_cached_network_image#743]
## 🚀 Feature Requests

I wish that you will support loading images from IPFS urls
Try this IPFS Image https://ipfs.io/ipfs/bafybeifvwitulq6elvka2hoqhwixfhgb42l4aiukmtrw335osetikviuuu and it will not be loaded

**Comment by chitgyi** [comment]
https://ipfs.io/ipfs/bafybeifvwitulq6elvka2hoqhwixfhgb42l4aiukmtrw335osetikviuuu this ipfs image is working on my simulator.

![Simulator Screen Shot - iPhone 12 Pro - 2022-05-23 at 16 53 23](https://user-images.githubusercontent.com/26025566/169799539-46323ef1-a07a-49ac-9cd7-e04b2d8995d4.png)

**Comment by pribbernow-marc** [comment]
Loading this URL is no problem for me, I tested with the current version in flutter app (on real device).

**Comment by oliverbytes** [comment]
> Loading this URL is no problem for me, I tested with the current version in flutter app (on real device).

Indeed the problem is in my end. Thanks
