### ISSUE TITLE
I only get HttpExceptionWithStatus when using this package

### ISSUE THREAD

**Issue by tobiasht** [Baseflow/flutter_cached_network_image#784]
## 🐛 Bug Report
When i try to add this package to my project i get a `HttpExceptionWithStatus` every time i use it. First i thought it was something wrong with my project or some dependencies that crashed somehow. But even if i create a brand new project and only add `cached_network_image` as a dependency, I get the same error. 

### Additional information
When adding the `cached_network_image` to my previous project i had problems when running `flutter pub get`. To fix my issues i have tried the following commands: 

```
sudo gem install ffi  
sudo arch -x86_64 gem install ffi
sudo gem install ffi -- --enable-libffi-alloc
```
Now `flutter pub get` works, but the package does not. 

Does anyone have any tips for how to solve this problem? 

### Configuration
I am using a M1 Pro

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by Shamsudeen12** [comment]
Can you share your Manifest.xml? @tobiasht
