### ISSUE TITLE
Can't you use this package as the cache manager(to try and support all platforms, instead of only ANDROID, IOS, MACOS)?

### ISSUE THREAD

**Issue by nivle** [Baseflow/flutter_cached_network_image#793]
package link: https://pub.dev/packages/cache_manager

Or forget cache and go with something this package: https://pub.dev/packages/hive

Or is there a reason why you wouldn't want this package to support all platforms?

**Comment by renefloor** [comment]
All platforms are supported. It should run fine everywhere. On previously supported platforms the cache uses sqflite, but on other platforms we just use a json string file. You can see that code here: https://github.com/Baseflow/flutter_cache_manager/blob/develop/flutter_cache_manager/lib/src/config/_config_io.dart#L41

We should migrate the other platforms as well, but than we would still have the dependency on sqflite for some time being to make sure apps can actually migrate to the new system. So all platforms are supported, but it's just hard to make that known on the badges of pub.dev.
