### ISSUE TITLE
The main premise of this package doesn't seem to work... images have a loading state pretty much every time.

### ISSUE THREAD

**Issue by hamishjohnson** [Baseflow/flutter_cached_network_image#829]

**Comment by aSameeraTennakoon** [comment]
did you try `flutter clean` and then run your program? I had the same issue and after a `flutter clean` it worked.

**Comment by therohansanap** [comment]
I am facing same issue and `flutter clean` did not help.

**Comment by nneuberger1** [comment]
@therohansanap I did what @aSameeraTennakoon did and it resolved my issue. I now see images loading. I was using an iPad 10th generation iOS 16.2 simulator on Mac.

Maybe consider doing a clean install of the app on your device or simulator. It's possible that it's a caching issue into temp folders on the device. Just an idea that I would try.

**Comment by renefloor** [comment]
> images have a loading state pretty much every time

It has a loading state the time it's reading the file from disk. The bigger the file the longer the loading state.
