### ISSUE TITLE
Not able to upgrade latlong2 and flutter_map to latest because of flutter_cached_network_image

### ISSUE THREAD

**Issue by Sun3** [Baseflow/flutter_cached_network_image#849]
## 🐛 Bug Report

When upgrading a project that uses cached_network_image version ^3.2.3 and you try to upgrade latlong2 to 0.9.0 and flutter_map to 5.0.0 you will receive the following error.

Error:
```
Because no versions of cached_network_image match >3.2.3 <4.0.0 and cached_network_image 3.2.3 depends on flutter_cache_manager ^3.3.0, cached_network_image ^3.2.3 requires flutter_cache_manager ^3.3.0.
And because no versions of flutter_cache_manager match >3.3.0 <4.0.0, cached_network_image ^3.2.3 requires flutter_cache_manager 3.3.0.
And because flutter_cache_manager 3.3.0 depends on http ^0.13.0 and flutter_map >=5.0.0 depends on http ^1.0.0, cached_network_image ^3.2.3 is incompatible with flutter_map >=5.0.0.
So, because my_journal depends on both flutter_map ^5.0.0 and cached_network_image ^3.2.3, version solving failed.
```

### Expected behavior
Able to upgrade latlong2 and flutter_map to the latest version.
Current latlong2: ^0.8.1 needs to be upgraded to 0.9.0
Current flutter_map: ^4.0.0 needs to be upgraded to 5.0.0

### Reproduction steps
Upgrade latlong2 tp 0.9.0
Upgrade flutter_map to 5.0.0
This will cause the error for cached_network_image package.

### Configuration

**Version:** ^3.2.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by codenashwan** [comment]
same
