### ISSUE TITLE
update dependencies, http: ^1.0.0 is not supported

### ISSUE THREAD

**Issue by MominRaza** [Baseflow/flutter_cached_network_image#854]
[yourapp] flutter pub get
Resolving dependencies...
Because no versions of cached_network_image match >3.2.3 <4.0.0 and cached_network_image 3.2.3 depends on flutter_cache_manager ^3.3.0, cached_network_image ^3.2.3 requires flutter_cache_manager ^3.3.0.
Because flutter_cache_manager 3.3.0 depends on http ^0.13.0 and no versions of flutter_cache_manager match >3.3.0 <4.0.0, flutter_cache_manager ^3.3.0 requires http ^0.13.0.
Thus, cached_network_image ^3.2.3 requires http ^0.13.0.
So, because yourapp depends on both cached_network_image ^3.2.3 and http ^1.0.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on http: flutter pub add http:^0.13.6
exit code 1

**Comment by memoriasIT** [comment]
While the PR from @Carapacik is merged you can do a dependency override:

dependency_overrides:
  flutter_cache_manager: ^3.3.1

**Comment by renefloor** [comment]
solved with the release of flutter_cache_manager 3.3.1, no need for override, as this package depends on ^3.3.0 it will be able to automatically resolve 3.3.1
