### ISSUE TITLE
update flutter cache manager to latest version

### ISSUE THREAD

**Issue by fisforfaheem** [Baseflow/flutter_cached_network_image#855]
### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by fisforfaheem** [comment]
also add complete flutter 3.10.5 support

**Comment by renefloor** [comment]
This package depends on ^3.3.0, so can automatically resolve 3.3.1. 3.3.1 doesn't add anything besides the support of http 1.0.0 and that will be automatically possible.
