### ISSUE TITLE
Should load images even if the SSL has expired

### ISSUE THREAD

**Issue by chitgoks** [Baseflow/flutter_cached_network_image#864]
## 🐛 Bug Report

there may be source images where the image site's ssl certificate has expired. should ignore it and load the image.

### Expected behavior
should still load

### Reproduction steps
load any image where the image url https has ssl expired.

### Configuration

**Version:** 3.2.1

**Platform:**  android
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by chitgoks** [comment]
Sorry. Seems HttpOverrides.global is the solution.

**Comment by giaotuancse** [comment]
@chitgoks HttpOverrides.global is not working on my case. Do you have any idea?

> Sorry. Seems HttpOverrides.global is the solution.

**Comment by chitgoks** [comment]
Sorry. No. It is working on my end. Maybe you are using it on other libs? This does not work on libraries that make use of video or audio players. There is simply no way. The source has to be SSL.
