### ISSUE TITLE
--- Failed to create image decoder with message 'unimplemented'

### ISSUE THREAD

**Issue by champ96k** [Baseflow/flutter_cached_network_image#869]
## 🐛 Bug Report

I encountered an error message "Failed to create image decoder with message 'unimplemented'" while using the cached_network_image package in my Flutter project.

### Expected behavior
I expected the cached_network_image package to successfully load and display the image from the provided URL without any error messages.

### Reproduction steps

Add the cached_network_image package to the project dependencies.
Use the package to load an image from a valid URL.
Run the app on an Android/iOS device or emulator.

used below images

```
I/flutter (28202): Image path info: network svg - https://pmi-offers-docs.s3.ap-south-1.amazonaws.com/hot_deals.svg
I/flutter (28202): Image path info: network svg - https://pmi-offers-docs.s3.ap-south-1.amazonaws.com/editors_picks.svg
I/flutter (28202): Image path info: network svg - https://pmi-offers-docs.s3.ap-south-1.amazonaws.com/explore_all.svg
I/flutter (28202): Image path info: network svg - https://pmi-offers-docs.s3.ap-south-1.amazonaws.com/expiring_soon.svg
I/flutter (28202): Image path info: network svg - https://pmi-offers-docs.s3.ap-south-1.amazonaws.com/explore_all.svg
I/flutter (28202): Image path info: network svg - https://pmi-offers-docs.s3.ap-south-1.amazonaws.com/latest_n_greatest.svg
I/flutter (28202): Image path info: network svg - https://pmi-offers-docs.s3.ap-south-1.amazonaws.com/editors_picks.svg
I/flutter (28202): Image path info: network svg - https://pmi-offers-docs.s3.ap-south-1.amazonaws.com/hot_deals.svg
```

### Configuration

cached_network_image: ^3.2.3

**Platform:** 

- Android

Error log 

```
D/OpenGLRenderer(28202): --- Failed to create image decoder with message 'unimplemented'
```

**flutter doctor:** 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

```

**Comment by leolopez89** [comment]
I have the same problem.

```log
E/FlutterJNI( 4533): Failed to decode image
E/FlutterJNI( 4533): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
```

**Comment by rekire** [comment]
Just a wild guess, this library does not support svg files.

**Comment by leolopez89** [comment]
I solved the problem cleaning the cache of my android emulator

see here https://github.com/Baseflow/flutter_cached_network_image/issues/837#issuecomment-1664292316

**Comment by champ96k** [comment]
> #837 (comment)

I'm still getting this issue on real device [Redmi A2+]

**Comment by renefloor** [comment]
> Just a wild guess, this library does not support svg files.

That's correct. SVG's are not supported automatically by Flutter and I'm not going to add support for svg's in this package as it will make things way more complex. For SVG's I would recommend [flutter_svg](https://pub.dev/packages/flutter_svg).

**Comment by binemmanuel** [comment]
I encountered a similar problem on `cached_network_image: ^3.3.0` and I'm not trying to render SVGs.

```
NativeAlloc concurrent copying GC freed 33051(2190KB) AllocSpace objects, 5(100KB) LOS objects, 49% free, 3576KB/7152KB, paused 145us,24us total 146.024ms
E/FlutterJNI( 6875): Failed to decode image
E/FlutterJNI( 6875): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI( 6875): 	at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI( 6875): 	at android.graphics.ImageDecoder.-$$Nest$smnCreate(Unknown Source:0)
E/FlutterJNI( 6875): 	at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:254)
E/FlutterJNI( 6875): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1981)
E/FlutterJNI( 6875): 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1973)
E/FlutterJNI( 6875): 	at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:554)
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack:
#0      _futurize (dart:ui/painting.dart:6950:5)
painting.dart:6950
#1      ImageDescriptor.encoded (dart:ui/painting.dart:6764:12)
painting.dart:6764
#2      instantiateImageCodecWithSize (dart:ui/painting.dart:2307:60)
painting.dart:2307
#3      PaintingBinding.instantiateImageCodecWithSize (package:flutter/src/painting/binding.dart:182:15)
binding.dart:182
#4      ImageLoader.loadImageAsync.<anonymous closure> (package:cached_network_image/src/image_provider/_image_loader.dart:68:22)
_image_loader.dart:68
<asynchronous suspension>
#5      ImageLoader._load (package:cached_network_image/src/image_provider/_image_loader.dart:129:27)
_image_loader.dart:129
<asynchronous suspension>
#6      new MultiImageStreamCompleter.<anonymous closure> (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:26:7)
multi_image_stream_completer.dart:26
<asynchronous suspension>

Image provider:
CachedNetworkImageProvider("https://domain.com/uploads/images/[gasportlite.com]_40167c37597fd5c6.jpg",
scale: 1.0)
 Image key:
CachedNetworkImageProvider("https://domain.com/uploads/images/[gasportlite.com]_40167c37597fd5c6.jpg",
scale: 1.0):
  CachedNetworkImageProvider("https://domain.com/uploads/images/[gasportlite.com]_40167c37597fd5c6.jpg",
  scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by waqadArshad** [comment]
This I believe is not related to SVG. maybe there's a problem with the cached version of the image for some reason. Shouldn't it re-fetch the image in case of an error? @renefloor

**Comment by No0b-master** [comment]
I seem to face this exact issue, but I'm not using SVG files, I'm decoding the base64 image in png or jpg, but it doesn't crash the app it just shows in the logs

**Comment by zhao004** [comment]
I didn’t use SVG images, but he still reported an error, “cached_network_image: ^3.3.1”.

```
E/FlutterJNI(18255): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'invalid input'Input contained an error.
E/FlutterJNI(18255): 	at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI(18255): 	at android.graphics.ImageDecoder.access$200(ImageDecoder.java:173)
E/FlutterJNI(18255): 	at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:250)
E/FlutterJNI(18255): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1847)
E/FlutterJNI(18255): 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1840)
E/FlutterJNI(18255): 	at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:558)
```

**Comment by emrszr** [comment]
I have same error with png file, cached_network_image: ^3.3.0

E/FlutterJNI( 5104): Failed to decode image
E/FlutterJNI( 5104): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI( 5104): 	at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI( 5104): 	at android.graphics.ImageDecoder.-$$Nest$smnCreate(Unknown Source:0)
E/FlutterJNI( 5104): 	at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:251)
E/FlutterJNI( 5104): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1935)

**Comment by Autom8r-82** [comment]
@renefloor This bug is not related to SVG, that was an assumption made which is not correct. 

I am getting the same issue on 3.3.0 and 3.3.1 using jpegs and pngs. Previously with 3.2.0 I can confirm there was no issue loading these exact same images.

I am going to try and dig into the codebase to fix this, but it would be helpful if you took a second look please!

**Comment by renefloor** [comment]
> Image provider:
CachedNetworkImageProvider("https://domain.com/uploads/images/[gasportlite.com]_40167c37597fd5c6.jpg",
scale: 1.0)

Indeed, if I try this website with something like postman I get a 403 with an html body, if I open it in the browser it redirects to https://www.domain.com/uploads/images/[gasportlite? with a 404.

**Comment by sonjz** [comment]
> I solved the problem cleaning the cache of my android emulator
> 
> see here [#837 (comment)](https://github.com/Baseflow/flutter_cached_network_image/issues/837#issuecomment-1664292316)

i too fixed it this way. i just deleted the existing apps from the simulator.
i performed a flutter upgrade and the old app/cache likely had issues and needed a fresh app.

**Comment by tovidd** [comment]
In my case using [flutter_svg](https://pub.dev/packages/flutter_svg)

On android: 
```dart
SvgPicture.asset(
  'assets_01.svg',
  colorFilter: const ColorFilter.mode(
    Colors.white,
    BlendMode.src, // causing failed to decode
    BlendMode.srcIn, // this works
  ),
),
  ```

While on web:
```dart
SvgPicture.asset(
  'assets_02.svg',
  colorFilter: const ColorFilter.mode(
    Colors.white,
    BlendMode.src, // this works
    BlendMode.srcIn, // didn't show any images
  ),
),
```

**Comment by CodeWithDarshan04** [comment]
E/FlutterJNI( 4704): Failed to decode image
E/FlutterJNI( 4704): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI( 4704): 	at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI( 4704): 	at android.graphics.ImageDecoder.-$$Nest$smnCreate(Unknown Source:0)
E/FlutterJNI( 4704): 	at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:254)
E/FlutterJNI( 4704): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1981)
help me
Solve this error....

**Comment by Ria-Tomar** [comment]
I faced same issue in flutter using cached_network_image 3.4.1. How to resolve it?

**Comment by OnClickListener2048** [comment]
Does this issues fixed ?

**Comment by sibeux** [comment]
I don’t know why this bug is happening, because with the same link in another widget and class, the image loads fine. I hope this problem can be resolved quickly.

**Comment by RuyVictor** [comment]
This problem starts to appear when you extend the class with AutomaticKeepAliveClientMixin, apparently saving the widget state is impacting image decode processing

**Comment by hterrolle** [comment]
got the same problem on android using ImageReader.OnImageAvailableListener

I/Camera3: ImageReader.OnImageAvailableListener : onImageAvailable 
D/OpenGLRenderer: --- Failed to create image decoder with message 'unimplemented'

when i try to use BitmapFactory.decodeByteArray.

android min 23 compileSdkVersion 30.  xiaomi 13T pro

PS:

I find a solution in my case for displaying the YUV_420_888 the gray plane :

Bitmap.createBitmap(1920,1080,Bitmap.Config.ALPHA_8)
Image image = reader.acquireLatestImage(); // need maximage = 3
ByteBuffer Y = image.getPlanes()[0].getBuffer();
bitmapBuffer.copyPixelsFromBuffer(Y);
