### ISSUE TITLE
TypeError thrown for AVIF files (could not convert raster image to png) 

### ISSUE THREAD

**Issue by kvenn** [Baseflow/flutter_cached_network_image#873]
## 🔙 Regression

[This image url](https://images.unsplash.com/photo-1685016925614-d41b39fb66b5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDI2fHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=800&q=60) throws a non-fatal `_TypeError` 100% of the time.

This happened when we updated to Flutter version `3.13.1` with Impeller (could be unrelated?)

### Old (and correct) behavior

The image loaded without throwing an error

### Current behavior

An error is thrown

```
[VERBOSE-2:image_encoding.cc(123)] Could not convert raster image to PNG.
_TypeError: Null check operator used on a null value
  File "painting.dart", line 1959, in _Image.toByteData.<fn>.<fn>
```

### Reproduction steps

Run this on a physical device on flutter 3.13.1

      return CachedNetworkImage(
        imageUrl:'https://images.unsplash.com/photo-1685016925614-d41b39fb66b5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDI2fHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=800&q=60',
        fit: BoxFit.cover,
        memCacheWidth: 100,
        memCacheHeight: null,
        maxWidthDiskCache: 100,
        maxHeightDiskCache: null,
        placeholder: (context, url) => const Container(color: Colors.white.withOpacity(0.05),),
      );

### Configuration

**Version:** 3.2.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by Byrceh** [comment]
I have the same problem...
Flutter 3.13.0.
iOS device.
Everything's good on Android.

**Comment by Hari-07** [comment]
Did a little bit of experimenting and seems like `maxWidthDiskCache: 100` is the culprit here. With that commented out, the error doesn't happen. Might be useful to whoever is going to debug this

**Comment by Hari-07** [comment]
It's this line that's throwing, when `maxWidthDiskCache` is null it doesn't even reach that line

https://github.com/Baseflow/flutter_cache_manager/blob/32b71c1da1689b97434959ac407b03b74d7e405c/flutter_cache_manager/lib/src/cache_managers/image_cache_manager.dart#L97-L100

**Comment by Hari-07** [comment]
Seems like this is related to a regression with impeller, however could be fixed if flutter_cache_manager didn't use `ImageByteFormat.png`

Have opened an [issue](https://github.com/flutter/flutter/issues/133942) regarding the regression

**Comment by renefloor** [comment]
@Hari-07 it read likes it's fixed and probably should work on master channel?

**Comment by renefloor** [comment]
Closing this as it seems like it's solved on Flutter master. Anyway it doesn't look like CachedNetworkImage specific.
