### ISSUE TITLE
Feature request: need way to pre-cache images

### ISSUE THREAD

**Issue by lukehutch** [Baseflow/flutter_cached_network_image#874]
## 🚀 Feature Requests

I want to be able to tell the `flutter_cache_manager` that an image should be cached, without actually creating a `CachedNetworkImage`. The purpose of this is to anticipate which images the user will shortly request to be displayed through the UI, and prefetch them, before the user takes any action.

### Contextualize the feature

`package:flutter/src/widgets/image.dart` has a public function `precacheImage` that does this for asset images, using the RAM image cache. This can be called from `didChangeDependencies` of a `Widget` to attempt to reduce UI jank from images loading. `CachedNetworkImage` needs the same sort of method.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by Hari-07** [comment]
`preCacheImage` seems to work just fine last I checked even for CachedNetworkImages

**Comment by Hari-07** [comment]
Oh you want to pre cache to disk? But wouldn't that be slow as well

**Comment by lukehutch** [comment]
@Hari-07 Yes, pre-caching to disk is the whole purpose of `flutter_cached_network_image`. Pre-fetching Web-hosted images to a disk cache means that when those same images are requested by URL, they can be displayed almost instantly. 

`preCacheImage` decodes images into pixels, but it can only be used for a limited number of images, because the RAM cache is limited to 100MB in size, which is not a lot once images are decompressed. It serves a different purpose though.

The issue I am dealing with is that some users can have a slow data connection. So I want to pre-fetch images and cache them on disk when I anticipate that the UI might need to display those images soon, based on predicting the user's behavior. That way the UI will feel snappier, even on a slow data connection.

**Comment by lukehutch** [comment]
I assume I can explicitly include `flutter_cache_manager` in my dependencies, then ask that to fetch the images I want to precache. But this should be available in the API of `flutter_cached_network_image`.

**Comment by Hari-07** [comment]
When you do `preCacheImage` with `CachedNetworkImageProvider` doesn't it do what you want? And filling up RAM cache shouldn't be an issue since that should get automatically evicted if required

**Comment by lukehutch** [comment]
@Hari-07 `preCacheImage` decodes each image into uncompressed pixels. I wanted a way to instead simply download the compressed images to the disk cache.

It looks like `flutter_cache_manager` uses `DefaultCacheManager`, so I used the following:

```
DefaultCacheManager().getSingleFile(url).ignore();
```

I can't yet verify that this is correct, but some variant of this should work. Thanks!
