### ISSUE TITLE
Error: Type 'DecoderCallback' not found.

### ISSUE THREAD

**Issue by orgil6m** [Baseflow/flutter_cached_network_image#877]
## 🐛 Bug Report

Error (Xcode): ../../../.pub-cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/cached_network_image_provider.dart:78:54: Error: Type 'DecoderCallback' not found.

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by wanjm** [comment]
https://api.flutter.dev/flutter/painting/DecoderCallback.html
it has been Deprecated

**Comment by chichichunam** [comment]
Having a same problem here too. It is depreciated then do we have to wait for a new version?

**Comment by neeltechuser** [comment]
i am still facing this issue flutter version 3.18

**Comment by yykcw** [comment]
i am using flutterflow_ui and it forced me to use the old version

**Comment by ihr1337** [comment]
Flutter 3.3.4
Got this when tried to launch my project

**Comment by FlyNumber** [comment]
> i am using flutterflow_ui and it forced me to use the old version

Can you elaborate?

**Comment by Nikdedov** [comment]
> i am using flutterflow_ui and it forced me to use the old version

try "flutter pub add cached_network_image" before "flutter build ipa"

**Comment by michielpr** [comment]
Just encountered this error as well (from a project started yesterday). 
Had to use the "flutter pub add cached_network_image" to unblock it.

**Comment by aftabawan431** [comment]
I did flutter clean and everything but I fixed that by upgrading the the package to **cached_network_image: ^3.3.0**

**Comment by sudhir72350999** [comment]
try this it will work 100% sure for this error in flutter , use this in terminal
 "flutter pub add cached_network_image"

**Comment by Javaworld22** [comment]
Upgraded to cached_network_image: ^3.4.1 and this solved my issue
