### ISSUE TITLE
cached_network_image: ^3.2.3 can not support flutter sdk: '>=3.2.0-191.0.dev <4.0.0'

### ISSUE THREAD

**Issue by patismyname** [Baseflow/flutter_cached_network_image#878]
### Configuration

**Version:** 3.2.3

**Platform:** 
- [ ] :iphone: iOS 17
- [ ] :robot: Android

response error message
Failed to build iOS app
Error (Xcode): ../../.pub-cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/cached_network_image_provider.dart:78:54: Error: Type 'DecoderCallback' not found.

**Comment by renefloor** [comment]
Fix in 3.3.0
