### ISSUE TITLE
Update createImageCodecFromUrl 

### ISSUE THREAD

**Issue by victorcode1** [Baseflow/flutter_cached_network_image#890]
The webOnlyInstantiateImageCodecFromUrl API is deprecated and will be removed in a future release. Please use `createImageCodecFromUrl` from `dart:ui_web` instead.

**Comment by victorcode1** [comment]
@mister-rao To solve this problem you can fork the project, enter the web part and make certain changes. I will leave you in the link of how I did it. I already created the pull request but they have not approved it yet.
https://github.com/victorcode1/flutter_cached_network_image.git

**Comment by muhib349** [comment]
I've submitted a pull request for it #911. Hope they'll merge it soon.

**Comment by mehroze-zaidi** [comment]
Hi! Please merge the request as I'm facing the same warning message.

**Comment by sachin-dahal** [comment]
@renefloor @amorenew @amrgetment
Would be great if this could be merged #939

**Comment by mvanbeusekom** [comment]
Resolved in version 1.2.0 of the cached_network_image_web packages.
