### ISSUE TITLE
Gifs shows faster

### ISSUE THREAD

**Issue by beibaochufa** [Baseflow/flutter_cached_network_image#899]
## 🚀 Feature Requests

Gifs shows faster than laptop.
such as this gif. in the web, this is normal,in the flutter, this is faster.
https://makerworld.bblmw.com/makerworld/model/US44e6631cdd80fc/design/2023-12-03_isig2w2u3x57.gif

These Gifs have a common feature: they are all frame delay 0.

**Comment by danny-rachelblue** [comment]
@beibaochufa 
How did you solve it?
