### ISSUE TITLE
Error: Type 'DecoderCallback' not found.

### ISSUE THREAD

**Issue by jasonNumar** [Baseflow/flutter_cached_network_image#904]
## 🐛 Bug Report

Error when attempting to compile on local device (iOS):

Error (Xcode): ../../.pub-cache/hosted/pub.dev/cached_network_image-3.2.1/lib/src/image_provider/cached_network_image_provider.dart:76:54: Error: Type 'DecoderCallback' not found.

I solved the issue, but just want to leave this here for anyone who encounters the same error code. Note, this may be limited to my project only, as I have a number of extra dependencies, so take with a grain of salt.

Steps to solve:
1. Navigate to your pubspec.yaml file.
2. Update dependency "cached_network_image" to version 3.3.0.
3. Update "flutter_blurhash" to 0.8.23. 
4. run flutter pub get to update project.

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS

**Comment by muhib349** [comment]
I'm having this same issue. I would like to fix this issue. I will create a pull request for it.

**Comment by renefloor** [comment]
Should be fixed now
