### ISSUE TITLE
Failing to compile the Flutter application

### ISSUE THREAD

**Issue by alexn777** [Baseflow/flutter_cached_network_image#925]
## 🔙 Regression

The Flutter application fails to compile after I upgraded Flutter to 3.19.0. You can find the list of errors [here](https://github.com/Baseflow/flutter_cached_network_image/files/14313579/errors.txt). And here is what I have found out. cached_network_image 3.3.1 depends on flutter_cache_manager 3.3.1, which depends on http 1.1.2, which depends on web 0.3.0. The latest version of the web package, which is web 0.5.0 at the moment, fixes the issues. http 1.2.1 depends on web 0.5.0. The latest version of the flutter_cache_manager package, which is 3.3.1, still depends on the old version of the http package, which cases issues.

### Old (and correct) behavior
The Flutter application compiles without errors

### Current behavior
The Flutter application fails to compile

### Reproduction steps
Just try to compile the Flutter application

### Configuration

**cached_network_image version:** 3.3.1
**Flutter version** 3.19.0
**Dart version** 3.3.0

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by PcolBP** [comment]
Tried today with `flutter pub upgrade` and `flutter packages upgrade` and works. Try by yourself.

**Comment by alexn777** [comment]
A new version of Flutter was released yesterday and there were new updates to some packages I am using. Now the Flutter application compiles without issues. Thanks!
