### ISSUE TITLE
Warning in the console about the webOnlyInstantiateImageCodecFromUrl API is deprecated

### ISSUE THREAD

**Issue by Muffin8175** [Baseflow/flutter_cached_network_image#941]
## 🐛 Bug Report

<!--- Summary description of the bug ---#

I have a warning in my debug console:

> The webOnlyInstantiateImageCodecFromUrl API is deprecated and will be removed in a future release. Please use `createImageCodecFromUrl` from `dart:ui_web` instead.

There is indeed the use of `webOnlyInstantiateImageCodecFromUrl` in the code. Could you update the API, please?

### Expected behavior

no warning would be great ;)

### Reproduction steps

Any implementation of CachedNetworkImage widget

### Configuration

**Version:** 3.3.1

**Platform:** 
WEB

**Comment by Muffin8175** [comment]
I have a warning in my debug console:

> The webOnlyInstantiateImageCodecFromUrl API is deprecated and will be removed in a future release. Please use `createImageCodecFromUrl` from `dart:ui_web` instead.

There is indeed the use of `webOnlyInstantiateImageCodecFromUrl` in the code. Could you update the API, please?

**Comment by mvanbeusekom** [comment]
Resolved in version 1.2.0 of the cached_network_image_web packages.

**Comment by Muffin8175** [comment]
But... I use cached_network_image package. Is this additional? Even though, I added the package to my pub.yaml and imported, no change is there

**Comment by mvanbeusekom** [comment]
The cached_network_image_web is a package the cached_network_image depends on. If you open the pubspec.lock file you can find all packages and their version numbers your application eventually depends on.

The cached_network_image uses the `^1.0.0` constraint when depending on the cached_network_image_web package. Meaning "the latest version between 1.0.0 and 2.0.0".

Running `flutter pub upgrade` should ensure the last version is downloaded and available.

So there is no need to add the package to yourself.
