### ISSUE TITLE
Fade Animation

### ISSUE THREAD

**Issue by Gmaffia596** [Baseflow/flutter_cached_network_image#942]
Hi all,
I'm using CachedNetworkImage to render a lot of image from network. 
Everthing working fine, but when I quickly scroll up (viewing images that have already been rendered and cached) I see a lag which I imagine comes from the CachedNetworkImage fade animation.

I tried setting these two properties:
fadeOutDuration: Duration.zero,
fadeInDuration: Duration.zero,
but the problem persists even if it is less perceptible.

Any ideas on how to fix it or to remove this fade animation?

I add a screenshot of how I'm using the CachedNetworkImage widget:
![image](https://github.com/Baseflow/flutter_cached_network_image/assets/43602245/1d538d37-fddf-4e9b-8337-eb33b69fc7f7)

**Comment by rarazuma97** [comment]
Hi, I have the same issue!

**Comment by AshishSingh2001** [comment]
I have filed a issue in octo_image for this and raised a PR to fix this

more details in this issue
https://github.com/Baseflow/octo_image/issues/34
