### ISSUE TITLE
Update flutter_cache_manager version

### ISSUE THREAD

**Issue by Moatasem159** [Baseflow/flutter_cached_network_image#952]
can you update flutter_cache_manager version to last stable version

 **flutter_cache_manager 3.3.2**

**Comment by mvanbeusekom** [comment]
This is not necessary, the current constraint is `^3.3.1`. This means the latest version larger or equal to 3.3.1 and smaller than 4.0.0.

Please read the constraint resolving documentation carefully: https://dart.dev/tools/pub/versioning#constraint-solving

If you have issues locally try running `flutter pub upgrade flutter_cache_manager`.
