### ISSUE TITLE
upgrade packages

### ISSUE THREAD

**Issue by andim27** [Baseflow/flutter_cached_network_image#956]
## 🐛 Bug Report
cached_network_image 3.3.1 depends on flutter_cache_manager ^3.3.1, flutter_cache_manager >3.3.1 requires rxdart ^0.27.7.
Thus, cached_network_image ^3.3.1 requires rxdart ^0.27.7 or flutter_cache_manager 3.3.1.
Please upgrade to last packeges
**Platform:** 
- [ ] :robot: Android

**Comment by ervindobri** [comment]
I have the same issue, when I wanted to upgrade to Flutter 3.22.2, but I'm using rx dart too.
