### ISSUE TITLE
Image is not loading while progressindicator is running forever 

### ISSUE THREAD

**Issue by maiHydrogen** [Baseflow/flutter_cached_network_image#977]
return Card(
        elevation: 1,
        color: Colors.transparent,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        margin: EdgeInsets.symmetric(
            vertical: 4, horizontal: MediaQuery.of(context).size.width * 0.04),
        child: InkWell(
          onTap: () {},
          child: ListTile(
            leading: ClipRRect(
              borderRadius: BorderRadius.circular(
                MediaQuery.of(context).size.width * 0.4,
              ),
              child:
              CachedNetworkImage(
                width: MediaQuery.of(context).size.width * 0.054,
                height:  MediaQuery.of(context).size.width * 0.054,
                imageUrl:widget.user.Image,
                placeholder: (context, url) => CircularProgressIndicator(color: Colors.cyan,),
                errorWidget: (context, url, error) => Icon(Icons.error),
              ),
            ),
            title: Text(
              widget.user.Name,
              style: const TextStyle(color: Colors.white),
            ),
            subtitle: Text(
              widget.user.About,
              style: const TextStyle(color: Colors.white),
            ),
            trailing: Container(
              width: 15,
              height: 15,
              decoration: BoxDecoration(
                  color: Colors.cyanAccent,
                  borderRadius: BorderRadius.circular(10)),
            ),
            //trailing: const Text('12:00 AM',
            //style: TextStyle(color: Colors.white),),
          ),
        ));

**Comment by aturanb** [comment]
I had the same problem: 

"E/flutter (20781): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (20781): #0      PathProviderApi.getTemporaryPath (package:path_provider_android/messages.g.dart:44:7)
E/flutter (20781): <asynchronous suspension>
E/flutter (20781): #1      getTemporaryDirectory (package:path_provider/path_provider.dart:55:24)" to be exact. 

I made sure I had path_provider and did flutter clean. It fixed it.
