### ISSUE TITLE
Long height image issue on iOS

### ISSUE THREAD

**Issue by AnhToof** [Baseflow/flutter_cached_network_image#987]
### Expected behavior
Hello, i'm facing issue when display the long height image on iOS. It's weird

### Reproduction steps
`
CachedNetworkImage(
      fit: BoxFit.fill,
      imageUrl:"https://i.postimg.cc/Dz0Z18Pp/Vqngjtgiz-M5-SFd-C7b-Mj49-Hzq-Peu-Cf0h0-Voz-KX5-MMSnk2iar-O2-T3vt-Zx-KGs6vf4n-YUCy-Z83-If-HKxdjluuk1j6zw4e-AQf-QMLSAm3ou.jpg",
 )
`
### Result
![Simulator Screenshot - iPhone 15 Pro Max - 2024-11-07 at 09 05 06](https://github.com/user-attachments/assets/2701ad01-7e37-49b6-9750-e7d67653c0cf)

**Version:** latest

**Platform:** 
- [x] :iphone: iOS

**Comment by AnhToof** [comment]
> ## 🐛 Bug Report
> ### Expected behavior
> Hello, i'm facing issue when display the long height image on iOS
> 
> ### Reproduction steps
> CachedNetworkImage( fit: BoxFit.fill, imageUrl:"https://i.postimg.cc/Dz0Z18Pp/Vqngjtgiz-M5-SFd-C7b-Mj49-Hzq-Peu-Cf0h0-Voz-KX5-MMSnk2iar-O2-T3vt-Zx-KGs6vf4n-YUCy-Z83-If-HKxdjluuk1j6zw4e-AQf-QMLSAm3ou.jpg", )
> 
> ### Result
> ![Simulator Screenshot - iPhone 15 Pro Max - 2024-11-07 at 09 05 06](https://private-user-images.githubusercontent.com/26817561/383786212-2701ad01-7e37-49b6-9750-e7d67653c0cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NDU1NTQsIm5iZiI6MTczMDk0NTI1NCwicGF0aCI6Ii8yNjgxNzU2MS8zODM3ODYyMTItMjcwMWFkMDEtN2UzNy00OWI2LTk3NTAtZTdkNjc2NTNjMGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDAyMDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNzBkNTU0ZTAyMWM1MWFmNTQ1YjAxNjUwNjM2MzFlM2YwNjRiNzYxYzlhYmU0NzlmNzNlYjI4NDIwNzA1YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dsYXWqBFsLNxMuKgYt_D9sgGmifF0lZZ8alyzmYiUk4)
> 
> **Version:** latest
> 
> **Platform:**
> 
> * [x]  📱 iOS

**Comment by raman04-byte** [comment]
you can solve this issue by fitting the image accordingly

`fit: BoxFit.cover`

It would be best if you edited it accordingly. 

https://api.flutter.dev/flutter/painting/BoxFit.html

Follow this URL for better understanding.

**Comment by AnhToof** [comment]
In my case, any box fit doesn't work. It's a native issue. I use the webview to display instead
https://github.com/flutter/flutter/issues/158232

**Comment by raman04-byte** [comment]
Glad the issue got resolved.
